import {
  Add,
  ArrowDownward,
  ArrowUpward,
  Delete,
  EditNote,
  Save,
  Close,
  Refresh,
  Tune,
  AddLink,
  DomainAdd,
  LibraryAdd,
  AddShoppingCart,
  PersonAdd,
  GroupAdd,
  AddToQueue,
  PlaylistAddCircle,
  DashboardCustomize,
  LocalOffer,
  Addchart,
  RemoveCircleOutline,
  Engineering,
  PlaylistAdd,
  KeyboardArrowDown,
  Update,
  ArchiveOutlined,
  Restore,
  SearchRounded,
  Share,
  SwapVerticalCircle,
  MoreVert,
} from '@mui/icons-material';

export const actionIcons = {
  add: <Add />,

  addLink: <AddLink />,
  addClub: <DomainAdd />,
  addPlayer: <PersonAdd />,
  addTeam: <GroupAdd />,
  addTag: <LocalOffer />,
  addStats: <Addchart />,
  addVideo: <AddToQueue />,
  addRole: <Engineering />,
  addMeeting: <LibraryAdd />,
  addAbilities: <PlaylistAdd />,
  addGame: <PlaylistAddCircle />,
  addPayment: <AddShoppingCart />,
  addGameStats: <DashboardCustomize />,

  delete: <Delete />,
  edit: <EditNote />,
  save: <Save />,
  share: <Share />,
  close: <Close />,
  reset: <Refresh />,
  filter: <Tune />,
  remove: <RemoveCircleOutline />,
  arrowDown: <KeyboardArrowDown />,
  update: <Update />,
  archive: <ArchiveOutlined />,
  restore: <Restore />,
  search: <SearchRounded />,
  swapVert: <SwapVerticalCircle />,
  more: <MoreVert />,
  sortUp: <ArrowUpward />,
  sortDown: <ArrowDownward />
};
