import {
  Add,
  Addchart,
  AddLink,
  AddShoppingCart,
  AddToQueue,
  ArchiveOutlined,
  ArrowDownward,
  ArrowUpward,
  Close,
  Clear,
  DashboardCustomize,
  Delete,
  Done,
  Download,
  DomainAdd,
  EditNote,
  Engineering,
  ElectricBolt,
  GroupAdd,
  KeyboardArrowDown,
  LibraryAdd,
  LocalOffer,
  MoreVert,
  PersonAdd,
  PlaylistAdd,
  PlaylistAddCircle,
  Refresh,
  RemoveCircleOutline,
  Restore,
  RunCircle,
  Save,
  SearchRounded,
  Share,
  Sort,
  SwapVerticalCircle,
  Tune,
  Update,
} from '@mui/icons-material';

export const actionIcons = {
  add: <Add />,
  addAbilities: <PlaylistAdd />,
  addClub: <DomainAdd />,
  addGame: <PlaylistAddCircle />,
  addGames: <PlaylistAdd />,
  addGameStats: <DashboardCustomize />,
  addLink: <AddLink />,
  addMeeting: <LibraryAdd />,
  addPayment: <AddShoppingCart />,
  addPlayer: <PersonAdd />,
  addParent: <GroupAdd />,
  addPlayers: <GroupAdd />,
  addRole: <Engineering />,
  addStats: <Addchart />,
  addTag: <LocalOffer />,
  addTeam: <GroupAdd />,
  addTraining: <RunCircle />,
  addVideo: <AddToQueue />,
  archive: <ArchiveOutlined />,
  arrowDown: <KeyboardArrowDown />,
  close: <Close />,
  clear: <Clear />,
  delete: <Delete />,
  download: <Download />,
  edit: <EditNote />,
  filter: <Tune />,
  more: <MoreVert />,
  remove: <RemoveCircleOutline />,
  reset: <Refresh />,
  restore: <Restore />,
  save: <Save />,
  search: <SearchRounded />,
  share: <Share />,
  sortDown: <ArrowDownward />,
  sortDesc: <ArrowDownward />,
  sortUp: <ArrowUpward />,
  sortAsc: <ArrowUpward />,
  sort: <Sort />,
  swapVert: <SwapVerticalCircle />,
  update: <Update />,
  quickActions: <ElectricBolt />
};
