import {
  Assignment,
  AssistantPhoto,
  AccessTime,
  Attribution,
  AddLocationAlt,
  Bookmarks,
  Forward,
  History,
  Info,
  Details,
  LiveHelp,
  NotesRounded,
  PermContactCalendar,
  PlaylistAddCheckCircle,
  Percent,
  Today,
  Weekend,
  Visibility,
  ViewWeek,
  ScheduleSend,
  Summarize,
  FamilyRestroom
} from '@mui/icons-material';

export const generalIcons = {
  addLocation: <AddLocationAlt />,
  age: <PermContactCalendar />,
  date: <Today />,
  details: <Details />,
  help: <LiveHelp />,
  history: <History />,
  hour: <AccessTime />,
  info: <Info />,
  flag: <AssistantPhoto />,
  note: <NotesRounded />,
  notes: <NotesRounded />,
  weekend: <Weekend />,
  weekday: <ViewWeek />,
  check: <PlaylistAddCheckCircle />,
  profile: <Attribution />,
  readiness: <Visibility />,
  rate: <Percent />,
  report: <Assignment />,
  percent: <Percent />,
  reliability: <Visibility />,
  view: <Visibility />,
  calendar: <ScheduleSend />,
  summary: <Summarize />,
  parents: <FamilyRestroom />,
  liveTagging: <Bookmarks />
};
