import {
  Info,
  Forward,
  History,
  PermContactCalendar,
  Sports,
  Assistant,
  Dashboard,
  FitnessCenter,
  PersonSearch,
  AccountBox,
  ManageAccounts,
  Psychology,
  WorkspacePremium,
  DashboardCustomize,
  NotesRounded,
  AccessTime,
  Today,
  AddLocationAlt,
  LiveHelp
} from '@mui/icons-material';

export const genralIcons = {
  info: <Info />,
  upComing: <Forward />,
  history: <History />,
  age: <PermContactCalendar />,
  coach: <Sports />,
  assistant: <Assistant />,
  analyst: <Dashboard />,
  fitness: <FitnessCenter />,
  scout: <PersonSearch />,
  contactPerson: <AccountBox />,
  teamAdministrator: <AccountBox />,
  administrator: <ManageAccounts />,
  psychologist: <Psychology />,
  sportingDirector: <WorkspacePremium />,
  dashboard: <Dashboard />,
  note: <NotesRounded />,
  notes: <NotesRounded />,
  hour: <AccessTime />,
  date: <Today />,
  addLocation: <AddLocationAlt />,
  duration: <AccessTime />,
  help: <LiveHelp />
};
