import {
  AddCircleOutline,
  AutoAwesomeMosaic,
  ArrowBack,
  ArrowForward,
  BarChart,
  Business,
  Dashboard,
  DataObject,
  Groups,
  Home,
  Payment,
  PeopleAlt,
  TableView,
  Visibility,
  VideoLibrary,
  ViewCompactAlt,
  ViewTimeline,
  Insights,
  AccountTree,
  ManageSearch,
  PlaylistAdd
} from '@mui/icons-material';

export const navigationIcons = {
  cardList: <ViewCompactAlt />,
  clubs: <Business />,
  back: <ArrowBack />,
  forward: <ArrowForward />,
  dashboard: <Dashboard />,
  games: <ViewTimeline />,
  home: <Home />,
  hub: <AutoAwesomeMosaic />,
  payments: <Payment />,
  players: <PeopleAlt />,
  stats: <BarChart />,
  tableList: <TableView />,
  teams: <Groups />,
  videos: <VideoLibrary />,
  insights: <Insights />,
  squadSimulator: <AccountTree />,
  playersDatabase: <ManageSearch />,
  firestoreUsage: <DataObject />,
  viewLeague: <Visibility />,
  viewLaeague: <Visibility />,
  addLeague: <AddCircleOutline />,
  addSeason: <PlaylistAdd />
};
