import {
  CheckCircle,
  Dangerous,
  HourglassEmpty,
  TaskAlt,
  Block,
  OfflinePin,
  CurrencyExchange,
  EventBusy,
  Unpublished,
  Hail,
  Adjust,
  EventSeat,
  Beenhere,
  EventAvailable,
  Diversity3,
  Diversity2,
  PersonSearch,
  ScheduleSend,
  Sms,
  CancelScheduleSend,
  PsychologyAlt,
  EditCalendar,
  CalendarMonth,
  Lock,
  VideocamOff,
  Key,
  ThumbUp,
  ThumbDown
} from '@mui/icons-material';

export const statusIcons = {
  isPaid: <TaskAlt />,
  notActive: <Block />,
  active: <OfflinePin />,
  isNotPaid: <CurrencyExchange />,
  noneType: <Unpublished />,
  isNotProject: <Unpublished />,
  project: <Beenhere />,
  groupMeeting: <Diversity3 />,
  teamMeetting: <Diversity2 />,
  approved: <CheckCircle />,
  declined: <Dangerous />,
  awaitingReply: <HourglassEmpty />,
  candidate: <PersonSearch />,
  callscheduled: <ScheduleSend />,
  messageSent: <Sms />,
  reschedule: <CancelScheduleSend />,
  thinking: <PsychologyAlt />,
  lock: <Lock />,
  noVideo: <VideocamOff />,
  selected: <CheckCircle />,
  keyPlayer: <Key />,
  win: <ThumbUp />,
  loss: <ThumbDown />,
};
