import {
  AdsClick,
  Beenhere,
  Block,
  CancelScheduleSend,
  CheckCircle,
  Cached,
  Category,
  CurrencyExchange,
  Dangerous,
  Diversity2,
  Diversity3,
  HourglassEmpty,
  Key,
  Lock,
  FactCheck,
  MilitaryTech,
  OfflinePin,
  Outbound,
  PersonSearch,
  PersonRemove,
  Pending,
  PsychologyAlt,
  ReportProblem,
  ScheduleSend,
  Sms,
  Spoke,
  Snooze,
  TaskAlt,
  NextPlan,
  Notifications,
  Unpublished,
  VideocamOff,
  VisibilityOff,
  ErrorOutline,
  TrendingFlat,
  RocketLaunch,
  RateReview,
  Quiz,
  SentimentDissatisfied,
  Stars,
  ManageHistory,
} from '@mui/icons-material';

export const statusIcons = {
  active: <OfflinePin />,
  approved: <CheckCircle />,
  awaitingReply: <HourglassEmpty />,
  callscheduled: <ScheduleSend />,
  candidate: <PersonSearch />,
  declined: <Dangerous />,
  groupMeeting: <Diversity3 />,
  isNotPaid: <CurrencyExchange />,
  isPaid: <TaskAlt />,
  isNotProject: <Unpublished />,
  keyPlayer: <Key />,
  fringe: <PersonRemove />,
  corePlayer: <Spoke />,
  rotation: <Cached />,
  notReviewed: <VisibilityOff />,
  underReviewed: <RateReview />,
  inSquad: <FactCheck />,
  undecided: <Quiz />,
  notSuitable: <SentimentDissatisfied />,
  wantsToLeave: <Outbound />,
  lock: <Lock />,
  messageSent: <Sms />,
  current: <ManageHistory />,
  projection: <NextPlan />,
  noVideo: <VideocamOff />,
  noneType: <Unpublished />,
  notifications: <Notifications />,
  notActive: <Block />,
  project: <Beenhere />,
  reschedule: <CancelScheduleSend />,
  selected: <CheckCircle />,
  strength: <MilitaryTech />,
  teamMeeting: <Diversity2 />,
  teamMeetting: <Diversity2 />,
  thinking: <PsychologyAlt />,
  targets: <AdsClick />,
  weakness: <ReportProblem />,
  planned: <NextPlan />,
  completed: <CheckCircle />,
  canceled: <Block />,
  postponed: <Snooze />,
  noData: <ErrorOutline />,
  critical: <Dangerous />,
  weak: <ErrorOutline />,
  stable: <TrendingFlat />,
  upside: <RocketLaunch />,
  elite: <Stars />,
  loading: <Pending />,
  warning: <ErrorOutline />,
  category: <Category />,
};
