// // src/features/playersDatabase/components/playersDatabasePage.sx.js

const palette = {
  bg: '#eef2f5',
  ink: '#17202a',
  muted: '#64717f',
  panel: '#ffffff',
  line: '#d8e0e7',
  slate: '#24313f',
  slateSoft: '#e6ebef',
  teal: '#0f766e',
  tealSoft: '#dff5f2',
  blue: '#2563eb',
  blueSoft: '#e8f0ff',
  amber: '#b7791f',
  amberSoft: '#fff3d6',
  green: '#15803d',
  greenSoft: '#e7f7ec',
  red: '#b42318',
  redSoft: '#ffe9e7',
}

export const pageSx = {
  root: {
    minHeight: 'calc(100vh - 72px)',
    height: { xs: 'auto', xl: 'calc(100vh - 72px)' },
    bgcolor: palette.bg,
    color: palette.ink,
    p: { xs: 1, md: 1.5 },
    overflow: { xs: 'visible', xl: 'hidden' },
  },
  shell: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', xl: 'minmax(0, 1fr) 360px' },
    gap: 2,
    alignItems: 'start',
    minHeight: 0,
  },
  hero: {
    mb: 1,
    p: { xs: 1.25, md: 1.5 },
    borderRadius: '10px',
    bgcolor: palette.slate,
    color: '#fff',
    display: 'grid',
    gap: 1,
    border: '1px solid rgba(255,255,255,0.08)',
    boxShadow: '0 20px 50px rgba(18, 31, 45, 0.18)',
  },
  heroTop: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    justifyContent: 'space-between',
    alignItems: { xs: 'stretch', md: 'flex-start' },
    gap: 1,
  },
  eyebrow: {
    color: '#9edbd4',
    fontWeight: 700,
    letterSpacing: 0,
    fontSize: 12,
  },
  title: {
    color: '#fff',
    fontWeight: 700,
    fontSize: { xs: 24, md: 30 },
    lineHeight: 1.15,
  },
  subtitle: {
    color: 'rgba(255,255,255,0.74)',
    maxWidth: 760,
    lineHeight: 1.45,
    fontSize: 13,
    mt: 0.25,
  },
  actionRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 0.75,
    justifyContent: { xs: 'stretch', md: 'flex-start' },
    alignItems: 'flex-start',
    '& button': {
      minWidth: { xs: 'calc(50% - 4px)', sm: 'auto' },
      minHeight: 36,
      px: 1.25,
      py: 0.5,
      borderRadius: '8px',
    },
  },
  kpiGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: 'repeat(2, minmax(0, 1fr))',
      md: 'repeat(4, minmax(0, 1fr))',
    },
    gap: 0.75,
  },
  kpi: {
    borderRadius: '8px',
    bgcolor: 'rgba(255,255,255,0.08)',
    border: '1px solid rgba(255,255,255,0.12)',
    p: 1,
    minHeight: 68,
  },
  kpiLabel: {
    color: 'rgba(255,255,255,0.68)',
    fontSize: 12,
  },
  kpiValue: {
    color: '#fff',
    fontSize: { xs: 20, md: 24 },
    fontWeight: 700,
    lineHeight: 1.1,
    mt: 0.35,
  },
  kpiNote: {
    color: 'rgba(255,255,255,0.62)',
    fontSize: 11,
    mt: 0.35,
  },
  panel: {
    bgcolor: palette.panel,
    border: `1px solid ${palette.line}`,
    borderRadius: '10px',
    boxShadow: '0 14px 38px rgba(22, 34, 51, 0.08)',
    overflow: 'hidden',
    minHeight: 0,
  },
  importPreview: {
    mb: 1,
    p: 1,
    bgcolor: palette.panel,
    border: `1px solid ${palette.line}`,
    borderRadius: '10px',
    boxShadow: '0 10px 28px rgba(22, 34, 51, 0.06)',
  },
  importPreviewHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 1,
    mb: 0.75,
  },
  importPreviewTextarea: {
    mb: 0.75,
    fontSize: 13,
  },
  importPasteBox: {
    width: '100%',
    height: '100%',
    minHeight: 0,
    maxHeight: '100%',
    boxSizing: 'border-box',
    resize: 'none',
    overflow: 'auto',
    border: `1px solid ${palette.line}`,
    borderRadius: '8px',
    p: 1,
    font: 'inherit',
    fontSize: 13,
    lineHeight: 1.6,
    outline: 'none',
    bgcolor: '#fff',
    color: palette.ink,
    '&:focus': {
      borderColor: palette.blue,
      boxShadow: '0 0 0 3px rgba(37, 99, 235, 0.14)',
    },
    '&:disabled': {
      bgcolor: '#f4f6f8',
      color: palette.muted,
    },
  },
  importPasteHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 1,
    mb: 0.5,
  },
  importZone: {
    p: 1,
    borderRadius: '8px',
    display: 'grid',
    gridTemplateRows: 'auto minmax(0, 1fr)',
    gap: 1,
    minHeight: 0,
    overflow: 'hidden',
  },
  importPreviewZone: {
    p: 1,
    borderRadius: '8px',
    display: 'grid',
    gridTemplateRows: 'auto minmax(0, 1fr)',
    gap: 1,
    minHeight: 0,
    overflow: 'hidden',
  },
  importPreviewTop: {
    display: 'grid',
    gap: 0.75,
  },
  summaryChips: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 0.75,
  },
  importTableWrap: {
    borderRadius: '8px',
    overflowY: 'auto',
    overflowX: 'hidden',
    minHeight: 0,
    maxHeight: '100%',
  },
  importPreviewTable: {
    width: '100%',
    tableLayout: 'fixed',
    '& th': {
      whiteSpace: 'nowrap',
      fontWeight: 700,
      px: 0.75,
    },
    '& td': {
      whiteSpace: 'nowrap',
      verticalAlign: 'middle',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      px: 0.75,
      fontSize: 13,
    },
    '& th:nth-of-type(1), & td:nth-of-type(1)': {
      width: 76,
    },
    '& th:nth-of-type(2), & td:nth-of-type(2)': {
      width: 58,
    },
    '& th:nth-of-type(3), & td:nth-of-type(3)': {
      width: '30%',
    },
  },
  importContextGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: 'repeat(2, minmax(0, 1fr))',
      md: 'repeat(4, minmax(0, 1fr))',
      xl: 'repeat(7, minmax(0, 1fr))',
    },
    gap: 0.75,
    mb: 0.75,
  },
  importPreviewActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 1,
    mb: 0.75,
  },
  importPreviewSubHeader: {
    mt: 1,
    mb: 0.75,
    display: 'flex',
    justifyContent: 'space-between',
    gap: 1,
    alignItems: 'center',
  },
  importPreviewGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: 'repeat(2, minmax(0, 1fr))',
      md: 'repeat(4, minmax(0, 1fr))',
      xl: 'repeat(8, minmax(0, 1fr))',
    },
    gap: 1,
    mt: 1,
  },
  importPreviewItem: {
    minHeight: 52,
    p: 0.75,
    borderRadius: '8px',
    bgcolor: '#f7fafc',
    border: `1px solid ${palette.line}`,
  },
  importPreviewValue: {
    fontSize: 18,
    lineHeight: 1,
    fontWeight: 700,
  },
  importPreviewLabel: {
    color: palette.muted,
    fontSize: 12,
    mt: 0.45,
  },
  importSaveSuccess: {
    mt: 1,
    p: 1,
    borderRadius: '8px',
    bgcolor: palette.greenSoft,
    color: palette.green,
    fontWeight: 700,
  },
  importSaveError: {
    mt: 1,
    p: 1,
    borderRadius: '8px',
    bgcolor: palette.redSoft,
    color: palette.red,
    fontWeight: 700,
  },
  importIssueList: {
    mt: 1,
    p: 1,
    maxHeight: { xs: 120, xl: 135 },
    overflow: 'auto',
    borderRadius: '8px',
    border: `1px solid ${palette.line}`,
    bgcolor: '#fff',
    color: palette.red,
    display: 'grid',
    gap: 0.5,
  },
  importFixList: {
    mt: 1,
    p: 1,
    minHeight: { xs: 220, xl: 280 },
    maxHeight: { xs: '36vh', xl: '40vh' },
    overflow: 'auto',
    borderRadius: '8px',
    border: `1px solid ${palette.line}`,
    bgcolor: '#fff',
    display: 'grid',
    gap: 0.75,
  },
  importFixRow: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'minmax(260px, 1fr) minmax(420px, 1.5fr)' },
    gap: 1,
    alignItems: 'center',
    p: 0.75,
    borderRadius: '8px',
    bgcolor: '#f8fafc',
    border: `1px solid ${palette.line}`,
  },
  importFixText: {
    minWidth: 0,
  },
  importClubAutocomplete: {
    minWidth: 0,
    bgcolor: '#fff',
  },
  leagueBoard: {
    mb: 1.5,
    bgcolor: palette.panel,
    border: `1px solid ${palette.line}`,
    borderRadius: '10px',
    boxShadow: '0 12px 32px rgba(22, 34, 51, 0.07)',
    overflow: 'hidden',
  },
  leagueBoardTop: {
    p: 1.5,
    borderBottom: `1px solid ${palette.line}`,
    display: 'flex',
    flexDirection: { xs: 'column', lg: 'row' },
    justifyContent: 'space-between',
    gap: 1.5,
    alignItems: { xs: 'stretch', lg: 'center' },
  },
  leagueNavControls: {
    display: 'flex',
    gap: 0.75,
    alignItems: 'center',
    justifyContent: { xs: 'space-between', lg: 'flex-start' },
  },
  leagueEmptyState: {
    minHeight: { xs: 260, xl: 'calc(100vh - 330px)' },
    display: 'grid',
    alignContent: 'center',
    justifyItems: 'center',
    gap: 1,
    p: 3,
    textAlign: 'center',
    bgcolor: '#fbfcfd',
  },
  leagueEmptyTitle: {
    fontWeight: 700,
  },
  leagueEmptyText: {
    maxWidth: 520,
    color: palette.muted,
    lineHeight: 1.6,
  },
  leagueFormDialog: {
    width: 'min(1080px, calc(100vw - 40px))',
    height: 'min(760px, calc(100vh - 56px))',
    maxHeight: 'calc(100vh - 56px)',
    borderRadius: '10px',
    overflow: 'hidden',
    p: { xs: 1.5, md: 2 },
    display: 'grid',
    gridTemplateRows: {
      xs: 'auto auto 190px minmax(0, 1fr) auto auto',
      xl: 'auto auto 220px minmax(0, 1fr) auto auto',
    },
    gap: 1,
  },
  leagueFormGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))' },
    gap: 1,
    mt: 1,
  },
  leagueDerivedBox: {
    mt: 1,
    p: 1,
    borderRadius: '8px',
    bgcolor: palette.slateSoft,
    color: palette.slate,
  },
  leagueFormActions: {
    display: 'flex',
    justifyContent: 'flex-start',
    gap: 1,
    mt: 1.5,
  },
  leagueDetailBody: {
    p: 1,
    bgcolor: '#f6f8fa',
    minHeight: { xs: 260, xl: 'calc(100vh - 300px)' },
  },
  leagueSelect: {
    minWidth: 132,
    borderRadius: '8px',
  },
  iconBtn: {
    minWidth: 34,
    width: 34,
    height: 34,
    p: 0,
    borderRadius: '8px',
  },
  leagueStage: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', xl: '280px minmax(0, 1fr)' },
    minHeight: 0,
    p: 1,
    gap: 1,
    bgcolor: '#f6f8fa',
  },
  leagueList: {
    border: `1px solid ${palette.line}`,
    borderRadius: '8px',
    bgcolor: '#ffffff',
    p: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    alignContent: 'flex-start',
    justifyContent: 'flex-start',
    gap: 0.5,
    maxHeight: { xs: 160, xl: 'calc(100vh - 292px)' },
    overflow: 'auto',
  },
  leagueListItem: {
    justifyContent: 'flex-start',
    minHeight: 56,
    borderRadius: '8px',
    textAlign: 'left',
    whiteSpace: 'normal',
    border: '1px solid transparent',
    flex: '0 0 auto',
    '&.isSelected': {
      bgcolor: '#e8f1ff',
      color: palette.ink,
      borderColor: '#b8d3ff',
      boxShadow: 'none',
    },
    '&.isSelected *': {
      color: `${palette.ink} !important`,
    },
    '&.isSelected:hover': {
      bgcolor: '#dceaff',
    },
    '&.MuiButton-plain': {
      color: palette.ink,
    },
    '&.MuiButton-plain:hover': {
      bgcolor: '#f1f5f9',
    },
  },
  leagueListText: {
    minWidth: 0,
    width: '100%',
  },
  leagueListTitle: {
    fontWeight: 700,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  leagueListMeta: {
    color: palette.muted,
    mt: 0.25,
  },
  leagueTablePanel: {
    minWidth: 0,
    display: 'grid',
    gridTemplateRows: 'auto minmax(0, 1fr)',
    bgcolor: '#ffffff',
    border: `1px solid ${palette.line}`,
    borderRadius: '8px',
    overflow: 'hidden',
    minHeight: { xs: 460, xl: 'calc(100vh - 280px)' },
  },
  leagueMetaBar: {
    p: 1.5,
    display: 'flex',
    flexDirection: { xs: 'column', lg: 'row' },
    justifyContent: 'space-between',
    gap: 1,
    alignItems: { xs: 'stretch', lg: 'center' },
    borderBottom: `1px solid ${palette.line}`,
  },
  leagueTitle: {
    fontWeight: 700,
  },
  leagueChips: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 0.75,
  },
  leagueTableWrap: {
    overflow: 'auto',
    maxHeight: { xs: '70vh', xl: 'calc(100vh - 225px)' },
    minHeight: { xs: 410, xl: 'calc(100vh - 340px)' },
    p: 1,
    bgcolor: '#ffffff',
    position: 'relative',
  },
  leagueTable: {
    minWidth: 860,
    width: '100%',
    height: 'auto',
    borderCollapse: 'collapse',
    tableLayout: 'fixed',
    border: `1px solid ${palette.line}`,
    borderRadius: '8px',
    overflow: 'clip',
    '& th, & td': {
      p: 1.15,
      borderBottom: `1px solid ${palette.line}`,
      textAlign: 'center',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      fontSize: 13,
    },
    '& th': {
      bgcolor: '#0f1d4d',
      color: '#fff',
      fontWeight: 700,
      position: 'sticky',
      top: -1,
      zIndex: 2,
      boxShadow: `0 1px 0 ${palette.line}`,
    },
    '& th:nth-of-type(2), & td:nth-of-type(2)': {
      textAlign: 'left',
      width: 220,
    },
    '& tbody tr:nth-of-type(even) td': {
      bgcolor: '#f6f8fa',
    },
    '& tbody tr.isPlaceholder td': {
      color: palette.muted,
    },
    '& tbody tr:first-of-type td': {
      borderTop: `2px solid ${palette.green}`,
    },
    '& td:first-of-type': {
      fontWeight: 700,
      color: '#0f1d4d',
    },
  },
  panelHeader: {
    p: 1.75,
    borderBottom: `1px solid ${palette.line}`,
    display: 'flex',
    justifyContent: 'space-between',
    gap: 1.5,
    alignItems: 'center',
  },
  panelTitle: {
    fontWeight: 700,
  },
  panelMeta: {
    color: palette.muted,
    mt: 0.25,
  },
  filters: {
    p: 1.5,
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr 1fr',
      lg: '1.4fr repeat(5, minmax(120px, 1fr))',
    },
    gap: 1,
    borderBottom: `1px solid ${palette.line}`,
    bgcolor: '#fbfcfd',
  },
  fieldLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: 700,
    mb: 0.5,
  },
  fieldBox: {
    minHeight: 38,
    borderRadius: '8px',
    border: `1px solid ${palette.line}`,
    bgcolor: '#fff',
    px: 1.2,
    display: 'flex',
    alignItems: 'center',
    color: '#3a4652',
    fontSize: 13,
  },
  fieldControl: {
    minHeight: 38,
    borderRadius: '8px',
    fontSize: 13,
  },
  tableWrap: {
    maxHeight: { xs: '42vh', xl: 'calc(100vh - 430px)' },
    overflow: 'auto',
    minHeight: 0,
  },
  table: {
    minWidth: 1060,
    width: '100%',
    borderCollapse: 'collapse',
    tableLayout: 'fixed',
    '& th, & td': {
      p: 1.35,
      borderBottom: `1px solid ${palette.line}`,
      textAlign: 'left',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      fontSize: 13,
    },
    '& th': {
      bgcolor: '#fbfcfd',
      color: palette.muted,
      fontSize: 12,
      fontWeight: 700,
    },
    '& tr.isSelected td': {
      bgcolor: '#f2fbf9',
    },
    '& tbody tr': {
      cursor: 'pointer',
    },
  },
  playerName: {
    fontWeight: 700,
  },
  subText: {
    color: palette.muted,
    fontSize: 12,
    mt: 0.25,
  },
  footer: {
    p: 1.5,
    display: 'flex',
    justifyContent: 'space-between',
    color: palette.muted,
    bgcolor: '#fbfcfd',
    fontSize: 13,
  },
  footerActions: {
    display: 'flex',
    gap: 0.5,
    alignItems: 'center',
  },
  sidePanel: {
    position: { xs: 'static', xl: 'sticky' },
    top: 18,
    maxHeight: { xs: 'none', xl: 'calc(100vh - 132px)' },
  },
  sideBody: {
    p: 1.75,
    display: 'grid',
    gap: 1.5,
    maxHeight: { xs: 'none', xl: 'calc(100vh - 208px)' },
    overflow: 'auto',
  },
  playerHead: {
    display: 'grid',
    gridTemplateColumns: '58px 1fr',
    gap: 1.25,
    alignItems: 'center',
  },
  avatar: {
    width: 58,
    height: 58,
    borderRadius: '12px',
    bgcolor: palette.tealSoft,
    color: palette.teal,
    display: 'grid',
    placeItems: 'center',
    fontWeight: 700,
    fontSize: 22,
  },
  note: {
    bgcolor: '#fff8e6',
    border: '1px solid #f3d48b',
    color: '#6f4b00',
    borderRadius: '8px',
    p: 1.25,
    lineHeight: 1.55,
  },
  section: {
    border: `1px solid ${palette.line}`,
    borderRadius: '8px',
    p: 1.35,
  },
  sectionTitle: {
    fontWeight: 700,
    mb: 1,
  },
  factGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 1,
  },
  fact: {
    bgcolor: palette.slateSoft,
    borderRadius: '8px',
    p: 1.1,
    minHeight: 62,
  },
  factLabel: {
    color: palette.muted,
    fontSize: 12,
  },
  factValue: {
    fontWeight: 700,
    mt: 0.5,
  },
  timeline: {
    display: 'grid',
    gap: 1,
  },
  timelineRow: {
    display: 'grid',
    gridTemplateColumns: '92px 1fr',
    gap: 1,
    fontSize: 13,
  },
  timelineDate: {
    color: palette.muted,
    fontWeight: 700,
  },
  statusBadge: (status) => {
    const map = {
      positive: { bgcolor: palette.greenSoft, color: palette.green },
      stable: { bgcolor: palette.amberSoft, color: palette.amber },
      decline: { bgcolor: palette.redSoft, color: palette.red },
      active: { bgcolor: palette.blueSoft, color: palette.blue },
      on_hold: { bgcolor: palette.amberSoft, color: palette.amber },
      closed: { bgcolor: palette.redSoft, color: palette.red },
      none: { bgcolor: palette.slateSoft, color: palette.slate },
    }

    return {
      ...(map[status] || map.none),
      borderRadius: 999,
      px: 1,
      py: 0.35,
      fontSize: 12,
      fontWeight: 700,
      display: 'inline-flex',
      justifyContent: 'center',
      maxWidth: '100%',
    }
  },
}
