import { COLORS, devPlanColors } from '../../../../../../ui/core/theme/Colors.js'

export const teamDiagnosticSignalsModalSx = {
  trigger: {
    width: 24,
    minWidth: 24,
    height: 24,
    minHeight: 24,
    p: 0.35,
    color: devPlanColors.secondary,
    bgcolor: devPlanColors.secondaryLight,
    '&:hover': {
      color: devPlanColors.primary,
      bgcolor: devPlanColors.primaryLight,
    },
  },
  content: {
    display: 'grid',
    gap: 1.25,
  },
  group: {
    display: 'grid',
    gap: 0.5,
    p: 1,
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 9,
    bgcolor: devPlanColors.surface,
  },
  groupTitle: {
    color: devPlanColors.primaryDark,
    fontSize: 13,
    fontWeight: 800,
  },
  item: {
    display: 'grid',
    gap: 0.25,
    py: 0.2,
  },
  itemMain: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.55,
    color: devPlanColors.secondary,
    fontSize: 12,
    lineHeight: 1.35,
  },
  conditions: {
    pr: 2.1,
    color: devPlanColors.secondary,
    fontSize: 10.5,
    lineHeight: 1.35,
  },
  signalId: {
    color: devPlanColors.primaryDark,
    fontFamily: 'monospace',
    fontSize: 10.5,
    fontWeight: 800,
    direction: 'ltr',
  },
  itemIcon: {
    display: 'inline-flex',
    color: devPlanColors.secondary,
    '& svg': { fontSize: 12 },
  },
  itemIconReview: {
    color: `${COLORS.status.success.solid} !important`,
    '& svg, & svg *': {
      color: `${COLORS.status.success.solid} !important`,
      fill: `${COLORS.status.success.solid} !important`,
    },
  },
  itemSelected: {
    mx: -0.45,
    px: 0.45,
    borderRadius: 6,
    bgcolor: devPlanColors.primaryLight,
  },
  matrix: {
    display: 'grid',
    gridTemplateColumns: 'minmax(72px, 0.8fr) repeat(3, minmax(0, 1fr))',
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 8,
    overflow: 'hidden',
  },
  squadMatrix: {
    gridTemplateColumns: 'minmax(100px, 0.85fr) repeat(2, minmax(0, 1fr))',
  },
  matrixHeader: {
    p: 0.65,
    bgcolor: devPlanColors.secondaryLight,
    color: devPlanColors.primaryDark,
    fontSize: 10,
    fontWeight: 800,
    textAlign: 'center',
    borderLeft: `1px solid ${devPlanColors.border}`,
    borderBottom: `1px solid ${devPlanColors.border}`,
  },
  headerBelow: { color: COLORS.status.danger.solid, fontWeight: 900 },
  headerAt: { color: COLORS.status.success.solid, fontWeight: 900 },
  headerAbove: { color: COLORS.status.warning.solid, fontWeight: 900 },
  matrixPerformance: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    p: 0.7,
    bgcolor: devPlanColors.secondaryLight,
    color: devPlanColors.primaryDark,
    fontSize: 11,
    fontWeight: 800,
    textAlign: 'center',
    borderLeft: `1px solid ${devPlanColors.border}`,
    borderBottom: `1px solid ${devPlanColors.border}`,
  },
  matrixCell: {
    minWidth: 0,
    minHeight: 92,
    px: 1.45,
    py: 0.85,
    textAlign: 'center',
    borderLeft: `1px solid ${devPlanColors.border}`,
    borderBottom: `1px solid ${devPlanColors.border}`,
  },
  matrixCellEmpty: {
    bgcolor: devPlanColors.surface,
  },
  matrixCellSelected: {
    bgcolor: COLORS.status.success.softBg,
  },
  matrixItem: {
    display: 'grid',
    minWidth: 0,
    gap: 0.45,
    color: devPlanColors.secondary,
    fontSize: 10,
    lineHeight: 1.3,
    textAlign: 'center',
  },
  matrixItemTitle: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: 0.35,
    color: devPlanColors.primaryDark,
    fontSize: 11.5,
    fontWeight: 700,
    lineHeight: 1.4,
  },
  matrixTask: {
    color: devPlanColors.tertiaryDark,
    fontSize: 9.5,
    fontWeight: 700,
    lineHeight: 1.35,
    textAlign: 'center',
  },
  matrixExplanation: {
    color: devPlanColors.secondary,
    fontSize: 9.5,
    lineHeight: 1.35,
    textAlign: 'center',
  },
  matrixAction: {
    minWidth: 0,
    color: devPlanColors.tertiaryDark,
    fontSize: 9.5,
    fontWeight: 700,
    lineHeight: 1.35,
    textAlign: 'center',
    overflowWrap: 'anywhere',
  },
  matrixActionLabel: {
    color: devPlanColors.primaryDark,
    fontWeight: 900,
  },
  matrixTaskUrgent: {
    color: COLORS.status.danger.solid,
    fontWeight: 900,
  },
  matrixSignalId: {
    display: 'block',
    justifySelf: 'center',
    mb: 0.7,
    color: devPlanColors.secondary,
    fontFamily: 'monospace',
    fontSize: 9.5,
    fontWeight: 500,
    direction: 'ltr',
  },
  matrixItemSelected: {
    mx: -0.25,
    px: 0.25,
    borderRadius: 5,
    bgcolor: COLORS.status.success.softBg,
  },
  classificationNote: {
    p: 0.85,
    borderRadius: 8,
    bgcolor: devPlanColors.secondaryLight,
    color: devPlanColors.secondary,
    fontSize: 11,
    lineHeight: 1.4,
  },
  classificationNoteSelected: {
    bgcolor: COLORS.status.success.softBg,
  },
}
