import { devPlanColors } from '../../../../../../ui/core/theme/Colors.js'

const fullBorder = `1px solid ${devPlanColors.border}`

export const teamOverviewSx = {
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1.5,
    minWidth: 0,
  },
  sectionHeading: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 1,
  },
  sectionTitle: {
    color: devPlanColors.primaryDark,
    fontSize: 18,
    fontWeight: 800,
  },
  sectionSubtitle: {
    mt: 0.25,
    color: devPlanColors.subText,
    fontSize: 12,
    fontWeight: 500,
  },
  performanceGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 1.25,
    '@media (max-width: 980px)': {
      gridTemplateColumns: '1fr',
    },
  },
  contextGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.25fr) minmax(280px, 0.75fr)',
    gap: 1.25,
    '@media (max-width: 1100px)': {
      gridTemplateColumns: '1fr',
    },
  },
  performanceCard: {
    p: 1.5,
    border: fullBorder,
    borderRadius: 12,
    bgcolor: devPlanColors.surface,
    minWidth: 0,
  },
  balanceCard: {
    p: 1.5,
    border: fullBorder,
    borderRadius: 12,
    bgcolor: devPlanColors.surface,
    minWidth: 0,
  },
  structureCard: {
    p: 1.5,
    border: fullBorder,
    borderRadius: 12,
    bgcolor: devPlanColors.surface,
    minWidth: 0,
  },
  cardHeading: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1.5,
    minWidth: 0,
  },
  headingText: { minWidth: 0 },
  eyebrow: {
    color: devPlanColors.subText,
    fontSize: 11,
    fontWeight: 700,
  },
  cardTitle: {
    color: devPlanColors.primaryDark,
    fontSize: 16,
    fontWeight: 800,
  },
  performanceState: {
    px: 1.15,
    py: 0.55,
    borderRadius: 999,
    bgcolor: devPlanColors.primaryLight,
    color: devPlanColors.primary,
    fontSize: 13,
    fontWeight: 800,
    whiteSpace: 'nowrap',
  },
  metricsRow: {
    mt: 1.35,
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 0.75,
  },
  metric: {
    minWidth: 0,
    p: 1,
    borderRadius: 9,
    bgcolor: devPlanColors.secondaryLight,
    textAlign: 'center',
  },
  metricValue: {
    color: devPlanColors.primaryDark,
    fontSize: 15,
    fontWeight: 800,
  },
  metricLabel: {
    mt: 0.15,
    color: devPlanColors.subText,
    fontSize: 10.5,
    fontWeight: 600,
  },
  reliability: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.45,
    px: 0.9,
    py: 0.45,
    borderRadius: 999,
    bgcolor: devPlanColors.secondaryLight,
    color: devPlanColors.secondary,
    fontSize: 11,
    fontWeight: 700,
    whiteSpace: 'nowrap',
    cursor: 'help',
  },
  balanceMetrics: {
    mt: 1.35,
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 0.75,
    '@media (max-width: 720px)': {
      gridTemplateColumns: '1fr',
    },
  },
  balanceMetric: {
    p: 1,
    borderRadius: 9,
    bgcolor: devPlanColors.secondaryLight,
    cursor: 'help',
  },
  balanceMetricLabel: {
    color: devPlanColors.subText,
    fontSize: 10.5,
    fontWeight: 600,
  },
  balanceMetricValue: {
    mt: 0.2,
    color: devPlanColors.primaryDark,
    fontSize: 13,
    fontWeight: 800,
  },
  coverageText: {
    color: devPlanColors.subText,
    fontSize: 11,
    fontWeight: 700,
    whiteSpace: 'nowrap',
  },
  lineRow: {
    mt: 1.35,
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 0.75,
  },
  emptyText: {
    mt: 1.35,
    p: 1.1,
    borderRadius: 9,
    bgcolor: devPlanColors.secondaryLight,
    color: devPlanColors.subText,
    fontSize: 12,
    fontWeight: 600,
  },
}
