// features/playersDatabase/ui/pages/searchPage/sx/searchResults.sx.js

import { devPlanColors } from '../../../../../../ui/core/theme/Colors.js'

const panelBase = {
  minWidth: 0,
  minHeight: 0,
  p: 0,
  overflow: 'hidden',
  borderRadius: 8,
  border: '1px solid #dbe5f4',
  boxShadow: '0 8px 22px rgba(11, 31, 77, 0.05)',
}

export const searchResultsSx = {
  panel: {
    ...panelBase,
    display: 'grid',
    gridTemplateRows: '58px minmax(0, 1fr)',
  },
  header: {
    px: 1.4,
    display: 'flex',
    gap: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid #dbe5f4',
  },
  title: { color: devPlanColors.primaryDark, fontWeight: 700 },
  subtitle: { color: devPlanColors.secondary },
  count: {
    px: 1.1,
    py: 0.35,
    borderRadius: 999,
    bgcolor: devPlanColors.primaryLight,
    color: devPlanColors.primary,
    fontSize: 12,
    fontWeight: 700,
  },
  activeQuery: {
    minWidth: 0,
    minHeight: 44,
    px: 1.25,
    py: 0.8,
    display: 'flex',
    gap: 1,
    alignItems: 'center',
    borderBottom: '1px solid #edf1f5',
    bgcolor: '#fbfcfe',
  },
  activeQueryCompact: { minWidth: 0, display: 'grid', gap: 0.6 },
  activeQueryLabel: { flex: '0 0 auto', color: devPlanColors.secondary, fontWeight: 700 },
  activeQueryItems: { minWidth: 0, display: 'flex', flexWrap: 'wrap', gap: 0.5 },
  activeChip: { cursor: 'pointer', bgcolor: devPlanColors.primaryLight, color: devPlanColors.primary },
  emptyQuery: { color: devPlanColors.secondary, lineHeight: 1.45 },
  tableWrap: {
    width: '100%',
    height: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'auto',
    border: 0,
    borderRadius: 0,
  },
  table: {
    width: '100%',
    minWidth: 1180,
    tableLayout: 'fixed',
    '& th, & td': { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  },
  insightsPanel: {
    ...panelBase,
    display: 'grid',
    gridTemplateRows: '58px minmax(0, 1fr)',
  },
  insightsHeader: {
    px: 1.25,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 0.8,
    borderBottom: '1px solid #dbe5f4',
  },
  resetButton: { color: devPlanColors.primary },
  insightsScroll: { minHeight: 0, overflowY: 'auto', p: 1.15, gap: 1.1 },
  summaryGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: 0.7 },
  summaryItem: { p: 0.9, borderRadius: 7, bgcolor: '#f4f7fb', border: '1px solid #e6edf5' },
  summaryLabel: { color: devPlanColors.secondary },
  summaryValue: { mt: 0.2, color: devPlanColors.primaryDark, fontSize: 24, fontWeight: 700 },
  activeQueryPanel: { display: 'grid', gap: 0.7 },
  insightBlock: { gap: 0.55 },
  insightTitle: { color: devPlanColors.primaryDark, fontWeight: 700 },
  insightRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 0.8 },
  insightLabel: { minWidth: 0, color: devPlanColors.secondary, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  insightValue: { flex: '0 0 auto', minWidth: 28, px: 0.7, py: 0.15, borderRadius: 999, textAlign: 'center', bgcolor: devPlanColors.primaryLight, color: devPlanColors.primary, fontSize: 12, fontWeight: 700 },
  insightEmpty: { color: devPlanColors.secondary },
  avatarColumn: { width: 44, px: 0.5, textAlign: 'center' },
  playerColumn: { width: 150 },
  yearColumn: { width: 68, textAlign: 'center' },
  teamColumn: { width: 145 },
  leagueColumn: { width: 150 },
  levelColumn: { width: 58, textAlign: 'center' },
  numberColumn: { width: 68, textAlign: 'center' },
  profileColumn: { width: 130 },
  scoreColumn: { width: 72, textAlign: 'center' },
  actionsColumn: { width: 78, textAlign: 'center' },
  playerAvatar: {
    width: 28,
    height: 28,
    display: 'block',
    mx: 'auto',
    objectFit: 'cover',
    borderRadius: '50%',
    border: `1px solid ${devPlanColors.primaryLight}`,
  },
  tableButton: {
    minWidth: 0,
    minHeight: 28,
    px: 1,
    color: devPlanColors.primary,
    borderColor: devPlanColors.primaryLight,
    bgcolor: '#fff',
    '&:hover': { bgcolor: devPlanColors.primaryLight, borderColor: devPlanColors.primary },
  },
}
