// features/playersDatabase/ui/pages/searchPage/sx/searchFilters.sx.js

import { devPlanColors } from '../../../../../../ui/core/theme/Colors.js'

export const searchFiltersSx = {
  panel: {
    minWidth: 0,
    p: 0,
    display: 'grid',
    gridTemplateRows: 'auto',
    overflow: 'hidden',
    borderRadius: 8,
    border: '1px solid #dbe5f4',
    boxShadow: '0 8px 22px rgba(11, 31, 77, 0.05)',
  },
  panelHeader: {
    minHeight: 60,
    px: 1.4,
    py: 0.75,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1.2,
    borderBottom: '1px solid #dbe5f4',
  },
  headerMain: {
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    gap: 1.25,
    flex: 1,
  },
  headerCopy: { flex: '0 0 auto', display: 'grid', gap: 0.1 },
  panelTitle: { color: devPlanColors.primaryDark, fontWeight: 700 },
  panelSubtitle: { color: devPlanColors.secondary },
  collapsedSummary: {
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 0.45,
    overflow: 'hidden',
  },
  summaryChip: { maxWidth: 170, bgcolor: devPlanColors.primaryLight, color: devPlanColors.primary },
  moreChip: { color: devPlanColors.primary, borderColor: '#c9d8e6' },
  headerActions: { flex: '0 0 auto', alignItems: 'center', gap: 0.5 },
  resetButton: { color: devPlanColors.primary, whiteSpace: 'nowrap' },
  toggleButton: {
    minHeight: 32,
    color: devPlanColors.primary,
    borderColor: '#c9d8e6',
    whiteSpace: 'nowrap',
    '&:hover': { bgcolor: devPlanColors.primaryLight, borderColor: devPlanColors.primary },
  },
  panelContent: {
    minWidth: 0,
    maxHeight: { xs: 420, xl: 300 },
    overflowX: 'auto',
    overflowY: 'auto',
    p: 1.15,
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      md: 'minmax(280px, 0.9fr) minmax(360px, 1.15fr)',
      xl: 'minmax(300px, 0.85fr) minmax(430px, 1.2fr) minmax(360px, 1fr)',
    },
    gap: 1.1,
    alignItems: 'start',
  },
  contextArea: { minWidth: 0 },
  profileArea: { minWidth: 0 },
  statsArea: { minWidth: 0, gridColumn: { xs: 'auto', md: '1 / -1', xl: 'auto' } },
  section: {
    minWidth: 0,
    display: 'grid',
    gap: 0.85,
    p: 1,
    border: '1px solid #edf1f5',
    borderRadius: 7,
    bgcolor: '#fbfcfe',
  },
  sectionHeader: { display: 'grid', gap: 0.15 },
  sectionTitle: { color: devPlanColors.primaryDark, fontWeight: 700 },
  sectionDescription: { color: devPlanColors.secondary },
  chipGroup: { flexWrap: 'wrap', gap: 0.5 },
  filterChip: {
    cursor: 'pointer',
    '&[data-variant="solid"]': { bgcolor: devPlanColors.primary },
  },
  profileGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))' },
    gap: 0.6,
    mt: 0.7,
  },
  profileCard: {
    minWidth: 0,
    p: 0.75,
    border: '1px solid #dbe5f4',
    borderRadius: 7,
    cursor: 'pointer',
    transition: '120ms ease',
  },
  profileCardSelected: { borderColor: devPlanColors.primary, bgcolor: devPlanColors.primaryLight },
  profileTitle: { color: devPlanColors.primaryDark, fontSize: 13 },
  profileDescription: { color: devPlanColors.secondary, lineHeight: 1.3 },
  conditionsList: { display: 'grid', gap: 0.6 },
  conditionRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(105px, 1fr) minmax(105px, 1fr) 72px 30px',
    gap: 0.45,
    alignItems: 'center',
  },
  removeConditionButton: { minWidth: 28, minHeight: 28, color: '#9c2d2d' },
  addConditionButton: { justifySelf: 'start', color: devPlanColors.primary, borderColor: devPlanColors.primaryLight },
}
