import {
  Adjust,
  BarChart,
  ControlPoint,
  EmojiEvents,
  ElectricBolt,
  FitnessCenter,
  Insights,
  Psychology,
  Security,
  Whatshot,
  Percent,
  DragIndicator,
  TrendingUp,
  LightMode,
  Feed,
  HighQuality,
  Speed,
  SportsSoccer,
  CrisisAlert,
  AssignmentInd,
  RemoveCircleOutline
} from '@mui/icons-material';

export const performanceIcons = {
  abilities: <FitnessCenter />,
  defensive: <Security />,
  defensive_key: <Security />,
  fitness: <FitnessCenter />,
  general: <BarChart />,
  hard: <Whatshot />,
  mental: <Psychology />,
  offensive: <ElectricBolt />,
  offensive_key: <ElectricBolt />,
  pro: <Insights />,
  rate: <Percent />,
  points: <DragIndicator />,
  trend: <TrendingUp />,
  topParm: <LightMode />,
  feed: <Feed />,
  performance: <HighQuality />,
  performanceModel: <CrisisAlert />,
  performanceProfile: <AssignmentInd />,
  scoringRating: <Speed />,
  scoringImpact: <TrendingUp />,
  scorer: <SportsSoccer />,
  doubleDigitScorer: <EmojiEvents />,
  complementaryScorer: <ControlPoint />,
  occasionalScorer: <Adjust />,
  noGoalTarget: <RemoveCircleOutline />,
};
