// preview/PreviewDomainCard/domains/team/videos/teamVideos.sx.js
export const domainBoxSx = {
  sx: {
    px: 1,
    py: 0.9,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
    bgcolor: 'background.level1',
    borderBottom: '1px solid',
    borderColor: 'divider',
    boxShadow: 'sm',
    borderRadius: 'sm',
  },
  left: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.75,
    minWidth: 0,
  },
  title: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  right: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.75,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
}

export const modalSx = {
  root: { minWidth: 0 },
  kpiStrip: {
    p: 1,
    borderRadius: 'md',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
    flexWrap: 'wrap',
  },
  filters: {
    p: 1,
    borderRadius: 'md',
    display: 'grid',
    gap: 1,
    gridTemplateColumns: { xs: '1fr', sm: '2fr 1fr', md: '2fr 1fr 1fr 1fr' },
    alignItems: 'center',
  },
  clips: {
    p: 1,
    borderRadius: 'md',
    overflow: 'auto',
    display: 'grid',
    gap: 0.75,
  },
  clipRow: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '2fr 1fr 1fr' },
    gap: 1,
    alignItems: 'center',
    py: 0.75,
    px: 0.75,
    borderRadius: 'sm',
    border: '1px solid',
    borderColor: 'divider',
    bgcolor: 'background.level1',
  },
  clipMain: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.75,
    minWidth: 0,
  },
  clipTitle: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  clipMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.5,
    flexWrap: 'wrap',
    justifyContent: { xs: 'flex-start', md: 'flex-end' },
  },
  tagsWrap: {
    display: 'flex',
    gap: 0.5,
    flexWrap: 'wrap',
    minWidth: 0,
  },
}
