import { devPlanColors } from '../../../../../../ui/core/theme/Colors.js'

export const teamPositionClassificationTableSx = {
  section: {
    p: { xs: 1.25, md: 1.5 },
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 10,
    bgcolor: devPlanColors.surface,
    minWidth: 0,
  },
  sectionEmbedded: {
    p: 0,
    border: 0,
    borderRadius: 0,
    bgcolor: 'transparent',
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 1,
    mb: 1,
  },
  title: { color: devPlanColors.primaryDark, fontSize: 15, fontWeight: 800 },
  meta: { color: devPlanColors.secondary, fontSize: 11, mt: 0.25 },
  actions: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1.25,
    flexShrink: 0,
  },
  filterControl: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0.5,
  },
  filterLabel: { color: devPlanColors.secondary, fontSize: 10.5, fontWeight: 700, whiteSpace: 'nowrap' },
  exportButton: { borderColor: devPlanColors.border, color: devPlanColors.primary },
  tableWrap: {
    mt: 0.75,
    maxHeight: 'min(52vh, 520px)',
    overflowX: 'hidden',
    overflowY: 'auto',
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 8,
  },
  table: {
    width: '100%',
    tableLayout: 'fixed',
    '--TableCell-paddingX': '10px',
    '--TableCell-paddingY': '8px',
    '& th': {
      position: 'sticky',
      top: 0,
      zIndex: 1,
      color: devPlanColors.primaryDark,
      bgcolor: devPlanColors.secondaryLight,
      fontSize: 11,
      fontWeight: 800,
      whiteSpace: 'normal',
      textAlign: 'center',
    },
    '& td': {
      color: devPlanColors.secondary,
      fontSize: 12,
      textAlign: 'center',
      verticalAlign: 'middle',
      whiteSpace: 'normal',
      overflowWrap: 'anywhere',
    },
  },
  indexColumn: { width: '5%', whiteSpace: 'nowrap' },
  avatarColumn: { width: '3%', textAlign: 'center' },
  playerColumn: { width: '12%' },
  gamesStartsColumn: { width: '12%' },
  minutesColumn: { width: '10%' },
  minutesBandColumn: { width: '10%' },
  substitutionsColumn: { width: '10%' },
  substitutionBandColumn: { width: '11%' },
  goalsColumn: { width: '7%' },
  lineClassificationColumn: { width: '15%' },
  openPlayerColumn: { width: '5%', textAlign: 'center' },
  openPlayerButton: { borderColor: devPlanColors.border, color: devPlanColors.primary },
  avatar: {
    width: 28,
    height: 28,
    display: 'block',
    mx: 'auto',
    objectFit: 'cover',
    borderRadius: '50%',
    border: `1px solid ${devPlanColors.primaryLight}`,
  },
  classificationEdit: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 30,
    p: 0,
    border: 0,
    bgcolor: 'transparent',
    cursor: 'pointer',
    borderRadius: 8,
    transition: 'transform 140ms ease',
    '& .MuiChip-root': {
      bgcolor: devPlanColors.tertiaryLight,
      border: `1px solid ${devPlanColors.tertiary}`,
    },
    '&:hover': {
      transform: 'translateY(-1px)',
      '& .MuiChip-root': {
        bgcolor: devPlanColors.primaryLight,
        borderColor: devPlanColors.tertiaryDark,
      },
    },
    '&:active': {
      transform: 'translateY(0)',
    },
    '&:focus-visible': {
      outline: `2px solid ${devPlanColors.primaryLight}`,
      outlineOffset: 2,
    },
    '&:disabled': {
      cursor: 'default',
      opacity: 0.65,
    },
  },
  player: { color: devPlanColors.primaryDark, fontSize: 12, fontWeight: 700 },
  playerNameContent: {
    minWidth: 0,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.55,
  },
  playerStatusBadge: color => ({
    width: 20,
    height: 20,
    minWidth: 20,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    color: `var(--joy-palette-${color}-700)`,
    bgcolor: `var(--joy-palette-${color}-100)`,
    border: `1px solid var(--joy-palette-${color}-300)`,
    lineHeight: 1,
    '& svg': { fontSize: 13 },
  }),
  index: { color: devPlanColors.secondary, fontSize: 12, fontWeight: 700 },
  minutesBand: { color: devPlanColors.primaryDark, fontSize: 12, fontWeight: 700, cursor: 'help' },
  substitutionBand: { color: devPlanColors.primaryDark, fontSize: 12, fontWeight: 700, cursor: 'help' },
}
