import { COLORS, devPlanColors } from '../../../../../../ui/core/theme/Colors.js'

export const teamStructureSx = {
  section: {
    p: { xs: 1.25, md: 1.5 },
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 10,
    bgcolor: devPlanColors.surface,
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 1,
    mb: 1.2,
  },
  title: { color: devPlanColors.primaryDark, fontSize: 15, fontWeight: 800 },
  conclusion: { color: devPlanColors.primary, fontSize: 17, lineHeight: 1.35, fontWeight: 800, mt: 0.3 },
  info: { color: devPlanColors.secondary, display: 'inline-flex', cursor: 'help', mt: 0.25 },
  factsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gap: 1,
  },
  interestGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 1,
    mb: 0.8,
    width: '100%',
    minWidth: 0,
  },
  defenseInterestArea: { minWidth: 0 },
  attackInterestArea: { minWidth: 0 },
  squadInterestArea: { minWidth: 0 },
  interestCard: {
    width: '100%',
    maxWidth: '100%',
    boxSizing: 'border-box',
    minWidth: 0,
    minInlineSize: 0,
    minHeight: 65,
    p: 0.8,
    borderRadius: 8,
    bgcolor: devPlanColors.secondaryLight,
    display: 'flex',
    alignItems: 'center',
    gap: 0.7,
  },
  interestCardActive: {
    bgcolor: COLORS.status.success.softBg,
  },
  interestCardClickable: {
    border: 0,
    font: 'inherit',
    textAlign: 'inherit',
    cursor: 'pointer',
    '&:hover': { boxShadow: `inset 0 0 0 1px ${devPlanColors.primary}` },
  },
  interestCardIcon: {
    display: 'inline-flex',
    flexShrink: 0,
    alignSelf: 'flex-start',
    color: devPlanColors.secondary,
  },
  interestCardContent: { display: 'grid', gap: 0.05, minWidth: 0, overflow: 'hidden', flex: 1 },
  interestCardLabel: { color: devPlanColors.secondary, fontSize: 10.5, fontWeight: 700 },
  interestCardStatus: { color: devPlanColors.primaryDark, fontSize: 15, fontWeight: 800, lineHeight: 1.15, overflowWrap: 'anywhere' },
  interestCardStatusActive: { color: COLORS.status.success.text },
  interestCardReason: { color: devPlanColors.secondary, fontSize: 10, lineHeight: 1.25 },
  lineCount: {
    p: 0.85,
    borderRadius: 8,
    bgcolor: devPlanColors.secondaryLight,
    display: 'grid',
    gap: 0.12,
    minWidth: 0,
  },
  lineCountClickable: {
    border: 0,
    font: 'inherit',
    textAlign: 'inherit',
    cursor: 'pointer',
    '&:hover': { boxShadow: `inset 0 0 0 1px ${devPlanColors.primary}` },
  },
  lineCountSelected: {
    boxShadow: `inset 0 0 0 2px ${devPlanColors.primary}`,
  },
  lineCountCompact: {
    p: 0.55,
    gap: 0.05,
  },
  lineCountValue: { color: devPlanColors.primaryDark, fontSize: 19, lineHeight: 1.15, fontWeight: 800 },
  lineCountValueCompact: { fontSize: 16 },
  lineCountValueRow: { display: 'flex', flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 0.35, minWidth: 0 },
  lineCountRate: { color: devPlanColors.secondary, fontSize: 9.5, fontWeight: 700, whiteSpace: 'nowrap' },
  lineCountFooter: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 0.35, minWidth: 0 },
  lineCountLabels: { display: 'grid', gap: 0.05, minWidth: 0 },
  lineCountLabel: { color: devPlanColors.secondary, fontSize: 11, fontWeight: 700, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  lineCountLabelCompact: { fontSize: 9.5 },
  lineCountAboveReference: { bgcolor: COLORS.status.success.softBg },
  lineCountBelowReference: { bgcolor: COLORS.status.danger.softBg },
  lineCountValueAboveReference: { color: COLORS.status.success.text },
  lineCountValueBelowReference: { color: COLORS.status.danger.text },
  referenceChip: { color: devPlanColors.secondary, display: 'inline-flex', alignItems: 'center', gap: 0.35, px: 0.42, py: 0.35, border: `1px solid ${devPlanColors.border}`, borderRadius: 99, bgcolor: devPlanColors.surface, fontSize: 10, fontWeight: 800, lineHeight: 1.1, whiteSpace: 'nowrap' },
  referenceChipAbove: { color: COLORS.status.success.text, bgcolor: COLORS.status.success.softBg, borderColor: '#BBF7D0' },
  referenceChipBelow: { color: COLORS.status.danger.text, bgcolor: COLORS.status.danger.softBg, borderColor: '#FECACA' },
  referenceChipIcon: { display: 'inline-flex', '& svg': { fontSize: 10 } },
  referenceChipValue: { color: devPlanColors.secondary, fontSize: 10, lineHeight: 1.1, fontWeight: 800 },
  lineCountIcon: { display: 'inline-flex', flexShrink: 0, color: devPlanColors.secondary },
  coverageRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 1 },
  coverageContent: { display: 'grid', gap: 0.12 },
  coverage: { color: devPlanColors.secondary, fontSize: 11.5, lineHeight: 1.45 },
  interest: { color: devPlanColors.primary, fontSize: 11.5, fontWeight: 800, lineHeight: 1.45 },
  detailsTrigger: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.3,
    flexShrink: 0,
    color: devPlanColors.secondary,
    cursor: 'help',
  },
  detailsLabel: { color: devPlanColors.secondary, fontSize: 10.5, fontWeight: 700 },
  detailsTooltip: { maxWidth: 310, minWidth: 240, textAlign: 'right', p: 1 },
  tableContent: {
    mt: 1.25,
    pt: 1.25,
    borderTop: `1px solid ${devPlanColors.border}`,
  },
  tooltipContent: { display: 'grid', gap: 0.5 },
  tooltipTitle: { color: devPlanColors.primaryDark, fontSize: 13, fontWeight: 800 },
  tooltipLabel: { color: devPlanColors.primary, fontSize: 10.5, fontWeight: 800, mt: 0.25 },
  tooltipText: { color: devPlanColors.secondary, fontSize: 11, lineHeight: 1.45 },
}
