import { devPlanColors, getEntityColors } from '../../../../../../ui/core/theme/Colors.js'

const scoutingColors = getEntityColors('scouting')

export const teamInformationSx = {
  content: {
    minWidth: 0,
    minHeight: 0,
    overflowY: 'auto',
    overflowX: 'hidden',
    pr: 0.25,
    display: 'grid',
    alignContent: 'start',
    gap: 1.25,
  },
  section: {
    p: { xs: 1.25, md: 1.5 },
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 10,
    bgcolor: devPlanColors.surface,
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
    mb: 1.15,
  },
  sectionTitle: {
    color: devPlanColors.primaryDark,
    fontSize: 15,
    fontWeight: 800,
  },
  sectionMeta: {
    color: devPlanColors.secondary,
    fontSize: 11,
  },
  kpiGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))', lg: 'repeat(4, minmax(0, 1fr))' },
    gap: 1,
  },
  kpi: {
    p: 1,
    borderRadius: 9,
    border: `1px solid ${devPlanColors.border}`,
    display: 'grid',
    alignContent: 'start',
    gap: 0.45,
    minHeight: 90,
  },
  kpiHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.55,
    minWidth: 0,
  },
  kpiIcon: {
    width: 25,
    height: 25,
    flexShrink: 0,
    display: 'grid',
    placeItems: 'center',
    borderRadius: 7,
    bgcolor: devPlanColors.primaryLight,
    color: devPlanColors.primary,
  },
  kpiStatusRow: { display: 'flex', alignItems: 'center', gap: 0.5, minHeight: 24 },
  kpiValue: { color: devPlanColors.primaryDark, fontSize: 23, lineHeight: 1.15, fontWeight: 700 },
  kpiLabel: { color: devPlanColors.primary, fontSize: 13, lineHeight: 1.3, fontWeight: 700, whiteSpace: 'nowrap' },
  kpiMeaningRow: { display: 'flex', alignItems: 'flex-start', gap: 0.4, minWidth: 0 },
  kpiMeta: { flex: 1, color: devPlanColors.secondary, fontSize: 11.5, lineHeight: 1.4, fontWeight: 400 },
  kpiInfo: {
    display: 'inline-flex',
    flexShrink: 0,
    color: devPlanColors.secondary,
    cursor: 'help',
    mt: '1px',
  },
  kpiTooltip: {
    maxWidth: 228,
    minWidth: 190,
    whiteSpace: 'normal',
    overflowWrap: 'anywhere',
    textAlign: 'right',
    lineHeight: 1.45,
    p: 1,
  },
  // Prepared UI treatment only; it is not connected to a condition or data source.
  kpiOpportunity: {},
  kpiOpportunityMarker: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.3,
    px: 0.5,
    py: 0.2,
    borderRadius: 'sm',
    bgcolor: scoutingColors.bg,
    color: scoutingColors.accent,
  },
  kpiOpportunityLabel: { color: scoutingColors.accent, fontSize: 10, fontWeight: 800 },  usageGrid: {
    mt: 1.25,
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(4, minmax(0, 1fr))' },
    borderTop: `1px solid ${devPlanColors.border}`,
    borderInlineStart: `1px solid ${devPlanColors.border}`,
  },
  usageCell: {
    minHeight: 70,
    p: 0.9,
    display: 'grid',
    alignContent: 'center',
    gap: 0.25,
    borderInlineEnd: `1px solid ${devPlanColors.border}`,
    borderBottom: `1px solid ${devPlanColors.border}`,
  },
  usageValue: { color: devPlanColors.primaryDark, fontSize: 18, fontWeight: 800 },
  usageLabel: { color: devPlanColors.secondary, fontSize: 10 },
  reliability: {
    mt: 1,
    display: 'flex',
    alignItems: 'center',
    gap: 0.65,
    color: devPlanColors.secondary,
    fontSize: 11,
  },
  twoColumn: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', lg: 'repeat(2, minmax(0, 1fr))' },
    gap: 1.25,
  },
  metricRow: {
    display: 'grid',
    gridTemplateColumns: '1fr auto',
    alignItems: 'center',
    gap: 1,
    py: 0.8,
    borderBottom: `1px solid ${devPlanColors.border}`,
    '&:last-of-type': { borderBottom: 0 },
  },
  metricLabel: { color: devPlanColors.secondary, fontSize: 11 },
  metricValue: { color: devPlanColors.primaryDark, fontSize: 13, fontWeight: 800 },
  empty: { p: 2, textAlign: 'center', color: devPlanColors.secondary, fontSize: 12 },
}



