import assert from 'node:assert/strict'; import test from 'node:test'; import vm from 'node:vm'; import fs from 'node:fs/promises'; import path from 'node:path'; import { fileURLToPath } from 'node:url'
const file=path.join(path.dirname(fileURLToPath(import.meta.url)),'useTeamPageUrlEditor.js'); let context
const synthetic=(name,exports)=>new vm.SyntheticModule(Object.keys(exports),function(){Object.entries(exports).forEach(([k,v])=>this.setExport(k,v))},{identifier:name,context})
async function load(calls=[]){const slots=[];let cursor=0;context=vm.createContext({console});const m=new vm.SourceTextModule(await fs.readFile(file,'utf8'),{context,identifier:file});await m.link(async s=>{if(s==='react')return synthetic('react',{useState:i=>{const x=cursor++;if(!(x in slots))slots[x]=i;return[slots[x],v=>slots[x]=typeof v==='function'?v(slots[x]):v]},useCallback:f=>f});if(s.includes('updateSeasonUrl'))return synthetic('write',{updateTeamSeasonUrl:async x=>{calls.push({...x});if(x.seasonKey==='24/25')throw new Error('fail')}});if(s.includes('teamPageSeason.model'))return synthetic('model',{findTeamPageTableRow:({season,teamId})=>(season.tableRank||[]).find(r=>(r.birthTeamId||r.teamId)===teamId)||null});throw Error(s)});await m.evaluate();return{ns:m.namespace,render:p=>{cursor=0;return m.namespace.default(p)},slots}}
const leagues=[{id:'l1',name:'L1',current:{seasonKey:'26/27',ageGroupId:'u15',tableRank:[{birthTeamId:'t1',teamUrl:'https://a'}]},history:[{seasonKey:'25/26',tableRank:[{birthTeamId:'t1',teamUrl:'https://b'}]},{seasonKey:'24/25',tableRank:[]}]}]
test('team rows include only real League rows with independent URLs',async()=>{const {ns}=await load();const rows=ns.buildTeamUrlRows({leagueDocuments:leagues,teamId:'t1'});assert.equal(rows.length,2);assert.equal(JSON.stringify(rows.map(r=>r.originalUrl)),JSON.stringify(['https://a','https://b']))})
test('one dirty row writes once and reloads once',async()=>{const calls=[];let reloads=0;const h=await load(calls);const p={leagueDocuments:leagues,team:{birthTeamId:'t1',domain:{identity:{birthTeamDocumentId:'team-document-id'}}},reload:async()=>reloads++};h.render(p).openDrawer();let x=h.render(p);x.change(x.rows[0].key,'https://new');await h.render(p).save();assert.equal(calls.length,1);assert.equal(calls[0].birthTeamDocumentId,'team-document-id');assert.equal(reloads,1)})
test('two dirty rows write in order and partial failure keeps failed dirty',async()=>{const calls=[];let reloads=0;const h=await load(calls);const custom=[{id:'l1',current:{seasonKey:'25/26',tableRank:[{birthTeamId:'t1',teamUrl:'a'}]},history:[{seasonKey:'24/25',tableRank:[{birthTeamId:'t1',teamUrl:'b'}]}]}];const p={leagueDocuments:custom,team:{birthTeamId:'t1',domain:{identity:{birthTeamDocumentId:'team-document-id'}}},reload:async()=>reloads++};h.render(p).openDrawer();let x=h.render(p);x.rows.forEach((r,i)=>x.change(r.key,`https://new${i}`));await h.render(p).save();x=h.render(p);assert.equal(JSON.stringify(calls.map(c=>c.seasonKey)),JSON.stringify(['25/26','24/25']));assert.equal(reloads,1);assert.equal(x.rows[0].saved,true);assert.equal(x.rows[1].saved,false);assert.ok(x.rows[1].error);assert.notEqual(x.rows[1].draftUrl,x.rows[1].originalUrl)})

test('reload failure does not lock team editor or undo saved row',async()=>{const calls=[];const h=await load(calls);const p={leagueDocuments:leagues,team:{birthTeamId:'t1',domain:{identity:{birthTeamDocumentId:'team-document-id'}}},reload:async()=>{throw new Error('reload failed')}};h.render(p).openDrawer();let x=h.render(p);x.change(x.rows[0].key,'https://new');await h.render(p).save();x=h.render(p);assert.equal(x.saving,false);assert.equal(x.rows[0].saved,true);assert.equal(x.rows[0].originalUrl,'https://new')})
