export const playersDatabaseKpis = [
  {
    id: 'players',
    label: 'שחקנים במאגר',
    value: '2,014',
    note: 'טעינה בעמודים, ללא listener גלובלי',
  },
  {
    id: 'snapshots',
    label: 'צילומי ביצועים',
    value: '5,842',
    note: 'תחילת עונה, אמצע עונה, סוף עונה',
  },
  {
    id: 'positiveTrend',
    label: 'מגמה חיובית',
    value: '312',
    note: 'מחושב בזמן ייבוא ועדכון',
  },
  {
    id: 'tracked',
    label: 'במעקב פעיל',
    value: '86',
    note: 'שכבת scouting מעל המאגר',
  },
]

export const playersDatabaseRows = [
  {
    id: 'pdb-92841',
    externalPlayerId: 'EXT-92841',
    fullName: 'נועם לוי',
    birthYear: 2010,
    clubName: 'מכבי חיפה',
    teamName: 'נערים ג׳ צפון',
    leagueName: 'על מחוזית',
    minutes: 1420,
    goals: 18,
    playingUpMinutes: 310,
    trendStatus: 'positive',
    trendLabel: 'חיובית',
    trackingStatus: 'active',
    trackingLabel: 'פעיל',
    latestSnapshotAt: '15.06.26',
  },
  {
    id: 'pdb-77104',
    externalPlayerId: 'EXT-77104',
    fullName: 'אדם כהן',
    birthYear: 2009,
    clubName: 'הפועל רעננה',
    teamName: 'נערים ב׳',
    leagueName: 'ארצית',
    minutes: 980,
    goals: 7,
    playingUpMinutes: 0,
    trendStatus: 'stable',
    trendLabel: 'יציבה',
    trackingStatus: 'on_hold',
    trackingLabel: 'בהמתנה',
    latestSnapshotAt: '11.06.26',
  },
  {
    id: 'pdb-55120',
    externalPlayerId: 'EXT-55120',
    fullName: 'יהונתן מזרחי',
    birthYear: 2011,
    clubName: 'בית״ר טוברוק',
    teamName: 'ילדים א׳',
    leagueName: 'מרכז 1',
    minutes: 740,
    goals: 14,
    playingUpMinutes: 120,
    trendStatus: 'positive',
    trendLabel: 'חיובית',
    trackingStatus: 'none',
    trackingLabel: 'לא במעקב',
    latestSnapshotAt: '10.06.26',
  },
  {
    id: 'pdb-49102',
    externalPlayerId: 'EXT-49102',
    fullName: 'רועי בן דוד',
    birthYear: 2010,
    clubName: 'הפועל תל אביב',
    teamName: 'נערים ג׳',
    leagueName: 'על',
    minutes: 420,
    goals: 2,
    playingUpMinutes: 0,
    trendStatus: 'decline',
    trendLabel: 'ירידה',
    trackingStatus: 'closed',
    trackingLabel: 'נסגר',
    latestSnapshotAt: '02.06.26',
  },
]

export const playersDatabaseSelectedPlayer = {
  ...playersDatabaseRows[0],
  snapshots: [
    {
      id: 'snap-end',
      checkpoint: 'סוף עונה',
      summary: '1,420 דקות · 18 שערים · 310 דקות בשנתון מעל',
    },
    {
      id: 'snap-mid',
      checkpoint: 'אמצע עונה',
      summary: '680 דקות · 7 שערים · ללא דקות בשנתון מעל',
    },
    {
      id: 'snap-start',
      checkpoint: 'תחילת עונה',
      summary: '210 דקות · 2 שערים',
    },
  ],
}
