// src/shared/liveTagging/actions/liveActionStatsMap.js

export const DEFAULT_LIVE_ACTION_PAIR_IDS = [
  'passes',
  'tackles',
  'shots',
  'personalPressures',
]

export const LIVE_ACTION_STATS_MAP = [
  {
    id: 'passes',
    statsGroup: 'passes',
    label: 'מסירות',
    idIcon: 'passes',
    scope: 'player',
    group: 'passing',
    positiveStatId: 'passesSuccess',
    totalStatId: 'passesTotal',
    rateStatId: 'passesSuccessRate',
    positiveLabel: 'טובה',
    negativeLabel: 'רעה',
    enabledByDefault: true,
  },
  {
    id: 'keyPasses',
    statsGroup: 'keyPasses',
    label: 'מסירת מפתח',
    idIcon: 'keyPasses',
    scope: 'player',
    group: 'passing',
    positiveStatId: 'keyPassesSuccess',
    totalStatId: 'keyPassesTotal',
    rateStatId: 'keyPassesSuccessRate',
    positiveLabel: 'טובה',
    negativeLabel: 'רעה',
  },
  {
    id: 'crosses',
    statsGroup: 'crosses',
    label: 'הגבהה',
    idIcon: 'crossesTotal',
    scope: 'player',
    group: 'passing',
    positiveStatId: 'crossesSuccess',
    totalStatId: 'crossesTotal',
    rateStatId: 'crossesSuccessRate',
    positiveLabel: 'טובה',
    negativeLabel: 'רעה',
  },
  {
    id: 'dribbles',
    statsGroup: 'dribbles',
    label: 'דריבל',
    idIcon: 'dribblesTotal',
    scope: 'player',
    group: 'dribbling',
    positiveStatId: 'dribblesSuccess',
    totalStatId: 'dribblesTotal',
    rateStatId: 'dribblesSuccessRate',
    positiveLabel: 'מוצלח',
    negativeLabel: 'נכשל',
  },
  {
    id: 'shots',
    statsGroup: 'shots',
    label: 'בעיטה',
    idIcon: 'shotsTotal',
    scope: 'player',
    group: 'shooting',
    positiveStatId: 'shotsOnTarget',
    totalStatId: 'shotsTotal',
    rateStatId: 'shotsOnTargetSuccessRate',
    positiveLabel: 'למסגרת',
    negativeLabel: 'לא למסגרת',
    enabledByDefault: true,
  },
  {
    id: 'tackles',
    statsGroup: 'tackles',
    label: 'תיקול',
    idIcon: 'tacklesTotal',
    scope: 'player',
    group: 'defending',
    positiveStatId: 'tacklesSuccess',
    totalStatId: 'tacklesTotal',
    rateStatId: 'tacklesSuccessRate',
    positiveLabel: 'מוצלח',
    negativeLabel: 'נכשל',
    enabledByDefault: true,
  },
  {
    id: 'keyTackles',
    statsGroup: 'keyTackles',
    label: 'תיקול מפתח',
    idIcon: 'keyTacklesTotal',
    scope: 'player',
    group: 'defending',
    positiveStatId: 'keyTacklesSuccess',
    totalStatId: 'keyTacklesTotal',
    rateStatId: 'keyTacklesSuccessRate',
    positiveLabel: 'מוצלח',
    negativeLabel: 'נכשל',
  },
  {
    id: 'personalPressures',
    statsGroup: 'personalPressures',
    label: 'לחץ אישי',
    idIcon: 'personalPressuresTotal',
    scope: 'player',
    group: 'defending',
    positiveStatId: 'personalPressuresSuccess',
    totalStatId: 'personalPressuresTotal',
    rateStatId: 'personalPressuresSuccessRate',
    positiveLabel: 'מוצלח',
    negativeLabel: 'נשבר',
    enabledByDefault: true,
  },
  {
    id: 'ballClearances',
    statsGroup: 'ballClearances',
    label: 'הרחקת כדור',
    idIcon: 'ballClearancesTotal',
    scope: 'player',
    group: 'defending',
    positiveStatId: 'ballClearancesSuccess',
    totalStatId: 'ballClearancesTotal',
    rateStatId: 'ballClearancesSuccessRate',
    positiveLabel: 'טובה',
    negativeLabel: 'לא טובה',
  },
  {
    id: 'ballLoss',
    statsGroup: null,
    label: 'איבוד כדור',
    idIcon: 'ballLoss',
    scope: 'player',
    group: 'offensive',
    negativeStatId: 'ballLoss',
    positiveLabel: null,
    negativeLabel: 'איבוד',
  },
  {
    id: 'interceptions',
    statsGroup: null,
    label: 'חטיפה',
    idIcon: 'interceptions',
    scope: 'player',
    group: 'defending',
    positiveStatId: 'interceptions',
    positiveLabel: 'חטיפה',
    negativeLabel: null,
  },
  {
    id: 'fouls',
    statsGroup: null,
    label: 'עבירה',
    idIcon: 'foulsCommitted',
    scope: 'player',
    group: 'defending',
    positiveStatId: 'foulsDrawn',
    negativeStatId: 'foulsCommitted',
    positiveLabel: 'סחט',
    negativeLabel: 'ביצע',
  },
]
