// src/features/playersDatabase/catalog/firestoreDocuments/birthTeamSeasonDocument.catalog.js

// Firestore source of truth: one birth-team season document.
// Owns roster, statistics, performance, balance and compact scouting projections
// for exactly one team + season identity.

const TEAM_BALANCE_GENERIC_OBJECT = {
  snapshotFormat: 'team-balance-summary-v2',
  version: '',
  outputContractVersion: '',
  persistenceContractVersion: '',
  dependencyKey: '',
  source: {
    inputHash: '',
  },
  reliability: {
    reliability: 'insufficient',
    rosterCount: 0,
    loadedCount: 0,
    observedLoadedCount: 0,
    missingCount: 0,
    loadedCoverage: 0,
    observedCoverage: 0,
  },
  availability: {
    minutesDistribution: 'unavailable',
    possibleMinutesUsage: 'unavailable',
    productionDistribution: 'unavailable',
    rotationDistribution: 'unavailable',
    rotationStarts: 'unavailable',
    rotationSubstituteIn: 'unavailable',
  },
  benchmarkVersions: {
    minutesDistribution: '',
    productionDistribution: '',
    rotationDistribution: '',
  },
  bands: {
    minutesTop5: null,
    minutesTop10: null,
    minutesTop14: null,
    usage70: null,
    usage50: null,
    usage30: null,
    usage10: null,
    productionTop1: null,
    productionTop3: null,
    rotationStartsTop5: null,
    rotationStartsTop10: null,
    rotationStartsTop14: null,
    rotationSubInTop5: null,
    rotationSubInTop10: null,
    rotationSubInTop14: null,
  },
  updatedAt: null,
}

const TEAM_PLAYER_SCOUT_PROJECTION_GENERIC_OBJECT = {
  primaryScoutProfileId: '',
  primaryScoutProfileStrengthDepthPct: null,
  professionalScoutProfileIds: [],
  preliminaryScoutProfileIds: [],
  scoutEffectiveImmediacyStatus: '',
  scoutPlayerInterestLevel: '',
  scoutEngineVersion: 'scouting-v2',
}

export const BIRTH_TEAM_SEASON_DOCUMENT_OPTIONAL_SCHEMA_PATHS = Object.freeze([])

export const BIRTH_TEAM_SEASONS_DATABASE_GENERIC_OBJECTS_CATALOG = {
  id: '',
  birthTeamId: '',
  birthTeamDocumentId: '',
  seasonId: '',
  seasonKey: '',
  seasonStatus: '',
  ageGroupId: '',
  leagueId: '',
  teamUrl: '',
  birthYear: 0,
  leagueTotalRound: 0,
  leagueLevel: 0,
  expectedLevelDelta: null,
  tableRank: null,
  tableAttackRank: null,
  tableDefenseRank: null,
  goalsForPerGame: 0,
  goalsAgainstPerGame: 0,
  teamAttackPerformance: null,
  teamDefensePerformance: null,
  playersCount: 0,
  scoutProfilesSummary: {
    total: 0,
    profileCounts: {},
  },
  teamPlayers: [
    {
      playerId: '',
      externalPlayerId: '',
      playerDocumentId: '',
      identityKey: '',
      fullName: '',
      normalizedName: '',
      aliases: [],
      playerUrl: '',
      notes: '',
      numShirt: '',
      statsStatus: 'missing',
      rosterStatus: 'regular',
      manualTransferDirection: '',
      isYoungerAgeGroup: false,
      primaryPosition: '',
      positionLayer: '',
      playerStats: {
        games: 0,
        goals: 0,
        yellowCards: 0,
        minutes: 0,
        starts: 0,
        substituteIn: 0,
        substitutedOut: 0,
        teamMinutes: 0,
        teamGames: 0,
        teamRank: null,
        teamGoalsFor: 0,
        teamGoalsAgainst: 0,
        minutesPerGame: 0,
        goalsPer90: 0,
      },
      ...TEAM_PLAYER_SCOUT_PROJECTION_GENERIC_OBJECT,
      updatedAt: null,
    },
  ],
  teamStats: {
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    teamGamePlayed: 0,
  },
  teamBalance: TEAM_BALANCE_GENERIC_OBJECT,
  createdAt: null,
  updatedAt: null,
}
