// src/features/playersDatabase/catalog/firestoreDocuments/searchIndexPlayerSeason.catalog.js

// Firestore source of truth: player-season SearchIndex document.

export const SEARCHINDEX_PLAYER_SEASON_GENERIC_OBJECT = {
  id: '',
  entityType: 'playerSeason',
  entityId: '',

  displayName: '',
  normalizedDisplayName: '',
  aliases: [],
  identityKey: '',
  identityBirthYear: 0,

  playerId: '',
  playerDocumentId: '',
  externalPlayerId: '',
  playerUrl: '',
  notes: '',
  rosterStatus: 'regular',
  isYoungerAgeGroup: false,

  leagueId: '',
  seasonId: '',
  seasonKey: '',
  clubId: '',
  clubLevel: 0,
  clubStrengthLevel: 0,
  birthTeamId: '',
  birthTeamDocumentId: '',
  birthTeamSlot: 1,
  teamId: '',
  teamDocumentId: '',
  teamUrl: '',
  seasonUrl: '',


  ageGroupId: '',
  ageGroupLabel: '',
  birthYear: 0,
  leagueTotalRound: 0,
  leagueLevel: 0,
  expectedLevelDelta: null,
  region: '',

  primaryPosition: '',
  positionLayer: '',
  numShirt: '',
  statsStatus: 'missing',

  teamTableRank: 0,
  teamTableAttackRank: 0,
  teamTableDefenseRank: 0,
  teamGoalsFor: 0,
  teamGoalsAgainst: 0,
  teamGoalsForPerGame: 0,
  teamGamePlayed: 0,

  games: 0,
  goals: 0,
  yellowCards: 0,
  minutes: 0,
  starts: 0,
  substituteIn: 0,
  substitutedOut: 0,
  teamMinutes: 0,
  teamGames: 0,
  minutesPerGame: 0,
  goalsPer90: 0,
  goalsPerGameDuration: 0,

  statsSnapshots: {
    previous: null,
    current: {
      capturedAt: '',
      snapshotKey: '',
      teamGamePlayed: 0,
      games: 0,
      goals: 0,
      minutes: 0,
      starts: 0,
      substituteIn: 0,
      substitutedOut: 0,
    },
  },

  gameMinutes: 0,
  seasonStatus: '',
  normalizationStatus: '',
  normalizationVersion: 0,
  remainingTeamGames: 0,
  teamMinutesPlayed: 0,
  minutesShareRate: 0,
  projectedRemainingMinutes: 0,

  projectedMinutesRaw: 0,
  projectedMinutes: 0,
  projectedGoalsRaw: 0,
  projectedGoals: 0,
  projectedGamesRaw: 0,
  projectedGames: 0,
  projectedStartsRaw: 0,
  projectedStarts: 0,

  primaryScoutProfileId: '',
  primaryScoutProfileStrengthDepthPct: null,
  primaryScoutWarnings: [],
  primaryScoutScore: null,
  primaryScoutInterestLevel: '',
  primaryScoutTeamGateMode: '',
  nearScoutProfileId: '',
  nearScoutProfileDistancePct: null,
  nearScoutProfileTrend: '',
  scoutEffectiveImmediacyStatus: '',
  scoutEngineVersion: 'scouting-v2',

  secondaryScoutProfileId: '',
  secondaryScoutProfileStrengthDepthPct: null,
  secondaryScoutWarnings: [],
  secondaryScoutScore: null,
  scoutProfileIds: [],
  scoutPreliminaryProfileIds: [],
  scoutCombinationIds: [],
  scoutProfileSearchIds: [],

  sourceCollection: 'players',
  sourceDocumentId: '',
  sourceTarget: '',

  updatedAt: null,
};

