import { COLORS, devPlanColors } from '../../../../../../ui/core/theme/Colors.js'

const statusColors = COLORS.status

export const teamYearDevelopmentSx = {
  content: {
    display: 'grid',
    gap: 1.25,
    minWidth: 0,
    minHeight: 0,
    overflowY: 'auto',
    overflowX: 'hidden',
    pr: 0.25,
    alignContent: 'start',
  },
  section: {
    p: { xs: 1, md: 1.15 },
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 10,
    bgcolor: devPlanColors.surface,
    minWidth: 0,
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 1,
    mb: 0.75,
  },
  titleContainer: {
    width: '100%',
    minWidth: 0,
  },
  titleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
    width: '100%',
  },
  titleIdentity: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.65,
    minWidth: 0,
  },
  titleExtra: {
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
  },
  titleIcon: {
    display: 'grid',
    placeItems: 'center',
    width: 23,
    height: 23,
    borderRadius: 7,
    border: `1px solid ${devPlanColors.primaryDark}`,
    bgcolor: devPlanColors.primary,
    color: devPlanColors.surface,
    '& svg': {
      color: `${devPlanColors.surface} !important`,
      fontSize: 14,
    },
  },
  title: {
    color: devPlanColors.primaryDark,
    fontSize: 15,
    fontWeight: 800,
  },
  meta: {
    mt: 0.35,
    color: devPlanColors.secondary,
    fontSize: 11.5,
  },
  hint: {
    color: devPlanColors.secondary,
    fontSize: 10.5,
    whiteSpace: 'nowrap',
  },
  timelineWrap: {
    overflowX: 'auto',
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 9,
  },
  timeline: {
    display: 'grid',
    minWidth: 500,
  },
  metricGroup: {
    display: 'contents',
  },
  cell: {
    minWidth: 0,
    minHeight: 43,
    p: 0.65,
    borderInlineStart: `1px solid ${devPlanColors.border}`,
    borderTop: `1px solid ${devPlanColors.border}`,
    bgcolor: devPlanColors.surface,
  },
  metricHead: {
    borderInlineStart: 0,
    borderTop: 0,
    bgcolor: devPlanColors.secondaryLight,
    minHeight: 30,
    p: 0.25,
  },
  seasonHead: {
    borderTop: 0,
    bgcolor: devPlanColors.secondaryLight,
    minHeight: 30,
    py: 0.25,
  },
  currentSeasonHead: {
    bgcolor: devPlanColors.primaryLight,
  },
  seasonTitle: {
    color: devPlanColors.primaryDark,
    fontSize: 12,
    fontWeight: 900,
  },
  seasonMeta: {
    color: devPlanColors.secondary,
    fontSize: 9.5,
    mt: 0.1,
  },
  metricLabel: {
    borderInlineStart: 0,
    display: 'flex',
    alignItems: 'center',
    gap: 0.55,
    bgcolor: devPlanColors.secondaryLight,
  },
  metricIcon: {
    display: 'inline-flex',
    color: devPlanColors.secondary,
    '& svg': { fontSize: 16 },
  },
  metricText: {
    color: devPlanColors.primaryDark,
    fontSize: 10.5,
    fontWeight: 800,
  },
  valueCell: {
    display: 'flex',
    alignItems: 'center',
  },
  currentValueCell: {
    bgcolor: devPlanColors.primaryLight,
  },
  value: {
    color: devPlanColors.primaryDark,
    fontSize: 17,
    fontWeight: 900,
  },
  leaguePath: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))', lg: 'repeat(4, minmax(0, 1fr))' },
    gap: 1,
  },
  leagueCard: {
    minWidth: 0,
    p: 0.85,
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 9,
    bgcolor: devPlanColors.surface,
    display: 'grid',
    alignContent: 'start',
    gap: 0.35,
  },
  leagueCardCurrent: {
    bgcolor: devPlanColors.primaryLight,
    borderColor: devPlanColors.primary,
  },
  cardSeason: {
    color: devPlanColors.secondary,
    fontSize: 11,
    fontWeight: 800,
  },
  leagueCardHead: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 0.5,
  },
  ageGroup: {
    color: devPlanColors.secondary,
    fontSize: 10,
    fontWeight: 700,
    whiteSpace: 'nowrap',
  },
  splitGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))' },
    gap: 1,
  },
  evolutionGroups: {
    display: 'grid',
    gap: 2,
  },
  evolutionSubCard: {
    display: 'grid',
    gap: 0.8,
    minWidth: 0,
    p: 1,
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 8,
    bgcolor: '#EEF3F6',
  },
  evolutionGroup: {
    display: 'grid',
    gap: 0.65,
    minWidth: 0,
  },
  evolutionGroupHead: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
    flexWrap: 'wrap',
  },
  evolutionGroupTitle: {
    color: devPlanColors.primaryDark,
    fontSize: 13,
    fontWeight: 900,
  },
  evolutionLegend: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.7,
    flexWrap: 'wrap',
  },
  evolutionLegendItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.3,
    color: devPlanColors.secondary,
    '& p': { fontSize: 10, fontWeight: 700 },
  },
  evolutionLegendColor: color => ({
    width: 8,
    height: 8,
    borderRadius: 99,
    flexShrink: 0,
    bgcolor: color,
  }),
  evolutionRows: {
    display: 'grid',
    gap: 0.4,
  },
  evolutionCollapse: {
    overflow: 'hidden',
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 7,
    bgcolor: devPlanColors.primaryLight,
  },
  evolutionCollapseHeader: {
    px: 0.75,
    py: 0.7,
    bgcolor: devPlanColors.primaryLight,
    '&:hover': {
      bgcolor: '#DCE8F0',
    },
  },
  evolutionCollapseContent: {
    borderTop: `1px solid ${devPlanColors.border}`,
  },
  evolutionCollapseBody: {
    display: 'grid',
    gap: 0.55,
    p: 0.75,
  },
  evolutionCollapseSummary: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.15,
    minWidth: 0,
    flexWrap: 'nowrap',
  },
  evolutionCollapseSeason: {
    color: devPlanColors.primaryDark,
    fontSize: 12,
    fontWeight: 900,
    whiteSpace: 'nowrap',
  },
  evolutionCollapseFacts: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.75,
    minWidth: 0,
    flexWrap: 'wrap',
    color: devPlanColors.secondary,
  },
  evolutionSummarySeparator: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flex: '0 0 auto',
    color: '#111827',
    fontSize: 12,
    fontWeight: 900,
    lineHeight: 1,
  },
  evolutionSummaryChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.25,
    minHeight: 22,
    px: 0.4,
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 99,
    bgcolor: devPlanColors.surface,
    color: devPlanColors.primaryDark,
    whiteSpace: 'nowrap',
    '& > svg': {
      flexShrink: 0,
      color: devPlanColors.tertiaryDark,
      fontSize: 14,
    },
    '& > p': {
      color: 'inherit',
      fontSize: 10.5,
      fontWeight: 800,
    },
  },
  evolutionSummaryValue: {
    display: 'grid',
    placeItems: 'center',
    minWidth: 17,
    minHeight: 17,
    px: 0.25,
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 99,
    bgcolor: devPlanColors.secondaryLight,
    color: devPlanColors.primaryDark,
    '& p': {
      color: 'inherit',
      fontSize: 10.5,
      fontWeight: 900,
      lineHeight: 1,
    },
  },
  evolutionLeadingProfile: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.3,
    minWidth: 0,
    color: devPlanColors.primaryDark,
    '& svg': {
      flexShrink: 0,
      color: devPlanColors.tertiaryDark,
      fontSize: 14,
    },
    '& p': {
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
  },
  evolutionCollapseEmptySummary: {
    px: 0.65,
    py: 0.25,
    borderRadius: 5,
    bgcolor: devPlanColors.secondaryLight,
    color: devPlanColors.secondary,
    fontSize: 10.5,
    fontWeight: 700,
    whiteSpace: 'nowrap',
  },
  evolutionRow: {
    display: 'grid',
    gridTemplateColumns: '56px minmax(0, 1fr)',
    gap: 0.8,
    alignItems: 'center',
    minWidth: 0,
    minHeight: 62,
    px: 0.8,
    pt: 0.8,
    pb: 0.5,
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 8,
    bgcolor: devPlanColors.surface,
  },
  evolutionRowCurrent: {
    bgcolor: devPlanColors.primaryLight,
    borderColor: devPlanColors.tertiary,
  },
  evolutionSeason: {
    color: devPlanColors.primaryDark,
    fontSize: 12,
    fontWeight: 900,
    whiteSpace: 'nowrap',
  },
  evolutionRowContent: {
    display: 'grid',
    gap: 0.4,
    minWidth: 0,
    alignContent: 'center',
  },
  stackedBar: {
    display: 'flex',
    height: 14,
    overflow: 'hidden',
    borderRadius: 99,
    bgcolor: devPlanColors.secondaryLight,
  },
  stackedSegment: ({ width, color }) => ({
    width: `${width}%`,
    minWidth: width ? 4 : 0,
    height: '100%',
    bgcolor: color,
    transition: 'width .16s ease',
    cursor: 'help',
    '&:hover': {
      filter: 'brightness(.82)',
    },
  }),
  evolutionTooltip: {
    p: 0.85,
    border: `1px solid ${devPlanColors.primaryDark}`,
    borderRadius: 8,
    bgcolor: devPlanColors.primaryDark,
    color: devPlanColors.surface,
    boxShadow: '0 10px 24px rgba(16, 43, 64, .24)',
  },
  evolutionTooltipContent: {
    display: 'grid',
    gap: 0.25,
    minWidth: 150,
  },
  evolutionTooltipHead: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.45,
    '& p': {
      color: devPlanColors.surface,
      fontSize: 12,
      fontWeight: 900,
    },
  },
  evolutionTooltipColor: color => ({
    width: 9,
    height: 9,
    borderRadius: 99,
    bgcolor: color,
    boxShadow: '0 0 0 2px rgba(255,255,255,.2)',
  }),
  evolutionTooltipValue: {
    color: devPlanColors.surface,
    fontSize: 12,
    fontWeight: 800,
  },
  evolutionTooltipMeta: {
    color: devPlanColors.primaryLight,
    fontSize: 10.5,
  },
  evolutionCounts: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.6,
    flexWrap: 'wrap',
    color: devPlanColors.secondary,
    '& p': { fontSize: 10.5, fontWeight: 700 },
  },
  evolutionTotal: {
    color: devPlanColors.primaryDark,
    fontWeight: 900,
  },
  evolutionProfileRow: {
    gridTemplateColumns: '56px auto minmax(0, 1fr)',
    alignItems: 'start',
    minHeight: 48,
    pt: 0.8,
    pb: 0.2,
  },
  evolutionProfileTotal: {
    px: 0.6,
    py: 0.3,
    borderRadius: 6,
    bgcolor: devPlanColors.tertiaryLight,
    border: `1px solid ${devPlanColors.tertiary}`,
    color: devPlanColors.primaryDark,
    fontSize: 11.5,
    fontWeight: 900,
    whiteSpace: 'nowrap',
  },
  evolutionProfileChips: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.45,
    minWidth: 0,
    flex: 1,
    overflowX: 'auto',
    overflowY: 'hidden',
    flexWrap: 'nowrap',
    alignSelf: 'start',
    pb: 0,
    '& > *': {
      flexShrink: 0,
    },
  },
  evolutionProfileChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.25,
    px: 0.35,
    py: 0.2,
    borderRadius: 7,
    bgcolor: devPlanColors.primaryLight,
    border: `1px solid ${devPlanColors.border}`,
    boxShadow: '0 2px 6px rgba(16, 43, 64, .08)',
    '& > p': {
      minWidth: 18,
      color: devPlanColors.primaryDark,
      fontSize: 11,
      fontWeight: 900,
      textAlign: 'center',
    },
  },
  evolutionProfileTooltip: {
    p: 0.8,
    border: `1px solid ${devPlanColors.tertiaryDark} !important`,
    borderRadius: 8,
    bgcolor: `${devPlanColors.primaryDark} !important`,
    color: `${devPlanColors.surface} !important`,
    boxShadow: '0 10px 24px rgba(16, 43, 64, .24)',
    '--Tooltip-background': `${devPlanColors.primaryDark} !important`,
    '--Tooltip-color': `${devPlanColors.surface} !important`,
    '--Tooltip-arrow-background': `${devPlanColors.primaryDark} !important`,
    '& p': {
      color: `${devPlanColors.surface} !important`,
    },
  },
  evolutionMoreProfiles: {
    color: devPlanColors.secondary,
    fontSize: 10.5,
    fontWeight: 800,
  },
  evolutionEmptyValue: {
    color: devPlanColors.secondary,
    fontSize: 11,
  },
  evolutionMissing: {
    display: 'grid',
    gridTemplateColumns: '56px minmax(0, 1fr)',
    gap: 0.8,
    alignItems: 'center',
    minHeight: 62,
    px: 0.8,
    py: 0.9,
    border: `1px dashed ${devPlanColors.border}`,
    borderRadius: 8,
    color: devPlanColors.secondary,
    '& p': { fontSize: 11 },
    opacity: 0.7,
  },
  profileSeasonBlock: {
    display: 'grid',
    gap: 0.7,
    minWidth: 0,
    px: 0.8,
    py: 0.7,
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 8,
    bgcolor: devPlanColors.surface,
  },
  profileSeasonHead: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 0.75,
  },
  profileDistributionList: {
    display: 'grid',
    gap: 0.45,
  },
  profileDistributionRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(110px, .9fr) minmax(80px, 1.4fr) 24px',
    alignItems: 'center',
    gap: 0.65,
    minWidth: 0,
  },
  profileDistributionLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.4,
    minWidth: 0,
    color: devPlanColors.primaryDark,
    '& svg': {
      flexShrink: 0,
      color: devPlanColors.tertiaryDark,
      fontSize: 14,
    },
    '& p': {
      overflow: 'hidden',
      fontSize: 11,
      fontWeight: 800,
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
  },
  profileDistributionTrack: {
    height: 8,
    overflow: 'hidden',
    borderRadius: 99,
    bgcolor: devPlanColors.primaryLight,
  },
  profileDistributionFill: width => ({
    width: `${width}%`,
    minWidth: width ? 4 : 0,
    height: '100%',
    borderRadius: 99,
    bgcolor: devPlanColors.tertiary,
  }),
  profileDistributionCount: {
    color: devPlanColors.primaryDark,
    fontSize: 12,
    fontWeight: 900,
    textAlign: 'center',
  },
  summaryCard: {
    minWidth: 0,
    p: 1.15,
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 9,
    bgcolor: devPlanColors.surface,
  },
  summaryTitle: {
    color: devPlanColors.primaryDark,
    fontSize: 12.5,
    fontWeight: 900,
    mb: 1,
  },
  barList: {
    display: 'grid',
    gap: 0.75,
  },
  barRow: {
    display: 'grid',
    gridTemplateColumns: '48px minmax(0, 1fr) 28px',
    gap: 0.65,
    alignItems: 'center',
  },
  barLabel: {
    color: devPlanColors.secondary,
    fontSize: 10.5,
    fontWeight: 800,
  },
  barTrack: {
    height: 8,
    borderRadius: 99,
    overflow: 'hidden',
    bgcolor: devPlanColors.secondaryLight,
  },
  barFill: width => ({
    width: `${width}%`,
    height: '100%',
    borderRadius: 99,
    bgcolor: devPlanColors.tertiary,
  }),
  barValue: {
    color: devPlanColors.primaryDark,
    fontSize: 12,
    fontWeight: 900,
    textAlign: 'end',
  },
  movementList: {
    display: 'grid',
    gap: 0.75,
  },
  movementSeasons: {
    display: 'grid',
    gap: 0.35,
  },
  movementCollapse: {
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 8,
    overflow: 'hidden',
    bgcolor: devPlanColors.primaryLight,
  },
  movementCollapseHeader: {
    px: 1,
    py: 0.55,
    bgcolor: devPlanColors.primaryLight,
    '&:hover': {
      bgcolor: '#DCE8F0',
    },
  },
  movementCollapseBody: {
    p: 0.75,
    borderTop: `1px solid ${devPlanColors.border}`,
  },
  movementHeaderSummary: {
    minWidth: 0,
    display: 'grid',
    alignItems: 'center',
    gridTemplateColumns: 'auto minmax(0, 1fr)',
    gap: 1,
    width: '100%',
  },
  movementHeaderTitle: {
    color: devPlanColors.primaryDark,
    fontSize: 12,
    fontWeight: 900,
    whiteSpace: 'nowrap',
  },
  movementHeaderMeta: {
    color: devPlanColors.secondary,
    fontSize: 11,
    fontWeight: 700,
    whiteSpace: 'nowrap',
  },
  movementHeaderAreas: {
    display: 'grid',
    gridTemplateColumns: 'minmax(130px, .8fr) minmax(130px, 1fr) minmax(130px, 1fr)',
    alignItems: 'stretch',
    minWidth: 0,
    '& > * + *': {
      borderInlineStart: `1px solid ${devPlanColors.border}`,
      ps: 0.85,
    },
  },
  movementHeaderArea: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.7,
    minWidth: 0,
    pe: 0.85,
    overflow: 'hidden',
  },
  movementAreaLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    flexShrink: 0,
    px: 0.55,
    py: 0.25,
    borderRadius: 5,
    border: `1px solid ${devPlanColors.border}`,
    bgcolor: devPlanColors.surface,
    color: devPlanColors.primaryDark,
    fontSize: 10.5,
    fontWeight: 800,
    whiteSpace: 'nowrap',
  },
  movementAreaValues: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.8,
    flexWrap: 'wrap',
  },
  movementMetric: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.6,
    color: devPlanColors.primaryDark,
    '& svg': {
      fontSize: 14,
      color: devPlanColors.tertiaryDark,
    },
    '& p': {
      color: 'inherit',
      fontSize: 11.5,
      fontWeight: 900,
    },
  },
  movementDirectionMetric: color => ({
    color: color === 'success'
      ? statusColors.success.text
      : color === 'warning'
        ? statusColors.warning.text
        : color === 'primary'
          ? devPlanColors.tertiaryDark
          : devPlanColors.secondary,
    '& svg': {
      color: 'inherit',
    },
  }),
  movementEmptyMetric: {
    color: devPlanColors.secondary,
    fontSize: 11,
    fontWeight: 800,
  },
  movementItem: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'minmax(0, 1.2fr) minmax(120px, .8fr) minmax(150px, 1fr)' },
    alignItems: 'center',
    gap: 1,
    p: 0.75,
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 8,
    bgcolor: devPlanColors.surface,
  },
  movementName: {
    color: devPlanColors.primaryDark,
    fontSize: 12,
    fontWeight: 900,
  },
  movementPlayer: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.5,
    minWidth: 0,
  },
  movementAvatar: {
    width: 24,
    height: 24,
    flexShrink: 0,
    fontSize: 10,
    bgcolor: devPlanColors.primaryLight,
  },
  movementMeta: {
    color: devPlanColors.secondary,
    fontSize: 10.5,
    mt: 0.15,
  },
  movementProfile: {
    color: devPlanColors.secondary,
    fontSize: 11,
  },
  movementTag: color => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.35,
    justifySelf: 'start',
    px: 0.65,
    py: 0.3,
    borderRadius: 99,
    border: `1px solid ${color === 'success' ? statusColors.success.solid : color === 'warning' ? statusColors.warning.solid : color === 'primary' ? devPlanColors.tertiary : devPlanColors.border}`,
    bgcolor: color === 'success' ? statusColors.success.softBg : color === 'warning' ? statusColors.warning.softBg : color === 'primary' ? devPlanColors.tertiaryLight : devPlanColors.secondaryLight,
    color: color === 'success' ? statusColors.success.text : color === 'warning' ? statusColors.warning.text : color === 'primary' ? devPlanColors.tertiaryDark : devPlanColors.secondary,
    fontSize: 10.5,
    fontWeight: 800,
    '& svg': { fontSize: 13 },
  }),
  movementTagText: {
    color: 'inherit',
    fontSize: 10.5,
    fontWeight: 800,
    whiteSpace: 'nowrap',
  },
  emptyInline: {
    color: devPlanColors.secondary,
    fontSize: 12,
    py: 1,
  },
  empty: {
    minHeight: 280,
    display: 'grid',
    placeItems: 'center',
    alignContent: 'center',
    gap: 0.75,
    color: devPlanColors.secondary,
  },
  emptyText: {
    color: devPlanColors.secondary,
    fontSize: 13,
  },
}
