import { devPlanColors } from '../../../../../../ui/core/theme/Colors.js'

export const teamStructureSx = {
  section: {
    p: { xs: 1.25, md: 1.5 },
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 10,
    bgcolor: devPlanColors.surface,
    minWidth: 0,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
    mb: 0.75,
  },
  titleRow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.65,
  },
  titleIcon: {
    display: 'grid',
    placeItems: 'center',
    width: 23,
    height: 23,
    borderRadius: 7,
    border: `1px solid ${devPlanColors.primaryDark}`,
    bgcolor: devPlanColors.primary,
    color: devPlanColors.surface,
    '& svg': {
      color: `${devPlanColors.surface} !important`,
      fontSize: 14,
    },
  },
  title: {
    color: devPlanColors.primaryDark,
    fontSize: 15,
    fontWeight: 800,
  },
  meta: {
    color: devPlanColors.secondary,
    fontSize: 11,
    mt: 0.2,
  },
  info: {
    color: devPlanColors.secondary,
    display: 'inline-flex',
    cursor: 'help',
    mt: 0.25,
  },
  headerActions: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.5,
    flexShrink: 0,
  },
  exportButton: {
    minHeight: 28,
    px: 0.8,
    borderColor: devPlanColors.border,
    color: devPlanColors.primaryDark,
    bgcolor: devPlanColors.surface,
    fontSize: 11,
    fontWeight: 700,
  },
  linesGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(2, minmax(0, 1fr))',
      lg: 'repeat(4, minmax(0, 2.25fr)) minmax(0, 3fr)',
    },
    gap: 1,
  },
  lineCard: {
    position: 'relative',
    minWidth: 0,
    overflow: 'hidden',
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr)',
    borderRadius: 9,
    border: `1px solid ${devPlanColors.border}`,
    p: 0,
    textAlign: 'inherit',
    font: 'inherit',
    bgcolor: devPlanColors.surface,
  },
  lineCardReview: {
    bgcolor: devPlanColors.petrolLight,
  },
  lineCardClear: {
    bgcolor: 'rgba(101, 118, 132, 0.16)',
  },
  lineCardClickable: {
    cursor: 'pointer',
    transition: 'transform 160ms ease, box-shadow 160ms ease, border-color 160ms ease',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 7px 16px rgba(23, 59, 87, 0.16)',
    },
    '&:active': {
      transform: 'translateY(0)',
    },
  },
  lineCardSelected: {
    border: `1px solid ${devPlanColors.primary}`,
    borderColor: devPlanColors.primary,
    bgcolor: devPlanColors.primaryLight,
    boxShadow: `0 6px 14px rgba(23, 59, 87, 0.18), inset 0 0 0 1px ${devPlanColors.primary}`,
  },
  lineCardReviewSelected: {
    border: `1px solid ${devPlanColors.petrol}`,
    borderColor: devPlanColors.petrol,
    bgcolor: devPlanColors.petrolLight,
    boxShadow: `0 6px 14px rgba(43, 124, 130, 0.18), inset 0 0 0 1px ${devPlanColors.petrol}`,
  },
  lineBody: {
    minWidth: 0,
    p: 0.75,
    display: 'grid',
    alignContent: 'start',
    gap: 0.25,
  },
  lineHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 0.6,
    minWidth: 0,
  },
  lineHeading: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.5,
    minWidth: 0,
  },
  lineIcon: {
    width: 24,
    height: 24,
    flexShrink: 0,
    display: 'grid',
    placeItems: 'center',
    borderRadius: 7,
    bgcolor: devPlanColors.primaryLight,
    color: devPlanColors.primary,
  },
  lineLabel: {
    color: devPlanColors.primaryDark,
    fontSize: 12,
    fontWeight: 800,
  },
  lineStatus: {
    flexShrink: 0,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.25,
    px: 0.55,
    py: 0.25,
    borderRadius: 99,
    bgcolor: devPlanColors.surface,
    '& svg': { fontSize: 12 },
  },
  lineStatusReview: {
    color: devPlanColors.surface,
    bgcolor: devPlanColors.petrol,
    border: `1px solid ${devPlanColors.petrolDark}`,
    '& svg, & p': { color: `${devPlanColors.surface} !important` },
  },
  lineStatusClear: {
    color: devPlanColors.secondary,
    border: `1px solid ${devPlanColors.border}`,
  },
  lineStatusText: {
    color: 'inherit',
    fontSize: 9.5,
    fontWeight: 900,
    whiteSpace: 'nowrap',
  },
  lineMetricRow: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: 0.6,
    mt: 0.2,
  },
  lineValue: {
    color: devPlanColors.primaryDark,
    fontSize: 30,
    lineHeight: 1,
    fontWeight: 800,
  },
  referenceChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.25,
    px: 0.5,
    py: 0.25,
    mb: 0.1,
    borderRadius: 99,
    border: `1px solid ${devPlanColors.border}`,
    bgcolor: devPlanColors.surface,
    color: devPlanColors.secondary,
  },
  referenceChipIcon: {
    display: 'inline-flex',
    '& svg': { fontSize: 11 },
  },
  referenceChipText: {
    color: 'inherit',
    fontSize: 9.5,
    fontWeight: 800,
    whiteSpace: 'nowrap',
  },
  lineConclusion: {
    color: devPlanColors.secondary,
    fontSize: 10.5,
    lineHeight: 1.4,
    minHeight: 0,
  },
  coverageStrip: {
    minWidth: 0,
    p: 0.75,
    borderRadius: 9,
    border: `1px solid ${devPlanColors.border}`,
    bgcolor: devPlanColors.secondaryLight,
    display: 'grid',
    alignContent: 'start',
    gap: 0.45,
  },
  coverageStripSelected: {
    borderColor: devPlanColors.primary,
    boxShadow: `inset 0 0 0 1px ${devPlanColors.primary}`,
  },
  coverageContent: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 0.65,
    minWidth: 0,
  },
  coverageIcon: {
    width: 27,
    height: 27,
    flexShrink: 0,
    display: 'grid',
    placeItems: 'center',
    borderRadius: 7,
    bgcolor: devPlanColors.primaryLight,
    color: devPlanColors.primary,
  },
  coverageTitle: {
    color: devPlanColors.primaryDark,
    fontSize: 11.5,
    fontWeight: 800,
  },
  coverageText: {
    color: devPlanColors.secondary,
    fontSize: 10.5,
    lineHeight: 1.4,
  },
  coverageAction: {
    border: 0,
    bgcolor: 'transparent',
    color: devPlanColors.primary,
    font: 'inherit',
    fontSize: 10.5,
    fontWeight: 800,
    cursor: 'pointer',
    justifySelf: 'start',
    px: 0.35,
    py: 0.2,
    borderRadius: 6,
    '&:hover': { bgcolor: devPlanColors.primaryLight },
  },
  coverageActionSelected: {
    bgcolor: devPlanColors.primaryLight,
  },
  tableContent: {
    mt: 1.25,
    pt: 1.25,
    borderTop: `1px solid ${devPlanColors.border}`,
  },
  tableIntro: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
    mb: 0.75,
  },
  tableTitleRow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.55,
  },
  tableTitleIcon: {
    display: 'grid',
    placeItems: 'center',
    width: 21,
    height: 21,
    borderRadius: 6,
    border: `1px solid ${devPlanColors.primaryDark}`,
    bgcolor: devPlanColors.primary,
    color: devPlanColors.surface,
    '& svg': {
      color: `${devPlanColors.surface} !important`,
      fontSize: 13,
    },
  },
  tableTitle: {
    color: devPlanColors.primaryDark,
    fontSize: 14,
    fontWeight: 800,
  },
  tableMeta: {
    color: devPlanColors.secondary,
    fontSize: 10.5,
    mt: 0.15,
  },
}
