import { COLORS, devPlanColors } from '../../../../../../ui/core/theme/Colors.js'

const squadRowColors = {
  classified: COLORS.status.success,
  unclassifiedSufficientSample: COLORS.status.warning,
  insufficientSample: COLORS.status.info,
  irrelevant: COLORS.status.neutral,
}

export const teamPositionClassificationTableSx = {
  section: {
    p: { xs: 1.25, md: 1.5 },
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 10,
    bgcolor: devPlanColors.surface,
    minWidth: 0,
  },
  sectionEmbedded: {
    p: 0,
    border: 0,
    borderRadius: 0,
    bgcolor: 'transparent',
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 1,
    mb: 1,
  },
  title: { color: devPlanColors.primaryDark, fontSize: 15, fontWeight: 800 },
  meta: { color: devPlanColors.secondary, fontSize: 11, mt: 0.25 },
  actions: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1.25,
    flexShrink: 0,
  },
  filterControl: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0.5,
  },
  filterLabel: { color: devPlanColors.secondary, fontSize: 10.5, fontWeight: 700, whiteSpace: 'nowrap' },
  exportButton: { borderColor: devPlanColors.border, color: devPlanColors.primary },
  tableWrap: {
    mt: 0.75,
    maxHeight: 'min(52vh, 520px)',
    overflowX: 'hidden',
    overflowY: 'auto',
    border: `1px solid ${devPlanColors.border}`,
    borderRadius: 8,
  },
  table: {
    width: '100%',
    tableLayout: 'fixed',
    '--TableCell-paddingX': '10px',
    '--TableCell-paddingY': '8px',
    '& th': {
      position: 'sticky',
      top: 0,
      zIndex: 1,
      color: devPlanColors.primaryDark,
      bgcolor: devPlanColors.primaryLight,
      fontSize: 11,
      fontWeight: 800,
      whiteSpace: 'normal',
      textAlign: 'center',
    },
    '& td': {
      color: devPlanColors.secondary,
      fontSize: 12,
      textAlign: 'center',
      verticalAlign: 'middle',
      whiteSpace: 'normal',
      overflowWrap: 'anywhere',
    },
  },
  indexColumn: { width: '5%', whiteSpace: 'nowrap' },
  avatarColumn: { width: '3%', textAlign: 'center' },
  playerColumn: { width: '12%' },
  gamesStartsColumn: { width: '9%' },
  minutesColumn: { width: '12%' },
  substitutionsColumn: { width: '12%' },
  goalsColumn: { width: '7%' },
  scoutProfileColumn: { width: '15%' },
  lineClassificationColumn: { width: '15%' },
  openPlayerColumn: { width: '5%', textAlign: 'center' },
  openPlayerButton: { borderColor: devPlanColors.border, color: devPlanColors.primary },
  avatar: {
    width: 28,
    height: 28,
    display: 'block',
    mx: 'auto',
    objectFit: 'cover',
    borderRadius: '50%',
    border: `1px solid ${devPlanColors.primaryLight}`,
  },
  classificationEdit: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 30,
    p: 0,
    border: 0,
    bgcolor: 'transparent',
    cursor: 'pointer',
    borderRadius: 8,
    transition: 'transform 140ms ease',
    '& .MuiChip-root': {
      bgcolor: devPlanColors.tertiaryLight,
      border: `1px solid ${devPlanColors.tertiary}`,
    },
    '&:hover': {
      transform: 'translateY(-1px)',
      '& .MuiChip-root': {
        bgcolor: devPlanColors.primaryLight,
        borderColor: devPlanColors.tertiaryDark,
      },
    },
    '&:active': {
      transform: 'translateY(0)',
    },
    '&:focus-visible': {
      outline: `2px solid ${devPlanColors.primaryLight}`,
      outlineOffset: 2,
    },
    '&:disabled': {
      cursor: 'default',
      opacity: 0.65,
    },
  },
  player: { color: devPlanColors.primaryDark, fontSize: 12, fontWeight: 700 },
  playerNameContent: {
    minWidth: 0,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.55,
  },
  playerStatusBadge: color => ({
    width: 20,
    height: 20,
    minWidth: 20,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    color: `var(--joy-palette-${color}-700)`,
    bgcolor: `var(--joy-palette-${color}-100)`,
    border: `1px solid var(--joy-palette-${color}-300)`,
    lineHeight: 1,
    '& svg': { fontSize: 13 },
  }),
  scoutProfileCell: {
    minWidth: 0,
    display: 'flex',
    justifyContent: 'center',
    '& > span': {
      minWidth: 0,
      maxWidth: '100%',
    },
    '& .MuiTypography-root': {
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
  },
  index: { color: devPlanColors.secondary, fontSize: 12, fontWeight: 700 },
  squadClassificationRow: status => {
    const colors = squadRowColors[status] || squadRowColors.irrelevant

    return {
      '& > td': {
        bgcolor: colors.softBg,
      },
      '&:hover > td': {
        bgcolor: colors.softBg,
      },
    }
  },
  minutesProgress: {
    width: '100%',
    minWidth: 0,
    display: 'grid',
    gap: 0.55,
  },
  minutesValues: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'center',
    gap: 0.4,
    whiteSpace: 'nowrap',
  },
  minutesValue: { color: devPlanColors.primaryDark, fontSize: 12, fontWeight: 800 },
  minutesRate: { color: devPlanColors.secondary, fontSize: 11, fontWeight: 600 },
  minutesProgressTrack: {
    width: 72,
    maxWidth: '100%',
    height: 7,
    mx: 'auto',
    overflow: 'hidden',
    borderRadius: 999,
    bgcolor: '#E6EDF2',
  },
  minutesProgressValue: ({ progress, tone }) => ({
    width: `${progress}%`,
    height: '100%',
    borderRadius: 'inherit',
    bgcolor: ({
      high: '#2F9D67',
      mediumHigh: '#78C99A',
      medium: '#D38A22',
      low: '#D9534F',
      unavailable: '#AAB7C2',
    })[tone] || '#AAB7C2',
    transition: 'width 180ms ease',
  }),
  progressTooltip: {
    border: '1px solid rgba(22, 42, 59, 0.34)',
    fontSize: 11,
    fontWeight: 700,
  },
  substitutionsProgress: {
    width: '100%',
    minWidth: 0,
    display: 'grid',
    gap: 0.55,
  },
  substitutionsValues: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'center',
    gap: 0.4,
    whiteSpace: 'nowrap',
  },
  substitutionsValue: { color: devPlanColors.primaryDark, fontSize: 12, fontWeight: 800 },
  substitutionsRate: { color: devPlanColors.secondary, fontSize: 11, fontWeight: 600 },
  substitutionsProgressTrack: {
    width: 72,
    maxWidth: '100%',
    height: 7,
    mx: 'auto',
    overflow: 'hidden',
    borderRadius: 999,
    bgcolor: '#E6EDF2',
  },
  substitutionsProgressValue: ({ progress, tone }) => ({
    width: `${progress}%`,
    height: '100%',
    borderRadius: 'inherit',
    bgcolor: ({
      high: '#D9534F',
      medium: '#D38A22',
      low: '#2F9D67',
      unavailable: '#AAB7C2',
    })[tone] || '#AAB7C2',
    transition: 'width 180ms ease',
  }),
}
