import {
  ViewTimeline,
  AccessTime,
  Scoreboard,
  ThumbUp,
  ThumbDown,
  Handshake,
  Leaderboard,
  Home,
  SportsSoccer,
  EmojiEvents,
  Recycling,
  DragHandle,
  Outbound,
  Hail,
  EventSeat,
  Adjust
} from '@mui/icons-material';

export const gameIcons = {
  game: <ViewTimeline />,
  games: <ViewTimeline />,
  duration: <AccessTime />,
  results: <Scoreboard />,
  result: <Scoreboard />,
  win: <ThumbUp />,
  loss: <ThumbDown />,
  draw: <Handshake />,
  league: <Leaderboard />,
  home: <Home />,
  away: <Outbound />,
  friendly: <SportsSoccer />,
  cup: <EmojiEvents />,
  easy: <Recycling />,
  equal: <DragHandle />,
  isSquad: <Hail />,
  isNotSquad: <EventSeat />,
  isStart: <Adjust />,
  isNotStart: <EventSeat />,
};
