import {
  AccessTime,
  Adjust,
  BugReport,
  DragHandle,
  DashboardCustomize,
  EmojiEvents,
  EventSeat,
  Hail,
  Handshake,
  Home,
  Leaderboard,
  Outbound,
  Recycling,
  Scoreboard,
  WavingHand,
  ThumbDown,
  ThumbUp,
  ViewTimeline,
  Upcoming
} from '@mui/icons-material';

export const gameIcons = {
  away: <Outbound />,
  cup: <EmojiEvents />,
  draw: <Handshake />,
  duration: <AccessTime />,
  easy: <Recycling />,
  equal: <DragHandle />,
  friendly: <WavingHand />,
  game: <ViewTimeline />,
  games: <ViewTimeline />,
  gameStats: <DashboardCustomize />,
  home: <Home />,
  isNotSquad: <EventSeat />,
  isNotStart: <EventSeat />,
  isSquad: <Hail />,
  isStart: <Adjust />,
  league: <Leaderboard />,
  loss: <ThumbDown />,
  rivel: <BugReport />,
  rival: <BugReport />,
  result: <Scoreboard />,
  results: <Scoreboard />,
  win: <ThumbUp />,
  upcoming: <Upcoming />,
};
