import {
  AppShortcut,
  Accessibility,
  Assignment,
  AssignmentInd,
  Archive,
  AddTask,
  AssignmentLate,
  BugReport,
  Ballot,
  BookmarkAdded,
  Cached,
  DataObject,
  Description,
  DeveloperMode,
  MobileFriendly,
  FollowTheSigns,
  LowPriority,
  PriorityHigh,
  VerticalAlignCenter,
  PendingActions,
  Title,
  Task,
  WifiProtectedSetup,
  OfflinePin,
  Sort,
  Splitscreen,
  SensorOccupied,

} from '@mui/icons-material';

export const tasksIcons = {
  task: <Task />,
  tasks: <Ballot />,
  workspace: <Splitscreen />,
  title: <Title />,
  description: <Description />,
  status: <SensorOccupied />,
  priority: <VerticalAlignCenter />,
  complexity: <VerticalAlignCenter />,
  taskType: <AssignmentInd />,
  parentTaskId: <Assignment />,
  sortOrder: <Sort />,
  dueDate: <AssignmentLate />,
  doneAt: <OfflinePin />,
  newTask: <AddTask />,
  addTask: <AddTask />,
  inProgressTask: <WifiProtectedSetup />,
  waitingTask: <PendingActions />,
  doneTask: <BookmarkAdded />,
  archivedTask: <Archive />,
  priorityLow: <LowPriority />,
  priorityMedium: <VerticalAlignCenter />,
  priorityHigh: <PriorityHigh />,
  complexityLow: <LowPriority />,
  complexityMedium: <VerticalAlignCenter />,
  complexityHigh: <PriorityHigh />,
  followUpTask: <FollowTheSigns />,
  bug: <BugReport />,
  ui: <DeveloperMode />,
  mobile: <MobileFriendly />,
  feature: <Accessibility />,
  refactor: <Cached />,
  data: <DataObject />,
  app: <AppShortcut />,
};
