// 📁 /b_styleObjects/icons/IconIndex.js
import * as React from 'react';
import {
  AddShoppingCart,
  AttachMoney,
  AlarmOn,
  AlarmOff,
  Adjust,
  ArrowUpward,
  ArrowDownward,
  Autorenew,
  Add,
  AddLink,
  Addchart,
  Analytics,
  AddToQueue,
  Assistant,
  AccountBox,
  Badge,
  Badge as BadgeIcon,
  Block,
  BugReport,
  BarChart as BarChartIcon,
  Beenhere,
  CalendarMonth,
  Close,
  Calculate,
  CurrencyExchange,
  CheckBox,
  ContactPhone,
  CancelScheduleSend,
  Comment,
  ContactPage,
  CheckCircle,
  Dashboard,
  Delete,
  Download,
  Done,
  DateRange,
  Dangerous,
  DragHandle,
  Diversity3 as Diversity3Icon,
  DomainAdd,
  DashboardCustomize,
  Event,
  EventAvailable,
  ElectricBolt,
  EventSeat,
  EventBusy,
  EditNote,
  EditCalendar,
  Email,
  ExpandMore,
  ExpandLess,
  EmojiEvents,
  Engineering,
  FilterAlt,
  FitnessCenter,
  Filter3,
  GppBad,
  GroupAdd,
  Groups,
  Home,
  Hail,
  HowToVote,
  Handshake,
  HourglassEmpty,
  HealthAndSafety,
  Info as InfoIcon,
  ImportExport,
  Insights,
  LibraryAdd,
  Link,
  LocalOffer,
  Leaderboard,
  MonetizationOn,
  MoreVert,
  MenuBook,
  ManageAccounts,
  OfflinePin,
  Payment as PaymentIcon,
  Payments,
  PeopleAlt,
  PlaylistAddCircle,
  PermContactCalendar,
  Person,
  PersonAdd as PersonAddIcon,
  Photo,
  Phone,
  PersonSearch,
  Psychology,
  PlayCircle,
  Print,
  PsychologyAlt,
  PublishedWithChanges,
  QueryBuilder,
  QueryStats,
  RestartAlt,
  Refresh,
  Recycling,
  RemoveCircleOutline,
  Save,
  Scoreboard,
  SupervisorAccount,
  SportsHandball,
  SportsSoccer,
  ScheduleSend,
  Share,
  Security,
  Star,
  Sort,
  Sports,
  SyncAlt,
  SyncLock,
  Sms,
  TaskAlt,
  TableView,
  ThumbDown,
  ThumbUp,
  Unpublished,
  Upcoming,
  VideoLibrary as VideoLibraryIcon,
  ViewTimeline,
  VolunteerActivism,
  ViewCompactAlt,
  Whatshot,
  WorkspacePremium
} from '@mui/icons-material';

export const icons = {
  active: <OfflinePin />,
  add: <Add />,
  addLink: <AddLink />,
  age: <PermContactCalendar />,
  analyst: <Dashboard />,
  analysis: <Analytics />,
  assists: <VolunteerActivism />,
  assistant: <Assistant />,
  abilities: <FitnessCenter />,
  actionButton: <MoreVert />,
  administrator: <ManageAccounts />,
  awaitingReply: <HourglassEmpty />,
  approved: <CheckCircle />,
  boolean: <CheckBox />,
  candidate: <PersonSearch />,
  clear: <RestartAlt />,
  close: <Close />,
  clubs: <Home />,
  cup: <EmojiEvents />,
  coach: <Sports />,
  cardList: <ViewCompactAlt />,
  contactPerson: <AccountBox />,
  comments: <Comment />,
  callscheduled: <ScheduleSend />,
  contact: <ContactPage />,
  dashboard: <Dashboard />,
  delete: <Delete />,
  done: <Done />,
  declined: <Dangerous />,
  draw: <Handshake />,
  day: <DateRange />,
  download: <Download />,
  defensive: <Security />,
  edit: <EditNote />,
  easy: <Recycling />,
  equal: <DragHandle />,
  expandMore: <ExpandMore />,
  expandLess: <ExpandLess />,
  email: <Email />,
  filter: <FilterAlt />,
  fitness: <FitnessCenter />,
  friendly: <SportsSoccer />,
  game: <ViewTimeline />,
  games: <ViewTimeline />,
  gameStats: <BarChartIcon />,
  generalParm: <BarChartIcon />,
  goalkeeping: <SportsHandball />,
  goal: <SportsSoccer />,
  goals: <SportsSoccer />,
  home: <Home />,
  hard: <Whatshot />,
  info: <InfoIcon />,
  isInvoice: <PublishedWithChanges />,
  isNotPaid: <CurrencyExchange />,
  isNotProject: <Unpublished />,
  isPaid: <TaskAlt />,
  isSquad: <Hail />,
  isStart: <Adjust />,
  isNotStart: <EventSeat  />,
  isDefault: <HowToVote />,
  incomeTab: <BarChartIcon />,
  interceptions: <HealthAndSafety />,
  link: <Link />,
  loss: <ThumbDown />,
  league: <Leaderboard />,
  level: <Star />,
  keyPasses: <SyncLock />,
  meeting: <Event />,
  meetingCancel: <EventBusy />,
  meetingDone: <EventAvailable />,
  meetings: <CalendarMonth />,
  meetingsPlan: <EditCalendar />,
  meetingReminder: <AlarmOn />,
  meetingOffReminder: <AlarmOff />,
  monthlyPayment: <Autorenew />,
  mental: <Psychology />,
  moreStats: <PlaylistAddCircle />,
  messageSent: <Sms />,
  name: <Badge />,
  number: <Calculate />,
  newClub: <DomainAdd />,
  newMeeting: <LibraryAdd />,
  newPayment: <AddShoppingCart />,
  newPlayer: <PersonAddIcon />,
  newTeam: <GroupAdd />,
  newVideo: <AddToQueue />,
  newGame: <PlaylistAddCircle />,
  newRole: <PersonAddIcon />,
  newGameStats: <DashboardCustomize />,
  newTag: <LocalOffer />,
  newStats: <Addchart />,
  noneType: <GppBad />,
  notActive: <Block />,
  parents: <SupervisorAccount />,
  payment: <Payments />,
  payments: <PaymentIcon />,
  paymentRequst: <VolunteerActivism />,
  photo: <Photo />,
  player: <Person />,
  players: <PeopleAlt />,
  position: <SportsSoccer />,
  price: <AttachMoney />,
  pro: <Insights />,
  project: <Beenhere />,
  playVideo: <PlayCircle />,
  passes: <SyncAlt />,
  proMan: <Diversity3Icon />,
  phone: <Phone />,
  print: <Print />,
  psychologist: <Psychology />,
  performance: <QueryStats />,
  requestsTab: <AttachMoney />,
  reset: <Refresh />,
  roles: <Engineering />,
  results: <Scoreboard />,
  result: <Scoreboard />,
  rivel: <BugReport />,
  remove: <RemoveCircleOutline />,
  reschedule: <CancelScheduleSend />,
  order: <Sort />,
  save: <TaskAlt />,
  saveStandart: <Save />,
  shortName: <BadgeIcon />,
  stats: <BarChartIcon />,
  statsParm: <BarChartIcon />,
  sort: <ImportExport />,
  sortUp: <ArrowUpward />,
  share: <Share />,
  scout: <PersonSearch />,
  scouting: <PersonSearch />,
  star: <Star />,
  sortDown: <ArrowDownward />,
  sportingDirector: <WorkspacePremium />,
  teams: <Groups />,
  time: <QueryBuilder />,
  triplet: <Filter3 />,
  tag: <LocalOffer />,
  tags: <LocalOffer />,
  text: <MenuBook />,
  thinking: <PsychologyAlt />,
  teamAdministrator: <AccountBox />,
  tableList: <TableView />,
  upcoming: <Upcoming />,
  win: <ThumbUp />,
  video: <VideoLibraryIcon />,
  videoAnalysis: <Analytics />,
  videoGeneral: <VideoLibraryIcon />,
  offensive: <ElectricBolt />,
  oneTimePayment: <MonetizationOn />,
};

export function iconUi({ id, size = 'md', style = {}, sx = {} }) {
  const icon = icons[id];
  if (!icon) return null;

  return React.cloneElement(icon, { fontSize: size, style, sx });
}

export function getIconList() {
  return Object.keys(icons).sort();
}
