export const domainBoxSx = {
  sx: {
    px: 1,
    py: 0.9,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
    bgcolor: 'background.level1',
    borderBottom: '1px solid',
    borderColor: 'divider',
    boxShadow: 'sm',
    borderRadius: 'sm',
  },
}

export const modalSx = {
  kpiStrip: {
    p: 1.25,
    borderRadius: 'md',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
    flexWrap: 'wrap',
  },
  filters: {
    p: 1,
    borderRadius: 'md',
    display: 'grid',
    gap: 1,
    gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr', md: '2fr 1fr 1fr 1fr' },
    alignItems: 'center',
  },
  table: {
    p: 1,
    borderRadius: 'md',
    overflow: 'auto',
  },
  row: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '2fr 1fr 1fr 1fr 1fr' },
    gap: 1,
    alignItems: 'center',
    py: 0.75,
    px: 0.75,
    borderBottom: '1px solid',
    borderColor: 'divider',
    '&:last-of-type': { borderBottom: 'none' },
  },
  headRow: {
    position: 'sticky',
    top: 0,
    zIndex: 1,
    bgcolor: 'background.level1',
    boxShadow: 'sm',
    borderRadius: 'sm',
  },
  nameCell: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.75,
    minWidth: 0,
  },
  nameText: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
}
