// features/playersDatabase/catalog/clubs.catalog.js

const AGE_GROUPS = [
  {
    id: 'kids-b',
    label: 'ילדים ב',
    kind: 'teams',
    slots: [
      { id: 'kids-b-1', order: 1, label: 'קבוצה 1' },
      { id: 'kids-b-2', order: 2, label: 'קבוצה 2' },
      { id: 'kids-b-3', order: 3, label: 'קבוצה 3' },
    ],
  },
  {
    id: 'kids-a',
    label: 'ילדים א',
    kind: 'teams',
    slots: [
      { id: 'kids-a-1', order: 1, label: 'קבוצה 1' },
      { id: 'kids-a-2', order: 2, label: 'קבוצה 2' },
      { id: 'kids-a-3', order: 3, label: 'קבוצה 3' },
    ],
  },
  {
    id: 'teens-g',
    label: 'נערים ג',
    kind: 'teams',
    slots: [
      { id: 'teens-g-1', order: 1, label: 'קבוצה 1' },
      { id: 'teens-g-2', order: 2, label: 'קבוצה 2' },
    ],
  },
  {
    id: 'teens-b',
    label: 'נערים ב',
    kind: 'teams',
    slots: [
      { id: 'teens-b-1', order: 1, label: 'קבוצה 1' },
      { id: 'teens-b-2', order: 2, label: 'קבוצה 2' },
    ],
  },
  {
    id: 'teens-a',
    label: 'נערים א',
    kind: 'teams',
    slots: [
      { id: 'teens-a-1', order: 1, label: 'קבוצה 1' },
      { id: 'teens-a-2', order: 2, label: 'קבוצה 2' },
    ],
  },
  {
    id: 'youth',
    label: 'נוער',
    kind: 'yearGroups',
  },
];

const CLUB_SHORT_NAMES = {
  'מכבי תל אביב': 'מכבי ת"א',
  'הפועל תל אביב': 'הפועל ת"א',
  'מכבי פתח תקוה': 'מכבי פ"ת',
  'הפועל פתח תקוה': 'הפועל פ"ת',
  'מכבי כפר סבא': 'מכבי כפ"ס',
  'הפועל כפר סבא': 'הפועל כפ"ס',
  'הפועל באר שבע': 'הפועל ב"ש',
  'הפועל ראשון לציון': 'הפועל ראשל"צ',
  'מכבי ראשון לציון': 'מכבי ראשל"צ',
  'הפועל ירושלים': 'הפועל י"ם',
  'בית"ר ירושלים': 'בית"ר י"ם',
  'הפועל רמת השרון': 'הפועל רמה"ש',
  'הפועל רמת גן': 'הפועל ר"ג',
  'מועדון כדורגל חולון ירמיהו': 'מ.כ ירמיהו חולון',
  'מ.ס אשדוד': 'מ.ס אשדוד',
  'מ.כ אשדוד': 'מ.כ אשדוד',
  'א.ס אשדוד': 'א.ס אשדוד',
};

const CLUB_PREFIX_SHORT_NAMES = [
  { prefix: 'מועדון ספורט כדורגל', short: 'מ.ס' },
  { prefix: 'מועדון כדורגל', short: 'מ.כ' },
  { prefix: 'מועדון ספורט', short: 'מ.ס' },
  { prefix: 'אגודת ספורט', short: 'א.ס' },
]

const clean = value => String(value ?? '').trim()

const buildClubShortNameFromPrefix = name => {
  const clubName = clean(name)
  if (!clubName) return ''

  for (const item of CLUB_PREFIX_SHORT_NAMES) {
    if (!clubName.startsWith(item.prefix)) continue

    const rest = clean(clubName.slice(item.prefix.length))
    return [item.short, rest].filter(Boolean).join(' ')
  }

  return clubName
}

const decorateAgeGroups = clubLevel =>
  AGE_GROUPS.map(ageGroup =>
    ageGroup.kind === 'teams' || clubLevel < 4
      ? {
          ...ageGroup,
          slots: Array.isArray(ageGroup.slots)
            ? ageGroup.slots.map(slot => ({ ...slot }))
            : undefined,
        }
      : { id: ageGroup.id, label: ageGroup.label, kind: ageGroup.kind }
  );

const decorateClubCatalogItem = club => ({
  ...club,
  shortName: CLUB_SHORT_NAMES[club.name] || buildClubShortNameFromPrefix(club.name),
  ageGroups: decorateAgeGroups(club.clubLevel),
});

const RAW_PLAYERS_DATABASE_CLUBS_CATALOG = [
  {
    id: "maccabi-tel-aviv",
    name: "מכבי תל אביב",
    clubLevel: 1,
    aliases: [],
  },
  {
    id: "maccabi-haifa",
    name: "מכבי חיפה",
    clubLevel: 1,
    aliases: [],
  },
  {
    id: "hapoel-tel-aviv",
    name: "הפועל תל אביב",
    clubLevel: 1,
    aliases: [],
  },
  {
    id: "maccabi-netanya",
    name: "מכבי נתניה",
    clubLevel: 1,
    aliases: [],
  },
  {
    id: "maccabi-petah-tikva",
    name: "מכבי פתח תקוה",
    clubLevel: 1,
    aliases: [],
  },
  {
    id: "hapoel-kfar-saba",
    name: "הפועל כפר סבא",
    clubLevel: 1,
    aliases: ['הפועל כפ"ס אילן'],
  },
  {
    id: "hapoel-beer-sheva",
    name: "הפועל באר שבע",
    clubLevel: 1,
    aliases: [],
  },
  {
    id: "hapoel-petah-tikva",
    name: "הפועל פתח תקוה",
    clubLevel: 1,
    aliases: [],
  },
  {
    id: "hapoel-jerusalem",
    name: "הפועל ירושלים",
    clubLevel: 1,
    aliases: [],
  },
  {
    id: "hapoel-ramat-gan",
    name: "הפועל רמת גן",
    clubLevel: 1,
    aliases: ['הפועל ר"ג דרום'],
  },
  {
    id: "beitar-jerusalem",
    name: "בית\"ר ירושלים",
    clubLevel: 1,
    aliases: [],
  },
  {
    id: "hapoel-raanana",
    name: "הפועל רעננה",
    clubLevel: 1,
    aliases: ['הפ. רעננה דן ווידנבאום', 'הפועל רעננה 2'],
  },
  {
    id: "ms-ashdvd",
    name: "מועדון ספורט אשדוד",
    clubLevel: 1,
    aliases: [],
  },
  {
    id: "hapoel-haifa",
    name: "הפועל חיפה",
    clubLevel: 1,
    aliases: [],
  },
  {
    id: "hapoel-hadera-arn",
    name: "הפועל חדרה ערן",
    clubLevel: 1,
    aliases: [],
  },
  {
    id: "hapoel-rishon-letzion",
    name: "הפועל ראשון לציון",
    clubLevel: 2,
    aliases: [],
  },
  {
    id: "bnei-sakhnin",
    name: "בני סכנין",
    clubLevel: 2,
    aliases: [],
  },
  {
    id: "hapoel-kiryat-shmona",
    name: "הפועל קרית שמונה",
    clubLevel: 2,
    aliases: [],
  },
  {
    id: "beitar-tubruk",
    name: "בית\"ר טוברוק",
    clubLevel: 2,
    aliases: [],
  },
  {
    id: "hapoel-nir-ramat-hasharon",
    name: "הפועל ניר רמת השרון",
    clubLevel: 2,
    aliases: ['הפועל ניר רמה"ש'],
  },
  {
    id: "bnei-yhvdh-tel-aviv",
    name: "בני יהודה תל אביב",
    clubLevel: 2,
    aliases: [],
  },
  {
    id: "maccabi-herzliya",
    name: "מכבי הרצליה",
    clubLevel: 2,
    aliases: ['מכבי הרצליה ליאור אסולין'],
  },
  {
    id: "maccabi-beer-sheva",
    name: "מכבי באר שבע",
    clubLevel: 2,
    aliases: ['מכבי ב"ש'],
  },
  {
    id: "shmshvn-tel-aviv",
    name: "שמשון תל אביב",
    clubLevel: 2,
    aliases: ['שמשון תל אביב', 'שמשון תל אביב רועי פלס', 'שמשון ת"א רועי פלס'],
  },
  {
    id: "hapoel-herzliya-ironi",
    name: "הפועל הרצליה עירוני",
    clubLevel: 2,
    aliases: [],
  },
  {
    id: "maccabi-kryt-gt",
    name: "מכבי קרית גת",
    clubLevel: 2,
    aliases: [],
  },
  {
    id: "ironi-mvdyayn",
    name: "עירוני מודיעין",
    clubLevel: 2,
    aliases: ['ע. מודיעין'],
  },
  {
    id: "mk-nvh-yvsf",
    name: "מועדון כדורגל נוה יוסף",
    clubLevel: 2,
    aliases: [],
  },
  {
    id: "maccabi-shvhm",
    name: "מכבי שוהם",
    clubLevel: 2,
    aliases: [],
  },
  {
    id: "maccabi-yavne",
    name: "מכבי יבנה",
    clubLevel: 2,
    aliases: [],
  },
  {
    id: "hapoel-nvf-hglyl",
    name: "הפועל נוף הגליל",
    clubLevel: 2,
    aliases: [],
  },
  {
    id: "hapoel-akko",
    name: "הפועל עכו",
    clubLevel: 2,
    aliases: [],
  },
  {
    id: "maccabi-tsvr-shlvm-kryt-byalyk",
    name: "מכבי צור שלום קרית ביאליק",
    clubLevel: 2,
    aliases: [],
  },
  {
    id: "ms-beer-sheva",
    name: "מועדון ספורט באר שבע",
    clubLevel: 2,
    aliases: ['מ.ס. ב"ש'],
  },
  {
    id: "hapoel-kryt-avnv",
    name: "הפועל קרית אונו",
    clubLevel: 2,
    aliases: [],
  },
  {
    id: "sktsyh-ns-tsyvnh",
    name: "סקציה נס ציונה",
    clubLevel: 2,
    aliases: ['ס. נס ציונה'],
  },
  {
    id: "hkh-maccabi-amydr-ramat-gan",
    name: "הכח מכבי עמידר רמת גן",
    clubLevel: 3,
    aliases: ['הכח מכבי עמידר ר"ג "שגב שושן"'],
  },
  {
    id: "hapoel-hvd-hasharon",
    name: "הפועל הוד השרון",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "ms-kryt-ym",
    name: "מועדון ספורט קרית ים",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "maccabi-bnei-ryynh",
    name: "מכבי בני ריינה",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "maccabi-ironi-kiryat-ata",
    name: "מכבי עירוני קרית אתא",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "mk-maccabi-ashklvn",
    name: "מועדון כדורגל מכבי אשקלון",
    clubLevel: 3,
    aliases: ['מ.כ. מכבי אשקלון'],
  },
  {
    id: "beitar-nahariya",
    name: "בית\"ר נהריה",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "as-nordia-jerusalem",
    name: "אגודת ספורט נורדיה ירושלים",
    clubLevel: 3,
    aliases: ['א.ס. נורדיה ירושלים'],
  },
  {
    id: "ironi-nshr",
    name: "עירוני נשר",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "hapoel-mhnh-yhvdh",
    name: "הפועל מחנה יהודה",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "gdna-tel-aviv-yhvdh",
    name: "גדנע תל אביב",
    clubLevel: 3,
    aliases: ['גדנע ת"א רוני'],
  },
  {
    id: "hapoel-hvf-hkrml",
    name: "הפועל חוף הכרמל",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "maccabi-ypv",
    name: "מכבי יפו",
    clubLevel: 3,
    aliases: ['מכבי יפו קביליו "קונורטי', 'מכבי יפו קביליו'],
  },
  {
    id: "hapoel-apvlh",
    name: "הפועל עפולה",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "maccabi-amyshb-petah-tikva",
    name: "מכבי עמישב פתח תקוה",
    clubLevel: 3,
    aliases: ['מ. עמישב פ"ת ברק הלפרן צו פיוס', 'מכבי עמישב פ"ת'],
  },
  {
    id: "ms-ayhvd-drvm-hasharon",
    name: "מועדון ספורט איחוד דרום השרון",
    clubLevel: 3,
    aliases: ['מ.ס. איחוד דרום השרון'],
  },
  {
    id: "ironi-tbryh",
    name: "עירוני טבריה",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "hapoel-alyh-kfar-saba",
    name: "הפועל עליה כפר סבא",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "hapoel-prdsyyh-nvam",
    name: "הפועל פרדסייה נועם",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "hapoel-kpr-shlm",
    name: "הפועל כפר שלם",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "maccabi-ironi-bt-ym",
    name: "מכבי עירוני בת ים",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "beitar-haifa-yaakov",
    name: "בית\"ר חיפה יעקב",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "maccabi-ahy-ntsrt",
    name: "מכבי אחי נצרת",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "maccabi-nvvh-shann-aldd",
    name: "מכבי נווה שאנן אלדד",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "maccabi-amk-hpr",
    name: "מכבי עמק חפר",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "maccabi-sharyym-rehovot",
    name: "מכבי שעריים רחובות",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "shmshvn-bnei-tayibe",
    name: "שמשון בני טייבה",
    clubLevel: 3,
    aliases: [],
  },
  {
    id: "mk-hvlvn-yrmyhv",
    name: "מועדון כדורגל חולון ירמיהו",
    clubLevel: 4,
    aliases: ['מ.כ. חולון ירמיהו צפון', 'מ.כ. חולון ירמיהו'],
  },
  {
    id: "hapoel-ironi-krmyal",
    name: "הפועל עירוני כרמיאל",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-nhll-yzraal",
    name: "מועדון כדורגל נהלל יזרעאל",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-ironi-kpr-yvnh",
    name: "מכבי עירוני כפר יונה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-kdymh-tsvrn",
    name: "מועדון ספורט קדימה צורן",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-mth-ashr",
    name: "הפועל מטה אשר",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-kpr-kasm",
    name: "מועדון ספורט כפר קאסם",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ayhvd-bnei-bkh",
    name: "איחוד בני בקה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-maccabi-ironi-ashdvd",
    name: "מועדון כדורגל מכבי עירוני אשדוד",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-hapoel-lvd-bnei-rgb",
    name: "מועדון ספורט הפועל לוד בני רגב",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-mrmvrk-rehovot",
    name: "הפועל מרמורק רחובות",
    clubLevel: 4,
    aliases: ["הפ' מרמורק רחובות \"עופר\""],
  },
  {
    id: "mk-ironi-avr-yhvdh",
    name: "מועדון כדורגל עירוני אור יהודה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "tsayry-avm-al-pahm",
    name: "צעירי אום אל פאחם",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "as-ashdvd",
    name: "אגודת ספורט אשדוד",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-rmlh",
    name: "מועדון ספורט רמלה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "as-rmt-alyhv",
    name: "א.ס רמת אליהו",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ironi-bar-yakb",
    name: "עירוני באר יעקב",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-kpr-yasyf",
    name: "מועדון ספורט כפר יאסיף",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-kfar-saba",
    name: "מכבי כפר סבא",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-dlyt-al-krml",
    name: "הפועל דלית אל כרמל",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-kryt-hyym",
    name: "מועדון כדורגל קרית חיים",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "avtsmh-mk-hvlvn",
    name: "עוצמה מועדון כדורגל חולון",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-hapoel-glbva",
    name: "מועדון כדורגל הפועל גלבוע",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ironi-ashklvn",
    name: "עירוני אשקלון",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-tyrh",
    name: "מועדון ספורט טירה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-ironi-arabh",
    name: "הפועל עירוני עראבה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-rehovot",
    name: "מכבי רחובות",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-avm-al-pahm",
    name: "הפועל אום אל פאחם",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-byt-shan-msylvt",
    name: "הפועל בית שאן מסילות",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-prds-hnh-krkvr",
    name: "מועדון ספורט פרדס חנה כרכור",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "beitar-ironi-kiryat-gat-dudu",
    name: "בית\"ר עירוני קרית גת דודו",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-tyrt-krml",
    name: "הפועל טירת כרמל",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-ironi-bkh-al-grbyyh",
    name: "הפועל עירוני בקה אל גרבייה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-shefa-amr",
    name: "מועדון ספורט שפרעם",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-karmel-haifa",
    name: "מועדון כדורגל כרמל חיפה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "beitar-ramat-gan",
    name: "בית\"ר רמת גן",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-bnei-hgvln-vhglyl",
    name: "מועדון ספורט בני הגולן והגליל",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-dymvnh",
    name: "מועדון ספורט דימונה",
    clubLevel: 4,
    aliases: ['מ.ס דימונה'],
  },
  {
    id: "ms-bnei-ypv-avrtvdvksym",
    name: "מועדון ספורט בני יפו אורתודוכסים",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-yhvd-mvnvsvn",
    name: "מכבי יהוד מונוסון",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-sktsyh-malvt-trshyha",
    name: "מכבי סקציה מעלות תרשיחא",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-tsayry-kpr-kna",
    name: "מועדון ספורט צעירי כפר כנא",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "tsayry-sakhnin",
    name: "צעירי סכנין",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-bvayynh",
    name: "הפועל בועיינה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-hvlvn-tspryrym",
    name: "הפועל חולון צפרירים",
    clubLevel: 4,
    aliases: ['הפועל חולון צפרירים'],
  },
  {
    id: "ms-tzirei-haifa",
    name: "מועדון ספורט צעירי חיפה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ahvvh-kpr-kra",
    name: "אחווה כפר קרע",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "beitar-kfar-saba-shlomi",
    name: "בית\"ר כפר סבא שלומי",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "bnei-yhvd",
    name: "בני יהוד",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-haifa-ruby-shapira",
    name: "מועדון ספורט חיפה רובי שפירא",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-kryt-mlaky-ironi",
    name: "מכבי קרית מלאכי עירוני",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "beitar-gedera",
    name: "בית\"ר גדרה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "bnei-aylt",
    name: "בני אילת",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-lb-hasharon",
    name: "הפועל לב השרון",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-bneimynh",
    name: "מועדון כדורגל בנימינה",
    sourceName: "מועדון כדורגל בנימינה (נוער)",
    clubLevel: 4,
    aliases: ["מועדון כדורגל בנימינה (נוער)"],
  },
  {
    id: "hapoel-ms-hbl-mvdyayn",
    name: "הפועל מועדון ספורט חבל מודיעין",
    sourceName: "הפועל מועדון ספורט חבל מודיעין (נוער)",
    clubLevel: 4,
    aliases: ["הפועל מועדון ספורט חבל מודיעין (נוער)"],
  },
  {
    id: "maccabi-ahy-ayksl",
    name: "מכבי אחי איכסל",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-ironi-aryal",
    name: "מועדון כדורגל עירוני אריאל",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-nhlt-yhvdh-rishon-letzion",
    name: "הפועל נחלת יהודה ראשון לציון",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-ayhvd-bnei-gt",
    name: "הפועל איחוד בני ג'ת",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-bnei-aablyn",
    name: "הפועל בני אעבלין",
    sourceName: "הפועל בני אעבלין (נוער)",
    clubLevel: 4,
    aliases: ["הפועל בני אעבלין (נוער)"],
  },
  {
    id: "maccabi-brkay",
    name: "מכבי ברקאי",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "shykvn-vtykym-ramat-gan",
    name: "שיכון ותיקים רמת גן",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-dyr-hna",
    name: "הפועל דיר חנא",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-asabv-gvsh-mbshrt-tsyvn",
    name: "הפועל ע.ס.אבו גוש מבשרת ציון",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-glyl-gvln",
    name: "מועדון כדורגל גליל גולן",
    sourceName: "מועדון כדורגל גליל גולן (נוער)",
    clubLevel: 4,
    aliases: ["מועדון כדורגל גליל גולן (נוער)"],
  },
  {
    id: "mk-ahvvh-kpr-mnda",
    name: "מועדון כדורגל אחווה כפר מנדא",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-gan-yavne",
    name: "מכבי גן יבנה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-avspya",
    name: "מכבי עוספיא",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-ironi-tmrh",
    name: "מכבי עירוני טמרה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-atlyt",
    name: "מכבי עתלית",
    sourceName: "מכבי עתלית (נוער)",
    clubLevel: 4,
    aliases: ["מכבי עתלית (נוער)"],
  },
  {
    id: "hapoel-rmt-yshral",
    name: "הפועל רמת ישראל",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "beitar-ironi-maale-adumim",
    name: "בית\"ר עירוני מעלה אדומים",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-gny-tkvvh",
    name: "מועדון כדורגל גני תקווה",
    sourceName: "מועדון כדורגל גני תקווה (נוער)",
    clubLevel: 4,
    aliases: ["מועדון כדורגל גני תקווה (נוער)"],
  },
  {
    id: "mk-tsayry-aylvt",
    name: "מועדון כדורגל צעירי עילוט",
    sourceName: "מועדון כדורגל צעירי עילוט (נוער)",
    clubLevel: 4,
    aliases: ["מועדון כדורגל צעירי עילוט (נוער)"],
  },
  {
    id: "mk-mytr",
    name: "מועדון כדורגל מיתר",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-shykvn-hmzrh",
    name: "מועדון ספורט שיכון המזרח",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-yvknam",
    name: "הפועל יוקנעם",
    sourceName: "הפועל יוקנעם (נוער)",
    clubLevel: 4,
    aliases: ["הפועל יוקנעם (נוער)"],
  },
  {
    id: "ayhvd-tsayry-ayksl-smyr",
    name: "איחוד צעירי איכסל סמיר",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "beitar-pardes-hanna",
    name: "בית\"ר פרדס חנה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "beitar-petah-tikva-dado",
    name: "בית\"ר פתח תקוה \"דדו\"",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-gdrh",
    name: "הפועל גדרה",
    sourceName: "הפועל גדרה (נוער)",
    clubLevel: 4,
    aliases: ["הפועל גדרה (נוער)"],
  },
  {
    id: "mk-shefa-amr",
    name: "מועדון כדורגל שפרעם",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ironi-byt-shmsh",
    name: "עירוני בית שמש",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-bnei-banh",
    name: "הפועל בני בענה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-kavkb",
    name: "הפועל כאוכב",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-mgdl-hamk",
    name: "הפועל מגדל העמק",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-nvgydat-ahmd",
    name: "מכבי נוג'ידאת אחמד",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-tsayry-yrka",
    name: "מכבי צעירי ירכא",
    sourceName: "מכבי צעירי ירכא (נוער)",
    clubLevel: 4,
    aliases: ["מכבי צעירי ירכא (נוער)"],
  },
  {
    id: "ironi-rash-hayn",
    name: "עירוני ראש העין",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-bnei-gsr-a-zrka",
    name: "הפועל בני ג'סר א זרקא",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-hapoel-yrvhm",
    name: "מועדון ספורט הפועל ירוחם",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-ramh",
    name: "מועדון ספורט ראמה",
    sourceName: "מועדון ספורט ראמה (נוער)",
    clubLevel: 4,
    aliases: ["מועדון ספורט ראמה (נוער)"],
  },
  {
    id: "hapoel-azvr",
    name: "הפועל אזור",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-shdrvt",
    name: "מועדון כדורגל שדרות",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-hapoel-bnei-ashdvd",
    name: "מועדון כדורגל הפועל בני אשדוד",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "beitar-umm-al-fahm",
    name: "בית\"ר אום אל פאחם",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "beitar-tel-aviv",
    name: "בית\"ר תל אביב",
    clubLevel: 4,
    aliases: ['בית"ר תל אביב חולון 1'],
  },
  {
    id: "hapoel-regional-council-mshgb",
    name: "הפועל מועצה אזורית משגב",
    sourceName: "הפועל מועצה אזורית משגב (נוער)",
    clubLevel: 4,
    aliases: ["הפועל מועצה אזורית משגב (נוער)"],
  },
  {
    id: "maccabi-hshkmh-hn",
    name: "מכבי השקמה חן",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ahly-tmrh",
    name: "אהלי טמרה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-kbbyr",
    name: "מועדון כדורגל כבביר",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-ironi-klnsvah",
    name: "מועדון כדורגל עירוני קלנסואה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ironi-bnei-kabvl",
    name: "עירוני בני כאבול",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-avrnyt-ironi",
    name: "הפועל אורנית עירוני",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "bnei-mgar",
    name: "בני מג'אר",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-maylya",
    name: "מועדון כדורגל מעיליא",
    sourceName: "מועדון כדורגל מעיליא (נוער)",
    clubLevel: 4,
    aliases: ["מועדון כדורגל מעיליא (נוער)"],
  },
  {
    id: "maccabi-ironi-ntybvt",
    name: "מכבי עירוני נתיבות",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-ypya",
    name: "הפועל יפיע",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-ayn-shlh",
    name: "הפועל עין סהלה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-ironi-ararh",
    name: "הפועל עירוני ערערה",
    sourceName: "הפועל עירוני ערערה (נוער)",
    clubLevel: 4,
    aliases: ["הפועל עירוני ערערה (נוער)"],
  },
  {
    id: "hapoel-amk-hyrdn",
    name: "הפועל עמק הירדן",
    sourceName: "הפועל עמק הירדן (נוער)",
    clubLevel: 4,
    aliases: ["הפועל עמק הירדן (נוער)"],
  },
  {
    id: "ms-tsayry-kpr-mnda",
    name: "מועדון ספורט צעירי כפר מנדא",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-netanya-2",
    name: "מכבי נתניה 2",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-ayn-mahl-gaml",
    name: "מכבי עין מאהל ג'אמל",
    sourceName: "מכבי עין מאהל ג'אמל (נוער)",
    clubLevel: 4,
    aliases: ["מכבי עין מאהל ג'אמל (נוער)"],
  },
  {
    id: "hapoel-byt-alyazr-grshvn",
    name: "הפועל בית אליעזר גרשון",
    sourceName: "הפועל בית אליעזר גרשון (נוער)",
    clubLevel: 4,
    aliases: ["הפועל בית אליעזר גרשון (נוער)"],
  },
  {
    id: "hapoel-kpr-kasm-shvaaa",
    name: "הפועל כפר קאסם שועאע",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-ryynh",
    name: "הפועל ריינה",
    sourceName: "הפועל ריינה (נוער)",
    clubLevel: 4,
    aliases: ["הפועל ריינה (נוער)"],
  },
  {
    id: "mk-alnhdh-ntsrt",
    name: "מועדון כדורגל אלנהדה נצרת",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "tsayry-shab",
    name: "צעירי שעב",
    sourceName: "צעירי שעב (נוער)",
    clubLevel: 4,
    aliases: ["צעירי שעב (נוער)"],
  },
  {
    id: "ayhvd-bnei-akko",
    name: "איחוד בני עכו",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-bnvt-sakhnin-narvt",
    name: "הפועל בנות סכנין (נערות)",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-hvrpysh",
    name: "הפועל חורפיש",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-tsayry-tyrh",
    name: "מועדון כדורגל צעירי טירה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mvadvn-tsayry-rht",
    name: "מועדון צעירי רהט",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-bnei-mvsmvs",
    name: "הפועל בני מוסמוס",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-brnr",
    name: "הפועל ברנר",
    sourceName: "הפועל ברנר (נוער)",
    clubLevel: 4,
    aliases: ["הפועל ברנר (נוער)"],
  },
  {
    id: "maccabi-knvt",
    name: "מכבי כנות",
    sourceName: "מכבי כנות (נוער)",
    clubLevel: 4,
    aliases: ["מכבי כנות (נוער)"],
  },
  {
    id: "avtsmh-beer-sheva",
    name: "עוצמה באר שבע",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-alatyhad-ntsrt",
    name: "הפועל אלאתיחאד נצרת",
    sourceName: "הפועל אלאתיחאד נצרת (נוער)",
    clubLevel: 4,
    aliases: ["הפועל אלאתיחאד נצרת (נוער)"],
  },
  {
    id: "hapoel-bkat-hyrdn",
    name: "הפועל בקעת הירדן",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-ironi-bnei-aablyn",
    name: "הפועל עירוני בני אעבלין",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-rmvt-mnshh-mgydv",
    name: "הפועל רמות מנשה מגידו",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-maccabi-nhryh",
    name: "מועדון כדורגל מכבי נהריה",
    sourceName: "מועדון כדורגל מכבי נהריה (נוער)",
    clubLevel: 4,
    aliases: ["מועדון כדורגל מכבי נהריה (נוער)"],
  },
  {
    id: "maccabi-ironi-brtah",
    name: "מכבי עירוני ברטעה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-ayhvd-aablyn",
    name: "הפועל איחוד אעבלין",
    sourceName: "הפועל איחוד אעבלין (נוער)",
    clubLevel: 4,
    aliases: ["הפועל איחוד אעבלין (נוער)"],
  },
  {
    id: "as-hvlvn-mvr",
    name: "אגודת ספורט חולון מור",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-ayhvd-bnei-smya",
    name: "הפועל איחוד בני סמיע",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-kpr-kna",
    name: "הפועל כפר כנא",
    sourceName: "הפועל כפר כנא (נוער)",
    clubLevel: 4,
    aliases: ["הפועל כפר כנא (נוער)"],
  },
  {
    id: "mk-mvatsh-ayzvryt-hvf-ashklvn",
    name: "מ.כ. מועצה איזורית חוף אשקלון",
    sourceName: "מ.כ. מועצה איזורית חוף אשקלון (נוער)",
    clubLevel: 4,
    aliases: ["מ.כ. מועצה איזורית חוף אשקלון (נוער)"],
  },
  {
    id: "mk-mzkrt-btyh",
    name: "מועדון כדורגל מזכרת בתיה",
    sourceName: "מועדון כדורגל מזכרת בתיה (נוער)",
    clubLevel: 4,
    aliases: ["מועדון כדורגל מזכרת בתיה (נוער)"],
  },
  {
    id: "ms-amk-hpr",
    name: "מועדון ספורט עמק חפר",
    sourceName: "מועדון ספורט עמק חפר (נוער)",
    clubLevel: 4,
    aliases: ["מועדון ספורט עמק חפר (נוער)"],
  },
  {
    id: "ayhvd-hapoel-byr-al-mksvr",
    name: "איחוד הפועל ביר אל מכסור",
    sourceName: "איחוד הפועל ביר אל מכסור (נוער)",
    clubLevel: 4,
    aliases: ["איחוד הפועל ביר אל מכסור (נוער)"],
  },
  {
    id: "hapoel-bnei-dyr-al-asd",
    name: "הפועל בני דיר אל אסד",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-tsayry-tmrh",
    name: "מועדון כדורגל צעירי טמרה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-bnei-ypya",
    name: "מועדון ספורט בני יפיע",
    sourceName: "מועדון ספורט בני יפיע (נוער)",
    clubLevel: 4,
    aliases: ["מועדון ספורט בני יפיע (נוער)"],
  },
  {
    id: "hapoel-nhf",
    name: "הפועל נחף",
    sourceName: "הפועל נחף (נוער)",
    clubLevel: 4,
    aliases: ["הפועל נחף (נוער)"],
  },
  {
    id: "mk-ard",
    name: "מועדון כדורגל ערד",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-ironi-hvrh",
    name: "מכבי עירוני חורה",
    sourceName: "מכבי עירוני חורה (נוער)",
    clubLevel: 4,
    aliases: ["מכבי עירוני חורה (נוער)"],
  },
  {
    id: "mk-avr-akyba",
    name: "מועדון כדורגל אור עקיבא",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-gbat-shmval",
    name: "מועדון ספורט גבעת שמואל",
    sourceName: "מועדון ספורט גבעת שמואל (נוער)",
    clubLevel: 4,
    aliases: ["מועדון ספורט גבעת שמואל (נוער)"],
  },
  {
    id: "ms-kdvrgl-hapoel-kryt-ym",
    name: "מועדון ספורט כדורגל הפועל קרית ים",
    sourceName: "מועדון ספורט כדורגל הפועל קרית ים (נוער)",
    clubLevel: 4,
    aliases: ["מועדון ספורט כדורגל הפועל קרית ים (נוער)"],
  },
  {
    id: "ayhvd-bnei-mgdl-krvm",
    name: "איחוד בני מג'דל כרום",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-mrvm-hglyl",
    name: "הפועל מרום הגליל",
    sourceName: "הפועל מרום הגליל (נוער)",
    clubLevel: 4,
    aliases: ["הפועל מרום הגליל (נוער)"],
  },
  {
    id: "ms-rishon-letzion",
    name: "מועדון ספורט ראשון לציון",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-tsvrn",
    name: "מכבי צורן",
    sourceName: "מכבי צורן (נוער)",
    clubLevel: 4,
    aliases: ["מכבי צורן (נוער)"],
  },
  {
    id: "ironi-byt-dgan",
    name: "עירוני בית דגן",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "bnei-dbvryh",
    name: "בני דבוריה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-rsht-mtn",
    name: "מועדון ספורט רשת מתנ\"סים טבעון",
    sourceName: "מועדון ספורט רשת מתנ\"סים טבעון (נוער)",
    clubLevel: 4,
    aliases: ["מועדון ספורט רשת מתנ\"סים טבעון (נוער)"],
  },
  {
    id: "maccabi-zkrvn-yakb",
    name: "מכבי זכרון יעקב",
    sourceName: "מכבי זכרון יעקב (נוער)",
    clubLevel: 4,
    aliases: ["מכבי זכרון יעקב (נוער)"],
  },
  {
    id: "bnei-avm-al-pahm",
    name: "בני אום אל פאחם",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-tvba",
    name: "הפועל טובא",
    sourceName: "הפועל טובא (נוער)",
    clubLevel: 4,
    aliases: ["הפועל טובא (נוער)"],
  },
  {
    id: "hapoel-bnei-arabh",
    name: "הפועל בני עראבה",
    sourceName: "הפועל בני עראבה (נוער)",
    clubLevel: 4,
    aliases: ["הפועל בני עראבה (נוער)"],
  },
  {
    id: "mk-bnei-raanana-avzy-khn",
    name: "מועדון כדורגל בני רעננה עוזי כהן",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-kpr-kma",
    name: "מועדון ספורט כפר כמא",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-bnei-zlph",
    name: "הפועל בני זלפה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-mtslyh",
    name: "הפועל מצליח",
    sourceName: "הפועל מצליח (נוער)",
    clubLevel: 4,
    aliases: ["הפועל מצליח (נוער)"],
  },
  {
    id: "mk-mgdl-krvm-shagvr",
    name: "מועדון כדורגל מג'דל כרום שאגור",
    sourceName: "מועדון כדורגל מג'דל כרום שאגור (נוער)",
    clubLevel: 4,
    aliases: ["מועדון כדורגל מג'דל כרום שאגור (נוער)"],
  },
  {
    id: "ms-byt-gan",
    name: "מועדון ספורט בית ג'אן",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-netanya-kolt-khen",
    name: "מועדון ספורט נתניה קולט כהן",
    sourceName: "מועדון ספורט נתניה קולט כהן (נוער)",
    clubLevel: 4,
    aliases: ["מועדון ספורט נתניה קולט כהן (נוער)"],
  },
  {
    id: "maccabi-gbat-shmval",
    name: "מכבי גבעת שמואל",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-mtn",
    name: "מכבי מתנ\"ס רהט",
    sourceName: "מכבי מתנ\"ס רהט (נוער)",
    clubLevel: 4,
    aliases: ["מכבי מתנ\"ס רהט (נוער)"],
  },
  {
    id: "mrkz-khylty-gvln-ktsryn",
    name: "מרכז קהילתי גולן קצרין",
    sourceName: "מרכז קהילתי גולן קצרין (נוער)",
    clubLevel: 4,
    aliases: ["מרכז קהילתי גולן קצרין (נוער)"],
  },
  {
    id: "hapoel-bary-ashkvl",
    name: "הפועל בארי אשכול",
    sourceName: "הפועל בארי אשכול (נוער)",
    clubLevel: 4,
    aliases: ["הפועל בארי אשכול (נוער)"],
  },
  {
    id: "maccabi-ironi-shdrvt",
    name: "מכבי עירוני שדרות",
    sourceName: "מכבי עירוני שדרות (נוער)",
    clubLevel: 4,
    aliases: ["מכבי עירוני שדרות (נוער)"],
  },
  {
    id: "ms-kabvl",
    name: "מועדון ספורט כאבול",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-ahvvh-prdys",
    name: "מכבי אחווה פרדיס",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-kryt-hyym-lybvbyts-yakb",
    name: "הפועל קרית חיים ליבוביץ יעקב",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-jerusalem",
    name: "מועדון כדורגל ירושלים",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "regional-council-shar-hngb",
    name: "מועצה אזורית שער הנגב",
    sourceName: "מועצה אזורית שער הנגב (נוער)",
    clubLevel: 4,
    aliases: ["מועצה אזורית שער הנגב (נוער)"],
  },
  {
    id: "hapoel-bnei-ararh-aarh",
    name: "הפועל בני ערערה עארה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-mtn",
    name: "מועדון כדורגל מתנ\"ס אופקים",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-rht",
    name: "הפועל רהט",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-kdvrgl-mshhd",
    name: "מועדון ספורט כדורגל משהד",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-bnei-abv-snan",
    name: "מכבי בני אבו סנאן",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-hapoel-shgb-shlvm",
    name: "מועדון ספורט הפועל שגב שלום",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-kryyt-hyym",
    name: "מועדון ספורט קריית חיים",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-ahly-shab",
    name: "הפועל אהלי שעב",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-hapoel-psvth",
    name: "מועדון כדורגל הפועל פסוטה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-ahvvh-shab",
    name: "מכבי אחווה שעב",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-tsayry-mshhd",
    name: "מכבי צעירי משהד",
    sourceName: "מכבי צעירי משהד (נוער)",
    clubLevel: 4,
    aliases: ["מכבי צעירי משהד (נוער)"],
  },
  {
    id: "beitar-kiryat-ata-kfir",
    name: "בית\"ר קרית אתא כפיר",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-bsmt-tbavn",
    name: "הפועל בסמת טבעון",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-bnei-pvrdys",
    name: "מועדון ספורט בני פורדיס",
    sourceName: "מועדון ספורט בני פורדיס (נוער)",
    clubLevel: 4,
    aliases: ["מועדון ספורט בני פורדיס (נוער)"],
  },
  {
    id: "maccabi-bnei-tvraan",
    name: "מכבי בני טורעאן",
    sourceName: "מכבי בני טורעאן (נוער)",
    clubLevel: 4,
    aliases: ["מכבי בני טורעאן (נוער)"],
  },
  {
    id: "hapoel-ahva-haifa",
    name: "הפועל אחוה חיפה",
    sourceName: "הפועל אחוה חיפה (נוער)",
    clubLevel: 4,
    aliases: ["הפועל אחוה חיפה (נוער)"],
  },
  {
    id: "bnei-alslam-rht",
    name: "בני אלסלאם רהט",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "bnei-dyr-hna",
    name: "בני דיר חנא",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-gan-yavne",
    name: "הפועל גן יבנה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-hapoel-rmt-yshy",
    name: "מועדון כדורגל הפועל רמת ישי",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "elitzur-ypv-tel-aviv",
    name: "אליצור יפו תל אביב",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-bnei-pkyayn",
    name: "הפועל בני פקיעין",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "mk-tzofi-haifa-samir-prahod",
    name: "מועדון כדורגל צופי חיפה סמיר פרהוד",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ms-tsayry-tayibe",
    name: "מועדון ספורט צעירי טייבה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "maccabi-gbatyym",
    name: "מכבי גבעתיים",
    sourceName: "מכבי גבעתיים (נוער)",
    clubLevel: 4,
    aliases: ["מכבי גבעתיים (נוער)"],
  },
  {
    id: "maccabi-tsayry-klnsvah",
    name: "מכבי צעירי קלנסואה",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-mrhbym",
    name: "הפועל מרחבים",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "ahly-shefa-amr-lkdvrgl",
    name: "אהלי שפרעם לכדורגל",
    sourceName: "אהלי שפרעם לכדורגל (נוער)",
    clubLevel: 4,
    aliases: ["אהלי שפרעם לכדורגל (נוער)"],
  },
  {
    id: "hapoel-glyl-alyvn",
    name: "הפועל גליל עליון",
    sourceName: "הפועל גליל עליון (נוער)",
    clubLevel: 4,
    aliases: ["הפועל גליל עליון (נוער)"],
  },
  {
    id: "mk-regional-council-yvab",
    name: "מועדון כדורגל מועצה אזורית יואב",
    sourceName: "מועדון כדורגל מועצה אזורית יואב (נוער)",
    clubLevel: 4,
    aliases: ["מועדון כדורגל מועצה אזורית יואב (נוער)"],
  },
  {
    id: "bnei-ytsalal-rehovot",
    name: "בני יצ'אלאל רחובות",
    clubLevel: 4,
    aliases: [],
  },
  {
    id: "hapoel-bnei-shmavn",
    name: "הפועל בני שמעון",
    sourceName: "הפועל בני שמעון (נוער)",
    clubLevel: 4,
    aliases: ["הפועל בני שמעון (נוער)"],
  },
];

export const PLAYERS_DATABASE_CLUBS_CATALOG = RAW_PLAYERS_DATABASE_CLUBS_CATALOG.map(
  decorateClubCatalogItem
);

