// src/features/playersDatabase/catalog/genericObjects.catalog.js

// Firestore schema contracts.
// These objects represent the real document shapes written to Firestore.
// Keep their fields and nested structures aligned with the active write builders.
// The five active contracts below must not be treated as UI catalogs or examples:
// PLAYERS_DATABASE_LEAGUES_MASTER_DOCUMENT_CATALOG,
// BIRTH_TEAMS_DATABASE_GENERIC_OBJECTS_CATALOG,
// PLAYERS_DATABASE_GENERIC_OBJECTS_CATALOG,
// SEARCHINDEX_BIRTH_TEAM_SEASON_GENERIC_OBJECT,
// SEARCHINDEX_PLAYER_SEASON_GENERIC_OBJECT.

export const PLAYERS_DATABASE_LEAGUES_MASTER_DOCUMENT_CATALOG = {
  id: 'all',
  docType: 'leagues_master',
  updatedAt: null,

  summary: {
    leaguesCount: 0,
    seasonsCount: 0,
    teamsCount: 0,
    playersCount: 0,
    playersWithScoutProfileCount: 0,
    scoutProfilesCount: 0,
  },

  leagues: [
    {
      leagueId: '',
      leagueDocumentId: '',
      leagueName: '',
      leagueUrl: '',
      region: '',
      ageGroupId: '',
      ageGroupLabel: '',
      active: true,
      updatedAt: null,

      seasons: [
        {
          seasonId: '',
          seasonKey: '',
          leagueDocumentId: '',
          leagueName: '',
          leagueUrl: '',
          ageGroupId: '',
          ageGroupLabel: '',
          birthYear: 0,
          teamsCount: 0,
          playersCount: 0,
          playersWithScoutProfileCount: 0,
          scoutProfilesCount: 0,
          tableRankCount: 0,
          currentDocRef: '',
          historyDocRef: '',
          updatedAt: null,
        },
      ],
    },
  ],
};

export const LEAGUES_DATABASE_GENERIC_OBJECTS_CATALOG = {
  id: '',
  leagueId: '',
  leagueName: '',
  region: '',
  ageGroupId: '',
  ageGroupLabel: '',
  level: null,
  createdAt: null,

  current: {
    seasonId: '',
    seasonKey: '',
    seasonUrl: '',
    birthYear: 0, // חובה
    leagueTotalRound: 0,
    goalsEnvironment: null,
    scoutEnvironment: null,
    tableRank: [
      {
        rank: 0,
        clubId: '',
        clubLevel: 0,
        birthTeamId: '',
        birthTeamSlot: 1,
        teamId: '',
        teamUrl: '',
        playersCount: 0,
        hasPlayers: false,
        hasStats: false,
        statsComplete: false,
        teamStats: {
          points: 0,
          goalsFor: 0,
          goalsAgainst: 0,
          teamGamePlayed: 0,
          attackPerformance: null,
          defensePerformance: null,
          attackNormalPerformance: null,
          defenseNormalPerformance: null,
          scoutPerformance: null,
        },
        scoutProfilesSummary: {
          total: 0,
          profileCounts: {},
        },
        updatedAt: null,
      },
    ],
    updatedAt: null,
  },

  history: [
    {
      seasonId: '',
      seasonKey: '',
      seasonUrl: '',
      birthYear: 0, // חובה
      leagueTotalRound: 0,
      goalsEnvironment: null,
      scoutEnvironment: null,
      tableRank: [
        {
          rank: 0,
          clubId: '',
          clubLevel: 0,
          birthTeamId: '',
          birthTeamSlot: 1,
          teamId: '',
          teamUrl: '',
          playersCount: 0,
          hasPlayers: false,
          hasStats: false,
          statsComplete: false,
          teamStats: {
            points: 0,
            goalsFor: 0,
            goalsAgainst: 0,
            teamGamePlayed: 0,
            attackPerformance: null,
            defensePerformance: null,
            attackNormalPerformance: null,
            defenseNormalPerformance: null,
            scoutPerformance: null,
          },
          scoutProfilesSummary: {
            total: 0,
            profileCounts: {},
          },
          updatedAt: null,
        },
      ],
      updatedAt: null,
    },
  ],

  updatedAt: null,
};

export const PLAYER_SCOUT_NULLABLE_STRUCTURED_FIELDS = [
  'scoutOpportunity',
  'scoutVerification',
  'scoutProfileProgression',
  'scoutProfileHierarchy',
  'scoutProfileCaseStrength',
  'scoutTrajectory',
  'scoutTransferContext',
]

const PLAYER_SCOUT_NARRATIVE_SNAPSHOT_GENERIC_OBJECT = {
  version: 1,
  inputHash: '',
  scope: '',
  seasonKeys: [],
  profileRefs: [
    {
      seasonKey: '',
      birthTeamId: '',
      birthTeamDocumentId: '',
      birthTeamSlot: 0,
      profileId: '',
    },
  ],
  revision: 0,
  generatedAt: null,
  approvedAt: null,
  source: 'ai',
  generator: {
    model: '',
    promptVersion: '',
  },
  content: {
    title: '',
    summary: '',
  },
}

const PLAYER_SCOUT_NARRATIVE_GENERIC_OBJECT = {
  version: 1,
  seasons: [
    {
      seasonId: '',
      seasonKey: '',
      approved: PLAYER_SCOUT_NARRATIVE_SNAPSHOT_GENERIC_OBJECT,
    },
  ],
  career: PLAYER_SCOUT_NARRATIVE_SNAPSHOT_GENERIC_OBJECT,
}

const PLAYER_SCOUT_STATE_GENERIC_OBJECT = {
  scoutCandidateSignals: [
    {
      id: 'near_profile',
      profileId: '',
      profileLabel: '',
      distance: null,
      distancePct: null,
      status: '',
      trend: '',
      distanceDelta: null,
      distanceDeltaPct: null,
    },
  ],
  scoutSpotlights: [
    {
      id: '',
      confidence: '',
      effect: '',
      evidence: [],
      details: {},
    },
  ],
  scoutOpportunity: {
    effectiveActionStatus: '',
    baseActionStatus: 'watch',
    automaticActionStatus: 'watch',
    manualActionStatus: '',
    hasManualDecision: false,
    profilesRemoved: false,
    manualDecision: {
      hasDecision: false,
      actionStatus: '',
      reason: '',
      note: '',
      decidedAt: null,
      seasonKey: '',
      profileIds: [],
    },
    source: '',
    boostScore: 0,
    reductionScore: 0,
    netScore: 0,
    boosts: [
      {
        id: '',
        points: 0,
        details: {},
      },
    ],
    reductions: [
      {
        id: '',
        points: 0,
        details: {},
      },
    ],
    signalPersistence: {
      profileRepeat: {
        profileId: '',
        seasons: 0,
      },
      combinationRepeat: {
        combinationId: '',
        profileIds: [],
        seasons: 0,
      },
      decay: {
        seasonsWithoutSignal: 0,
        profileIds: [],
        lastSignalSeasonKey: '',
        currentSeasonKey: '',
        currentSeasonCounted: false,
      },
      reasons: [],
    },
    exposureLevel: '',
    reasons: [],
    profileIds: [],
    candidateProfileIds: [],
    bestProfileId: '',
  },
  scoutVerification: {
    checks: [],
    answeredChecks: [],
    missingChecks: [],
    nextBestCheck: null,
    dimensions: {},
    completion: {
      answered: 0,
      total: 0,
      complete: false,
    },
  },
  scoutProfileProgression: {
    distances: [],
    nearProfiles: [],
    nearestProfile: null,
  },
  scoutProfileHierarchy: {
    primaryProfileId: '',
    primarySignal: null,
    supportingProfileIds: [],
    supportingSignals: [],
    orderedProfileIds: [],
  },
  scoutProfileCaseStrength: {
    primaryProfileId: '',
    primaryProfileStrength: {
      depth: 0,
      depthPct: 0,
      measurableRuleCount: 0,
    },
    profileCount: 0,
    profileIds: [],
    supportingProfileIds: [],
    hasDefinedCombination: false,
    combinationCount: 0,
    combinationIds: [],
  },
  scoutTrajectory: {
    direction: '',
    confidence: '',
    evidence: [],
    stintsCount: 0,
    seasonsCount: 0,
    latestTransfer: null,
    transferEvents: [],
  },
  scoutTransferContext: {
    type: 'transfer',
    seasonKey: '',
    fromClubId: '',
    fromClubName: '',
    fromBirthTeamId: '',
    fromBirthTeamDocumentId: '',
    fromTeamName: '',
    toClubId: '',
    toClubName: '',
    toBirthTeamId: '',
    toBirthTeamDocumentId: '',
    toTeamName: '',
    fromClubStrengthLevel: 0,
    toClubStrengthLevel: 0,
    fromLeagueLevel: 0,
    toLeagueLevel: 0,
    clubStrengthChange: 0,
    leagueLevelChange: 0,
    direction: '',
    moveType: '',
    sameSeason: false,
    fromPrimaryPosition: '',
    toPrimaryPosition: '',
    fromPositionLayer: '',
    toPositionLayer: '',
    impact: {
      minutesPctDelta: 0,
      startsPctDelta: 0,
      goalsPer90Delta: 0,
      roleChanged: false,
      positionLayerChanged: false,
      profileChange: {
        added: [],
        lost: [],
        retained: [],
      },
    },
  },
  scoutEngineVersion: 'scouting-v2',
};

export const PLAYER_SCOUT_STATS_LOAD_MEASUREMENT_GENERIC_OBJECT = {
  snapshotKey: '',
  capturedAt: '',
  engineVersion: 'scouting-v2',
  primaryProfileId: '',
  profileIds: [],
  profileStates: [
    {
      profileId: '',
      matched: false,
      depth: null,
      distance: null,
    },
  ],
};

const PLAYER_SCOUT_STATS_LOAD_MEASUREMENTS_GENERIC_OBJECT = {
  previous: null,
  current: null,
};

// Canonical operational Team Season document.
// Source of truth for roster/stats and the season-level computed scout state.
export const BIRTH_TEAMS_DATABASE_GENERIC_OBJECTS_CATALOG = {
  id: '',
  clubId: '',
  birthTeamId: '',
  birthYear: 0,
  birthTeamSlot: 1,
  displayName: '',
  teamId: '',
  createdAt: null,

  current: [
    {
      seasonId: '',
      ageGroupId: '',
      seasonStatus: '',
      leagueId: '',
      teamUrl: '',
      birthYear: 0,
      leagueTotalRound: 0,
      leagueLevel: 0,
      expectedLevelDelta: null,
      seasonKey: '',
      playersCount: 0,
      playerSeasonIndexCount: 0,
      scoutProfiledPlayersCount: 0,
      scoutProfilesSummary: {
        total: 0,
        profileCounts: {},
      },
      teamPlayers: [
        {
          playerId: '',
          externalPlayerId: '',
          playerDocumentId: '',
          identityKey: '',
          fullName: '',
          normalizedName: '',
          aliases: [],
          playerUrl: '',
          notes: '',
          numShirt: '',
          statsStatus: 'missing',

          rosterStatus: 'regular',
          manualTransferDirection: '',
          isYoungerAgeGroup: false,

          primaryPosition: '',
          positionLayer: '',

          playerStats: {
            games: 0,
            goals: 0,
            yellowCards: 0,
            minutes: 0,
            starts: 0,
            substituteIn: 0,
            substitutedOut: 0,
            teamMinutes: 0,
            teamGames: 0,
            teamRank: null,
            teamGoalsFor: 0,
            teamGoalsAgainst: 0,
            teamAttackPerformance: null,
            teamDefensePerformance: null,
            minutesPerGame: 0,
            goalsPer90: 0,
          },

          scoutProfiles: [],
          scoutCombinations: [],
          ...PLAYER_SCOUT_STATE_GENERIC_OBJECT,
          scoutStatsLoadMeasurements: PLAYER_SCOUT_STATS_LOAD_MEASUREMENTS_GENERIC_OBJECT,
          updatedAt: null,
        },
      ],
      scoutProfiles: [],
      teamStats: {
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        teamGamePlayed: 0,
      },
      updatedAt: null,
    },
  ],

  history: [
    {
      seasonId: '',
      ageGroupId: '',
      seasonStatus: '',
      seasonKey: '',
      leagueId: '',
      teamUrl: '',
      birthYear: 0,
      leagueTotalRound: 0,
      leagueLevel: 0,
      expectedLevelDelta: null,
      playersCount: 0,
      playerSeasonIndexCount: 0,
      scoutProfiledPlayersCount: 0,
      scoutProfilesSummary: {
        total: 0,
        profileCounts: {},
      },
      teamPlayers: [
        {
          playerId: '',
          externalPlayerId: '',
          playerDocumentId: '',
          identityKey: '',
          fullName: '',
          normalizedName: '',
          aliases: [],
          playerUrl: '',
          notes: '',
          numShirt: '',
          statsStatus: 'missing',

          rosterStatus: 'regular',
          manualTransferDirection: '',
          isYoungerAgeGroup: false,

          primaryPosition: '',
          positionLayer: '',

          playerStats: {
            games: 0,
            goals: 0,
            yellowCards: 0,
            minutes: 0,
            starts: 0,
            substituteIn: 0,
            substitutedOut: 0,
            teamMinutes: 0,
            teamGames: 0,
            teamRank: null,
            teamGoalsFor: 0,
            teamGoalsAgainst: 0,
            teamAttackPerformance: null,
            teamDefensePerformance: null,
            minutesPerGame: 0,
            goalsPer90: 0,
          },

          scoutProfiles: [],
          scoutCombinations: [],
          ...PLAYER_SCOUT_STATE_GENERIC_OBJECT,
          scoutStatsLoadMeasurements: PLAYER_SCOUT_STATS_LOAD_MEASUREMENTS_GENERIC_OBJECT,
          updatedAt: null,
        },
      ],
      scoutProfiles: [],
      teamStats: {
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        teamGamePlayed: 0,
      },
      updatedAt: null,
    },
  ],

  updatedAt: null,
};

const PLAYER_SCOUT_PROFILE_GENERIC_OBJECT = {
  profileId: '',
  profileLabel: '',
  perspective: '',
  searchLevels: [],
  teamFilter: '',
  positionContext: '',
  interestLevel: '',
  profileDepth: {
    depth: 0,
    depthPct: 0,
    measurableRuleCount: 0,
    rules: [
      {
        metric: '',
        reason: '',
        depth: 0,
        depthPct: 0,
      },
    ],
  },
  profileStrength: {
    depth: 0,
    depthPct: 0,
    measurableRuleCount: 0,
  },
  warnings: [],
  score: null,
  reasons: [],
  requiredReview: [],
  matchEvidence: [
    {
      metric: '',
      actual: null,
      op: '',
      threshold: null,
      reason: '',
      matched: false,
    },
  ],
  scoutContext: {
    team: {
      classification: '',
      relevantSide: '',
      attack: {
        classification: '',
        priorityLevel: '',
        score: null,
      },
      defense: {
        classification: '',
        priorityLevel: '',
        score: null,
      },
      legacyFilter: '',
    },
    competition: {
      classification: '',
      clubLevel: null,
      clubStrengthLevel: null,
      leagueLevel: null,
      levelGap: null,
    },
    position: {
      evidence: '',
      requiredContext: '',
      positionValue: '',
    },
    teamGate: {
      passed: false,
      mode: '',
      reason: '',
      legacyFilterPassed: null,
      clubStrengthLevel: null,
      leagueLevel: null,
    },
  },
  spotlights: [
    {
      id: '',
      confidence: '',
      effect: '',
      evidence: [],
      details: {},
    },
  ],
};

const PLAYER_MANUAL_REVIEW_BASE_GENERIC_OBJECT = {
  note: '',
  updatedAt: null,
  seasonKey: '',
};

const PLAYER_MANUAL_REVIEW_GENERIC_OBJECT = {
  position: {
    ...PLAYER_MANUAL_REVIEW_BASE_GENERIC_OBJECT,
    value: '',
    status: 'unknown',
  },
  agent_status: {
    ...PLAYER_MANUAL_REVIEW_BASE_GENERIC_OBJECT,
    value: 'unknown',
  },
  transfer_history: {
    ...PLAYER_MANUAL_REVIEW_BASE_GENERIC_OBJECT,
    status: 'unknown',
    transfers: [],
  },
  goal_distribution: {
    ...PLAYER_MANUAL_REVIEW_BASE_GENERIC_OBJECT,
    status: 'unknown',
  },
  minutes_distribution: {
    ...PLAYER_MANUAL_REVIEW_BASE_GENERIC_OBJECT,
    status: 'unknown',
  },
  visual_review: {
    ...PLAYER_MANUAL_REVIEW_BASE_GENERIC_OBJECT,
    status: 'unknown',
  },
  agent_path_fit: {
    ...PLAYER_MANUAL_REVIEW_BASE_GENERIC_OBJECT,
    value: 'unknown',
  },
  scout_path_fit: {
    ...PLAYER_MANUAL_REVIEW_BASE_GENERIC_OBJECT,
    value: 'unknown',
  },
};

const PLAYER_MANUAL_IMMEDIACY_DECISION_GENERIC_OBJECT = {
  actionStatus: '',
  reason: '',
  note: '',
  decidedAt: null,
  seasonKey: '',
  profileIds: [],
};

const PLAYER_MANUAL_IMMEDIACY_HISTORY_GENERIC_OBJECT = {
  ...PLAYER_MANUAL_IMMEDIACY_DECISION_GENERIC_OBJECT,
};

// Canonical tracked Player document.
// Source of truth for multi-season scout history, manual review and manual immediacy.
export const PLAYERS_DATABASE_GENERIC_OBJECTS_CATALOG = {
  id: '',
  externalPlayerId: '',
  fullName: '',
  normalizedName: '',
  birthYear: null,
  birthDate: null,
  status: '',
  favorite: false,
  notes: '',
  primaryPosition: '',
  positionLayer: '',
  numShirt: '',

  tracking: {
    favorite: false,
    watchlist: false,
    firstTrackedAt: null,
    trackingReasons: [],
  },

  playerReview: PLAYER_MANUAL_REVIEW_GENERIC_OBJECT,
  manualImmediacyDecision: PLAYER_MANUAL_IMMEDIACY_DECISION_GENERIC_OBJECT,
  manualImmediacyHistory: [PLAYER_MANUAL_IMMEDIACY_HISTORY_GENERIC_OBJECT],

  verification: {
    mode: 'manual',
    answers: [
      {
        questionId: '',
        answer: 'unknown',
        sourceType: '',
        sourceLabel: '',
        answeredAt: null,
        reviewAfter: null,
      },
    ],
    updatedAt: null,
  },

  events: [
    {
      eventKey: '',
      type: '',
      seasonId: '',
      seasonKey: '',
      clubId: '',
      birthTeamId: '',
      profileId: '',
      fromClubId: '',
      fromClubName: '',
      toClubId: '',
      toClubName: '',
      fromBirthTeamId: '',
      fromBirthTeamDocumentId: '',
      toBirthTeamId: '',
      toBirthTeamDocumentId: '',
      moveType: '',
      direction: '',
      fromClubStrengthLevel: null,
      toClubStrengthLevel: null,
      fromLeagueLevel: null,
      toLeagueLevel: null,
      detectedAt: null,
    },
  ],

  scoutNarrative: PLAYER_SCOUT_NARRATIVE_GENERIC_OBJECT,

  createdAt: null,
  updatedAt: null,

  current: [
    {
      seasonId: '',
      seasonKey: '',
      seasonStatus: '',
      leagueId: '',
      leagueName: '',
      ageGroupId: '',
      ageGroupLabel: '',
      clubId: '',
      clubName: '',
      clubLevel: 0,
      clubStrengthLevel: 0,
      leagueLevel: 0,
      expectedLevelDelta: null,
      teamName: '',
      birthTeamId: '',
      birthTeamDocumentId: '',
      birthTeamSlot: 1,
      teamId: '',
      birthYear: null,
      playerUrl: '',
      notes: '',
      primaryPosition: '',
      positionLayer: '',
      numShirt: '',
      rosterStatus: 'regular',
      manualTransferDirection: '',
      isYoungerAgeGroup: false,
      statsStatus: 'missing',
      playerStats: {
        games: 0,
        goals: 0,
        yellowCards: 0,
        minutes: 0,
        starts: 0,
        substituteIn: 0,
        substitutedOut: 0,
        teamMinutes: 0,
        teamGames: 0,
        teamRank: null,
        teamGoalsFor: 0,
        teamGoalsAgainst: 0,
        teamAttackPerformance: null,
        teamDefensePerformance: null,
      },
      scoutProfiles: [PLAYER_SCOUT_PROFILE_GENERIC_OBJECT],
      scoutCombinations: [],
      ...PLAYER_SCOUT_STATE_GENERIC_OBJECT,
      scoutStatsLoadMeasurementHistory: [PLAYER_SCOUT_STATS_LOAD_MEASUREMENT_GENERIC_OBJECT],
      updatedAt: null,
    },
  ],

  history: [
    {
      seasonId: '',
      seasonKey: '',
      seasonStatus: '',
      leagueId: '',
      leagueName: '',
      ageGroupId: '',
      ageGroupLabel: '',
      clubId: '',
      clubName: '',
      clubLevel: 0,
      clubStrengthLevel: 0,
      leagueLevel: 0,
      expectedLevelDelta: null,
      teamName: '',
      birthTeamId: '',
      birthTeamDocumentId: '',
      birthTeamSlot: 1,
      teamId: '',
      birthYear: null,
      playerUrl: '',
      notes: '',
      primaryPosition: '',
      positionLayer: '',
      numShirt: '',
      rosterStatus: 'regular',
      manualTransferDirection: '',
      isYoungerAgeGroup: false,
      statsStatus: 'missing',
      playerStats: {
        games: 0,
        goals: 0,
        yellowCards: 0,
        minutes: 0,
        starts: 0,
        substituteIn: 0,
        substitutedOut: 0,
        teamMinutes: 0,
        teamGames: 0,
        teamRank: null,
        teamGoalsFor: 0,
        teamGoalsAgainst: 0,
        teamAttackPerformance: null,
        teamDefensePerformance: null,
      },
      scoutProfiles: [PLAYER_SCOUT_PROFILE_GENERIC_OBJECT],
      scoutCombinations: [],
      ...PLAYER_SCOUT_STATE_GENERIC_OBJECT,
      scoutStatsLoadMeasurementHistory: [PLAYER_SCOUT_STATS_LOAD_MEASUREMENT_GENERIC_OBJECT],
      updatedAt: null,
    },
  ],

  updatedAt: null,
};

export const SEARCHINDEX_BIRTH_TEAM_SEASON_GENERIC_OBJECT = {
  id: '',
  entityType: 'birthTeamSeason',
  entityId: '',

  displayName: '',
  normalizedDisplayName: '',

  leagueId: '',
  seasonId: '',
  seasonKey: '',
  clubId: '',
  clubLevel: 0,
  clubStrengthLevel: 0,
  birthTeamId: '',
  birthTeamDocumentId: '',
  birthTeamSlot: 1,
  teamId: '',
  teamDocumentId: '',
  teamUrl: '',
  seasonUrl: '',

  ageGroupId: '',
  ageGroupLabel: '',
  birthYear: 0,
  leagueTotalRound: 0,
  leagueLevel: 0,
  expectedLevelDelta: null,
  region: '',
  seasonDataStatus: '',
  seasonDataCompleteness: '',

  tableRank: 0,
  tableAttackRank: 0,
  tableDefenseRank: 0,

  points: 0,
  goalsFor: 0,
  goalsAgainst: 0,
  goalsForPerGame: 0,
  goalsAgainstPerGame: 0,
  teamGamePlayed: 0,

  seasonStatus: '',
  normalizationStatus: '',
  normalizationVersion: 0,
  remainingTeamGames: 0,

  projectedPointsRaw: 0,
  projectedPoints: 0,
  searchPoints: 0,
  projectedGoalsForRaw: 0,
  projectedGoalsFor: 0,
  searchGoalsFor: 0,
  projectedGoalsAgainstRaw: 0,
  projectedGoalsAgainst: 0,
  searchGoalsAgainst: 0,
  projectedTeamGamePlayedRaw: 0,
  projectedTeamGamePlayed: 0,
  searchTeamGamePlayed: 0,

  teamPerformanceSchemaVersion: 5,

  attackQualityRate: null,
  attackTargetRate: null,
  attackTargetNormalized: null,
  attackTargetLevel: '',
  attackRankingRate: null,
  attackRankingNormalized: null,
  attackRankingLevel: '',
  attackAnomalyRate: null,
  attackAnomalyLevel: '',
  attackScoutPriorityScore: null,
  attackPriorityLevel: '',
  attackOpportunityType: '',

  defenseQualityRate: null,
  defenseTargetRate: null,
  defenseTargetNormalized: null,
  defenseTargetLevel: '',
  defenseRankingRate: null,
  defenseRankingNormalized: null,
  defenseRankingLevel: '',
  defenseAnomalyRate: null,
  defenseAnomalyLevel: '',
  defenseScoutPriorityScore: null,
  defensePriorityLevel: '',
  defenseOpportunityType: '',

  teamScoutEngineVersion: '',
  scoutCompetitionRelation: '',
  scoutCompetitionGap: null,
  attackingNeedLevel: 'none',
  defensiveNeedLevel: 'none',
  balanceProblemLevel: 'none',
  recruitmentWindow: 'none',

  playersCount: 0,
  playerSeasonIndexCount: 0,
  scoutProfiledPlayersCount: 0,
  scoutProfilesSummary: {
    total: 0,
    profileCounts: {},
  },

  sourceCollection: 'leagues',
  sourceDocumentId: '',
  sourceTarget: '',

  updatedAt: null,
};

// Player Season search projection only.
// Never treat this document as the source of truth for profile evidence or player history.
export const SEARCHINDEX_PLAYER_SEASON_GENERIC_OBJECT = {
  id: '',
  entityType: 'playerSeason',
  entityId: '',

  displayName: '',
  normalizedDisplayName: '',
  aliases: [],
  identityKey: '',
  identityBirthYear: 0,

  playerId: '',
  playerDocumentId: '',
  externalPlayerId: '',
  playerUrl: '',
  notes: '',
  rosterStatus: 'regular',
  isYoungerAgeGroup: false,

  leagueId: '',
  seasonId: '',
  seasonKey: '',
  clubId: '',
  clubLevel: 0,
  clubStrengthLevel: 0,
  birthTeamId: '',
  birthTeamDocumentId: '',
  birthTeamSlot: 1,
  teamId: '',
  teamDocumentId: '',
  teamUrl: '',
  seasonUrl: '',


  ageGroupId: '',
  ageGroupLabel: '',
  birthYear: 0,
  leagueTotalRound: 0,
  leagueLevel: 0,
  expectedLevelDelta: null,
  region: '',

  primaryPosition: '',
  positionLayer: '',
  numShirt: '',
  seasonNotes: '',
  statsStatus: 'missing',

  teamTableRank: 0,
  teamTableAttackRank: 0,
  teamTableDefenseRank: 0,
  teamGoalsFor: 0,
  teamGoalsAgainst: 0,
  teamGoalsForPerGame: 0,
  teamGamePlayed: 0,

  games: 0,
  goals: 0,
  yellowCards: 0,
  minutes: 0,
  starts: 0,
  substituteIn: 0,
  substitutedOut: 0,
  teamMinutes: 0,
  teamGames: 0,
  minutesPerGame: 0,
  goalsPer90: 0,
  goalsPerGameDuration: 0,

  statsSnapshots: {
    previous: null,
    current: {
      capturedAt: '',
      snapshotKey: '',
      teamGamePlayed: 0,
      games: 0,
      goals: 0,
      minutes: 0,
      starts: 0,
      substituteIn: 0,
      substitutedOut: 0,
    },
  },

  gameMinutes: 0,
  seasonStatus: '',
  normalizationStatus: '',
  normalizationVersion: 0,
  remainingTeamGames: 0,
  teamMinutesPlayed: 0,
  minutesShareRate: 0,
  projectedRemainingMinutes: 0,

  projectedMinutesRaw: 0,
  projectedMinutes: 0,
  searchMinutes: 0,
  projectedGoalsRaw: 0,
  projectedGoals: 0,
  searchGoals: 0,
  projectedGamesRaw: 0,
  projectedGames: 0,
  searchGames: 0,
  projectedStartsRaw: 0,
  projectedStarts: 0,
  searchStarts: 0,

  primaryScoutProfileId: '',
  primaryScoutProfileStrengthDepthPct: null,
  primaryScoutWarnings: [],
  primaryScoutScore: null,
  primaryScoutInterestLevel: '',
  primaryScoutTeamGateMode: '',
  nearScoutProfileId: '',
  nearScoutProfileDistancePct: null,
  nearScoutProfileTrend: '',
  scoutEffectiveImmediacyStatus: '',
  scoutBaseImmediacyStatus: 'watch',
  scoutAutomaticImmediacyStatus: 'watch',
  scoutManualImmediacyStatus: '',
  scoutHasManualImmediacyDecision: false,
  scoutImmediacyBoostScore: 0,
  scoutImmediacyBoostIds: [],
  scoutImmediacyReductionScore: 0,
  scoutImmediacyReductionIds: [],
  scoutImmediacyNetScore: 0,
  scoutProfilePersistenceSeasons: 0,
  scoutCombinationPersistenceSeasons: 0,
  scoutSignalDecaySeasons: 0,
  scoutSignalDecayLastSeasonKey: '',
  scoutProfileCaseStrengthProfileCount: 0,
  scoutProfileCaseHasCombination: false,
  scoutProfileCaseCombinationIds: [],
  scoutExposureLevel: '',
  scoutNextBestCheckId: '',
  scoutEngineVersion: 'scouting-v2',
  scoutTransferMoveType: '',
  scoutTransferDirection: '',
  scoutTransferFromClubId: '',
  scoutTransferToClubId: '',
  scoutTransferSameSeason: false,

  secondaryScoutProfileId: '',
  secondaryScoutProfileStrengthDepthPct: null,
  secondaryScoutWarnings: [],
  secondaryScoutScore: null,
  scoutProfileIds: [],
  scoutCombinationIds: [],
  scoutProfileSearchIds: [],

  sourceCollection: 'players',
  sourceDocumentId: '',
  sourceTarget: '',

  updatedAt: null,
};

export const TEAMS_DATABASE_GENERIC_OBJECTS_CATALOG = BIRTH_TEAMS_DATABASE_GENERIC_OBJECTS_CATALOG

export const SEARCHINDEX_DATABASE_GENERIC_OBJECTS_CATALOG = {
  birthTeamSeason: SEARCHINDEX_BIRTH_TEAM_SEASON_GENERIC_OBJECT,
  playerSeason: SEARCHINDEX_PLAYER_SEASON_GENERIC_OBJECT,
};
