// features/playersDatabase/catalog/leagues.catalog.js

export const PLAYERS_DATABASE_LEAGUE_GAME_TIME_BY_AGE_GROUP = {
  u19: 90,
  u17: 90,
  u16: 80,
  u15: 80,
  u14: 70,
}

export const resolvePlayersDatabaseLeagueGameTime = ageGroupId =>
  PLAYERS_DATABASE_LEAGUE_GAME_TIME_BY_AGE_GROUP[String(ageGroupId || '').trim()] || 90

export const PLAYERS_DATABASE_LEAGUES_CATALOG = [
  {
    id: 'u19-premier',
    ageGroupId: 'u19',
    ageGroupLabel: 'נוער',
    order: 1,
    level: 1,
    region: '',
    name: 'ליגת העל',
    aliases: ['על', 'ליגת על'],
  },
  {
    id: 'u19-national',
    ageGroupId: 'u19',
    ageGroupLabel: 'נוער',
    order: 2,
    level: 2,
    region: '',
    name: 'ליגה לאומית',
    aliases: ['לאומית', 'ליגת לאומית'],
  },
  {
    id: 'u19-regional-north',
    ageGroupId: 'u19',
    ageGroupLabel: 'נוער',
    order: 3,
    level: 3,
    region: 'north',
    name: 'ליגה ארצית צפון',
    aliases: ['ארצית צפון', 'ליגה ארצית צפון'],
  },
  {
    id: 'u19-regional-south',
    ageGroupId: 'u19',
    ageGroupLabel: 'נוער',
    order: 4,
    level: 3,
    region: 'south',
    name: 'ליגה ארצית דרום',
    aliases: ['ארצית דרום', 'ליגה ארצית דרום'],
  },
  {
    id: 'u19-district-center',
    ageGroupId: 'u19',
    ageGroupLabel: 'נוער',
    order: 5,
    level: 4,
    region: 'center',
    name: 'ליגה מחוזית מרכז',
    aliases: ['מרכז', 'מחוז מרכז'],
  },
  {
    id: 'u19-district-sharon',
    ageGroupId: 'u19',
    ageGroupLabel: 'נוער',
    order: 6,
    level: 4,
    region: 'sharon',
    name: 'ליגה מחוזית שרון',
    aliases: ['שרון', 'מחוז שרון'],
  },
  {
    id: 'u19-district-shfela',
    ageGroupId: 'u19',
    ageGroupLabel: 'נוער',
    order: 7,
    level: 4,
    region: 'shfela',
    name: 'ליגה מחוזית שפלה',
    aliases: ['שפלה', 'מחוז שפלה'],
  },
  {
    id: 'u19-district-north',
    ageGroupId: 'u19',
    ageGroupLabel: 'נוער',
    order: 8,
    level: 4,
    region: 'north',
    name: 'ליגה מחוזית צפון',
    aliases: ['צפון', 'מחוז צפון'],
  },
  {
    id: 'u19-district-south',
    ageGroupId: 'u19',
    ageGroupLabel: 'נוער',
    order: 9,
    level: 4,
    region: 'south',
    name: 'ליגה מחוזית דרום',
    aliases: ['דרום', 'מחוז דרום'],
  },

  {
    id: 'u17-premier',
    ageGroupId: 'u17',
    ageGroupLabel: 'נערים א',
    order: 1,
    level: 1,
    region: '',
    name: 'ליגת העל',
    aliases: ['על', 'ליגת על'],
  },
  {
    id: 'u17-national',
    ageGroupId: 'u17',
    ageGroupLabel: 'נערים א',
    order: 2,
    level: 2,
    region: '',
    name: 'ליגה לאומית',
    aliases: ['לאומית', 'ליגת לאומית'],
  },
  {
    id: 'u17-regional-north',
    ageGroupId: 'u17',
    ageGroupLabel: 'נערים א',
    order: 3,
    level: 3,
    region: 'north',
    name: 'ליגה ארצית צפון',
    aliases: ['ארצית צפון', 'ליגה ארצית צפון'],
  },
  {
    id: 'u17-regional-south',
    ageGroupId: 'u17',
    ageGroupLabel: 'נערים א',
    order: 4,
    level: 3,
    region: 'south',
    name: 'ליגה ארצית דרום',
    aliases: ['ארצית דרום', 'ליגה ארצית דרום'],
  },
  {
    id: 'u17-district-dan',
    ageGroupId: 'u17',
    ageGroupLabel: 'נערים א',
    order: 5,
    level: 4,
    region: 'dan',
    name: 'ליגה מחוזית דן',
    aliases: ['דן', 'מחוז דן'],
  },
  {
    id: 'u17-district-center',
    ageGroupId: 'u17',
    ageGroupLabel: 'נערים א',
    order: 6,
    level: 4,
    region: 'center',
    name: 'ליגה מחוזית מרכז',
    aliases: ['מרכז', 'מחוז מרכז'],
  },
  {
    id: 'u17-district-shfela',
    ageGroupId: 'u17',
    ageGroupLabel: 'נערים א',
    order: 7,
    level: 4,
    region: 'shfela',
    name: 'ליגה מחוזית שפלה',
    aliases: ['שפלה', 'מחוז שפלה'],
  },
  {
    id: 'u17-district-sharon',
    ageGroupId: 'u17',
    ageGroupLabel: 'נערים א',
    order: 8,
    level: 4,
    region: 'sharon',
    name: 'ליגה מחוזית שרון',
    aliases: ['שרון', 'מחוז שרון'],
  },
  {
    id: 'u17-district-north',
    ageGroupId: 'u17',
    ageGroupLabel: 'נערים א',
    order: 9,
    level: 4,
    region: 'north',
    name: 'ליגה מחוזית צפון',
    aliases: ['צפון', 'מחוז צפון'],
  },
  {
    id: 'u17-district-south',
    ageGroupId: 'u17',
    ageGroupLabel: 'נערים א',
    order: 10,
    level: 4,
    region: 'south',
    name: 'ליגה מחוזית דרום',
    aliases: ['דרום', 'מחוז דרום'],
  },

  {
    id: 'u16-premier',
    ageGroupId: 'u16',
    ageGroupLabel: 'נערים ב',
    order: 1,
    level: 1,
    region: '',
    name: 'ליגת העל',
    aliases: ['על', 'ליגת על'],
  },
  {
    id: 'u16-national',
    ageGroupId: 'u16',
    ageGroupLabel: 'נערים ב',
    order: 2,
    level: 2,
    region: '',
    name: 'ליגה לאומית',
    aliases: ['לאומית', 'ליגת לאומית'],
  },
  {
    id: 'u16-regional-north',
    ageGroupId: 'u16',
    ageGroupLabel: 'נערים ב',
    order: 3,
    level: 3,
    region: 'north',
    name: 'ליגה ארצית צפון',
    aliases: ['ארצית צפון', 'ליגה ארצית צפון'],
  },
  {
    id: 'u16-regional-south',
    ageGroupId: 'u16',
    ageGroupLabel: 'נערים ב',
    order: 4,
    level: 3,
    region: 'south',
    name: 'ליגה ארצית דרום',
    aliases: ['ארצית דרום', 'ליגה ארצית דרום'],
  },
  {
    id: 'u16-district-dan',
    ageGroupId: 'u16',
    ageGroupLabel: 'נערים ב',
    order: 5,
    level: 4,
    region: 'dan',
    name: 'ליגה מחוזית דן',
    aliases: ['דן', 'מחוז דן'],
  },
  {
    id: 'u16-district-center',
    ageGroupId: 'u16',
    ageGroupLabel: 'נערים ב',
    order: 6,
    level: 4,
    region: 'center',
    name: 'ליגה מחוזית מרכז',
    aliases: ['מרכז', 'מחוז מרכז'],
  },
  {
    id: 'u16-district-shfela',
    ageGroupId: 'u16',
    ageGroupLabel: 'נערים ב',
    order: 7,
    level: 4,
    region: 'shfela',
    name: 'ליגה מחוזית שפלה',
    aliases: ['שפלה', 'מחוז שפלה'],
  },
  {
    id: 'u16-district-sharon',
    ageGroupId: 'u16',
    ageGroupLabel: 'נערים ב',
    order: 8,
    level: 4,
    region: 'sharon',
    name: 'ליגה מחוזית שרון',
    aliases: ['שרון', 'מחוז שרון'],
  },
  {
    id: 'u16-district-north',
    ageGroupId: 'u16',
    ageGroupLabel: 'נערים ב',
    order: 9,
    level: 4,
    region: 'north',
    name: 'ליגה מחוזית צפון',
    aliases: ['צפון', 'מחוז צפון'],
  },
  {
    id: 'u16-district-south',
    ageGroupId: 'u16',
    ageGroupLabel: 'נערים ב',
    order: 10,
    level: 4,
    region: 'south',
    name: 'ליגה מחוזית דרום',
    aliases: ['דרום', 'מחוז דרום'],
  },
  {
    id: 'u16-district-mifratz',
    ageGroupId: 'u16',
    ageGroupLabel: 'נערים ב',
    order: 11,
    level: 4,
    region: 'mifratz',
    name: 'ליגה מחוזית מפרץ',
    aliases: ['מפרץ', 'מחוז מפרץ'],
  },

  {
    id: 'u15-premier',
    ageGroupId: 'u15',
    ageGroupLabel: 'נערים ג',
    order: 1,
    level: 1,
    region: '',
    name: 'ליגת העל',
    aliases: ['על', 'ליגת על'],
  },
  {
    id: 'u15-national',
    ageGroupId: 'u15',
    ageGroupLabel: 'נערים ג',
    order: 2,
    level: 2,
    region: '',
    name: 'ליגה לאומית',
    aliases: ['לאומית', 'ליגת לאומית'],
  },
  {
    id: 'u15-regional-north',
    ageGroupId: 'u15',
    ageGroupLabel: 'נערים ג',
    order: 3,
    level: 3,
    region: 'north',
    name: 'ליגה ארצית צפון',
    aliases: ['ארצית צפון', 'ליגה ארצית צפון'],
  },
  {
    id: 'u15-regional-south',
    ageGroupId: 'u15',
    ageGroupLabel: 'נערים ג',
    order: 4,
    level: 3,
    region: 'south',
    name: 'ליגה ארצית דרום',
    aliases: ['ארצית דרום', 'ליגה ארצית דרום'],
  },
  {
    id: 'u15-district-dan',
    ageGroupId: 'u15',
    ageGroupLabel: 'נערים ג',
    order: 5,
    level: 4,
    region: 'dan',
    name: 'ליגה מחוזית דן',
    aliases: ['דן', 'מחוז דן'],
  },
  {
    id: 'u15-district-center',
    ageGroupId: 'u15',
    ageGroupLabel: 'נערים ג',
    order: 6,
    level: 4,
    region: 'center',
    name: 'ליגה מחוזית מרכז',
    aliases: ['מרכז', 'מחוז מרכז'],
  },
  {
    id: 'u15-district-shfela',
    ageGroupId: 'u15',
    ageGroupLabel: 'נערים ג',
    order: 7,
    level: 4,
    region: 'shfela',
    name: 'ליגה מחוזית שפלה',
    aliases: ['שפלה', 'מחוז שפלה'],
  },
  {
    id: 'u15-district-sharon',
    ageGroupId: 'u15',
    ageGroupLabel: 'נערים ג',
    order: 8,
    level: 4,
    region: 'sharon',
    name: 'ליגה מחוזית שרון',
    aliases: ['שרון', 'מחוז שרון'],
  },
  {
    id: 'u15-district-north',
    ageGroupId: 'u15',
    ageGroupLabel: 'נערים ג',
    order: 9,
    level: 4,
    region: 'north',
    name: 'ליגה מחוזית צפון',
    aliases: ['צפון', 'מחוז צפון'],
  },
  {
    id: 'u15-district-south',
    ageGroupId: 'u15',
    ageGroupLabel: 'נערים ג',
    order: 10,
    level: 4,
    region: 'south',
    name: 'ליגה מחוזית דרום',
    aliases: ['דרום', 'מחוז דרום'],
  },
  {
    id: 'u15-district-mifratz',
    ageGroupId: 'u15',
    ageGroupLabel: 'נערים ג',
    order: 11,
    level: 4,
    region: 'mifratz',
    name: 'ליגה מחוזית מפרץ',
    aliases: ['מפרץ', 'מחוז מפרץ'],
  },

  {
    id: 'u14-district-dan',
    ageGroupId: 'u14',
    ageGroupLabel: 'ילדים א',
    order: 1,
    level: 3,
    region: 'dan',
    name: 'ליגה מחוזית דן',
    aliases: ['דן', 'מחוז דן'],
  },
  {
    id: 'u14-district-dan-1',
    ageGroupId: 'u14',
    ageGroupLabel: 'ילדים א',
    order: 2,
    level: 4,
    region: 'dan',
    name: 'ליגה מחוזית דן 1',
    aliases: ['דן 1', 'מחוז דן 1'],
  },
  {
    id: 'u14-district-dan-2',
    ageGroupId: 'u14',
    ageGroupLabel: 'ילדים א',
    order: 3,
    level: 5,
    region: 'dan',
    name: 'ליגה מחוזית דן 2',
    aliases: ['דן 2', 'מחוז דן 2'],
  },
  {
    id: 'u14-district-center',
    ageGroupId: 'u14',
    ageGroupLabel: 'ילדים א',
    order: 4,
    level: 1,
    region: 'center',
    name: 'ליגה מחוזית מרכז',
    aliases: ['מרכז', 'מחוז מרכז'],
  },
  {
    id: 'u14-district-center-1',
    ageGroupId: 'u14',
    ageGroupLabel: 'ילדים א',
    order: 5,
    level: 4,
    region: 'center',
    name: 'ליגה מחוזית מרכז 1',
    aliases: ['מרכז 1', 'מחוז מרכז 1'],
  },
  {
    id: 'u14-district-sharon',
    ageGroupId: 'u14',
    ageGroupLabel: 'ילדים א',
    order: 6,
    level: 2,
    region: 'sharon',
    name: 'ליגה מחוזית שרון',
    aliases: ['שרון', 'מחוז שרון'],
  },
  {
    id: 'u14-district-sharon-1',
    ageGroupId: 'u14',
    ageGroupLabel: 'ילדים א',
    order: 7,
    level: 4,
    region: 'sharon',
    name: 'ליגה מחוזית שרון 1',
    aliases: ['שרון 1', 'מחוז שרון 1'],
  },
  {
    id: 'u14-district-shfela',
    ageGroupId: 'u14',
    ageGroupLabel: 'ילדים א',
    order: 8,
    level: 3,
    region: 'shfela',
    name: 'ליגה מחוזית שפלה',
    aliases: ['שפלה', 'מחוז שפלה'],
  },
  {
    id: 'u14-district-shfela-1',
    ageGroupId: 'u14',
    ageGroupLabel: 'ילדים א',
    order: 9,
    level: 4,
    region: 'shfela',
    name: 'ליגה מחוזית שפלה 1',
    aliases: ['שפלה 1', 'מחוז שפלה 1'],
  },
  {
    id: 'u14-district-hof',
    ageGroupId: 'u14',
    ageGroupLabel: 'ילדים א',
    order: 10,
    level: 4,
    region: 'hof',
    name: 'ליגה מחוזית חוף',
    aliases: [],
  },
  {
    id: 'u14-district-mizrah',
    ageGroupId: 'u14',
    ageGroupLabel: 'ילדים א',
    order: 11,
    level: 5,
    region: 'mizrarh',
    name: 'ליגה מחוזית מזרח',
    aliases: [],
  },
];
