import { devPlanColors } from '../../../../../../ui/core/theme/Colors.js'

export const scoutProfileTooltipSx = {
  root: {
    width: 300,
    minHeight: 0,
    maxHeight: 200,
    maxWidth: 'min(300px, calc(100vw - 32px))',
    display: 'grid',
    gap: 0.85,
    p: 1,
    overflowY: 'auto',
    scrollbarWidth: 'thin',
    scrollbarColor: `${devPlanColors.tertiary} transparent`,
    '&::-webkit-scrollbar': {
      width: 5,
    },
    '&::-webkit-scrollbar-thumb': {
      backgroundColor: devPlanColors.tertiary,
      borderRadius: 99,
    },
    color: devPlanColors.primaryDark,
    bgcolor: devPlanColors.tertiaryLight,
    border: `1px solid ${devPlanColors.tertiary}`,
    borderRadius: 9,
  },
  profileSection: ({ divided = false } = {}) => ({
    display: 'grid',
    gap: 0.85,
    ...(divided
      ? {
        borderTop: `1px solid rgba(23, 59, 87, 0.18)`,
        paddingTop: 0.85,
      }
      : {}),
  }),
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 0.75,
  },
  profileTitle: {
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    gap: 0.55,
  },
  profileIcon: {
    width: 23,
    height: 23,
    flex: '0 0 auto',
    display: 'grid',
    placeItems: 'center',
    color: devPlanColors.primary,
    bgcolor: 'rgba(255, 255, 255, 0.78)',
    border: '1px solid rgba(23, 59, 87, 0.18)',
    borderRadius: '50%',
    '& svg': { fontSize: 13 },
  },
  title: {
    minWidth: 0,
    color: devPlanColors.primaryDark,
    fontSize: 13,
    fontWeight: 800,
    lineHeight: 1.2,
  },
  createdAt: {
    flex: '0 0 auto',
    color: devPlanColors.secondary,
    fontSize: 10.5,
    fontWeight: 700,
    whiteSpace: 'nowrap',
  },
  conditionsLabel: {
    display: 'inline-flex',
    alignSelf: 'start',
    justifySelf: 'start',
    width: 'auto',
    color: devPlanColors.primaryDark,
    fontSize: 11,
    fontWeight: 800,
    lineHeight: 1,
    borderBottom: `1px solid ${devPlanColors.primaryDark}`,
    paddingBottom: 0,
  },
  conditions: {
    display: 'grid',
    gap: 0.15,
  },
  condition: {
    display: 'grid',
    gap: 0.05,
  },
  conditionMeta: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 0.75,
  },
  conditionTitle: {
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    gap: 0.45,
  },
  conditionIcon: {
    width: 17,
    height: 17,
    flex: '0 0 auto',
    display: 'grid',
    placeItems: 'center',
    color: devPlanColors.tertiaryDark,
    '& svg': { fontSize: 12 },
  },
  conditionLabel: {
    minWidth: 0,
    color: devPlanColors.primaryDark,
    fontSize: 10.5,
    fontWeight: 600,
    lineHeight: 1.1,
  },
  conditionProgress: {
    flex: '0 0 auto',
    color: devPlanColors.primary,
    fontSize: 10.5,
    fontWeight: 800,
    lineHeight: 1,
  },
  progressTrack: {
    '--LinearProgress-trackColor': 'rgba(23, 59, 87, 0.12)',
    '--LinearProgress-progressColor': devPlanColors.tertiary,
    '--LinearProgress-thickness': '3px',
    minHeight: 3,
    height: 3,
  },
  emptyState: {
    color: devPlanColors.secondary,
    fontSize: 10.5,
  },
}
