import {
  STATS_AUDIT_V2_COVERED_TARGETS,
  STATS_AUDIT_V2_TARGET,
  STATS_AUDIT_V2_UNCOVERED_TARGETS,
} from './contract.js'

describe('Stats Audit V2 coverage', () => {
  test('all Stats Final Sync projection targets are covered', () => {
    expect(STATS_AUDIT_V2_COVERED_TARGETS).toEqual([
      STATS_AUDIT_V2_TARGET.TEAM_SEASON,
      STATS_AUDIT_V2_TARGET.COUNTERPARTS,
      STATS_AUDIT_V2_TARGET.PLAYER_DOCUMENTS,
      STATS_AUDIT_V2_TARGET.PLAYER_SEARCH_INDEXES,
      STATS_AUDIT_V2_TARGET.TEAM_SEARCH_INDEX,
      STATS_AUDIT_V2_TARGET.LEAGUE_METADATA,
      STATS_AUDIT_V2_TARGET.LEAGUES_MASTER,
      STATS_AUDIT_V2_TARGET.CLUBS,
      STATS_AUDIT_V2_TARGET.CLUBS_MASTER,
    ])
    expect(STATS_AUDIT_V2_UNCOVERED_TARGETS).toEqual([])
  })
})
