export const STATS_AUDIT_V2_RESULT = Object.freeze({
  CLEAN: 'clean',
  FINDINGS: 'findings',
  PARTIAL: 'partial',
})

export const STATS_AUDIT_V2_TARGET = Object.freeze({
  TEAM_SEASON: 'teamSeason',
  COUNTERPARTS: 'counterparts',
  PLAYER_DOCUMENTS: 'playerDocuments',
  PLAYER_SEARCH_INDEXES: 'playerSearchIndexes',
  TEAM_SEARCH_INDEX: 'teamSearchIndex',
  LEAGUE_METADATA: 'leagueMetadata',
  LEAGUES_MASTER: 'leaguesMaster',
  CLUBS: 'clubs',
  CLUBS_MASTER: 'clubsMaster',
})

export const STATS_AUDIT_V2_COVERED_TARGETS = Object.freeze([
  STATS_AUDIT_V2_TARGET.TEAM_SEASON,
  STATS_AUDIT_V2_TARGET.COUNTERPARTS,
  STATS_AUDIT_V2_TARGET.PLAYER_DOCUMENTS,
  STATS_AUDIT_V2_TARGET.PLAYER_SEARCH_INDEXES,
  STATS_AUDIT_V2_TARGET.TEAM_SEARCH_INDEX,
  STATS_AUDIT_V2_TARGET.LEAGUE_METADATA,
  STATS_AUDIT_V2_TARGET.LEAGUES_MASTER,
  STATS_AUDIT_V2_TARGET.CLUBS,
  STATS_AUDIT_V2_TARGET.CLUBS_MASTER,
])

export const STATS_AUDIT_V2_UNCOVERED_TARGETS = Object.freeze([])
