import assert from 'node:assert/strict'; import test from 'node:test'; import vm from 'node:vm'; import fs from 'node:fs/promises'; import path from 'node:path'; import { fileURLToPath } from 'node:url'
const file=path.join(path.dirname(fileURLToPath(import.meta.url)),'usePlayerUrlEditor.js');let context
const synthetic=(n,e)=>new vm.SyntheticModule(Object.keys(e),function(){Object.entries(e).forEach(([k,v])=>this.setExport(k,v))},{identifier:n,context})
async function load(calls=[]){const slots=[];let cursor=0;context=vm.createContext({console});const m=new vm.SourceTextModule(await fs.readFile(file,'utf8'),{context,identifier:file});await m.link(async s=>{if(s==='react')return synthetic('react',{useState:i=>{const x=cursor++;if(!(x in slots))slots[x]=i;return[slots[x],v=>slots[x]=typeof v==='function'?v(slots[x]):v]},useCallback:f=>f});if(s.includes('updateSeasonUrl'))return synthetic('write',{updatePlayerSeasonUrl:async x=>calls.push({...x})});throw Error(s)});await m.evaluate();return{ns:m.namespace,render:p=>{cursor=0;return m.namespace.default(p)}}}
const player={id:'pd',playerId:'p1',seasonContexts:[{seasonKey:'26/27',birthTeamId:'t1',birthTeamDocumentId:'d1',playerUrl:'https://a',clubName:'A'},{seasonKey:'25/26',birthTeamId:'t2',birthTeamDocumentId:'d2',playerUrl:'',clubName:'B'},{seasonKey:'26/27',birthTeamId:'t3',birthTeamDocumentId:'d3',playerUrl:'https://c',clubName:'C'}]}
test('player rows distinguish seasons and two teams in same season without URL fallback',async()=>{const {ns}=await load();const rows=ns.buildPlayerUrlRows(player);assert.equal(rows.length,3);assert.equal(new Set(rows.map(r=>r.key)).size,3);assert.equal(rows[1].originalUrl,'')})
test('one changed player row sends only that row and reloads once',async()=>{const calls=[];let reloads=0;const h=await load(calls);const p={player,reload:async()=>reloads++};h.render(p).openDrawer();let x=h.render(p);x.change(x.rows[1].key,'https://new');await h.render(p).save();assert.equal(calls.length,1);assert.equal(calls[0].birthTeamId,'t2');assert.equal(reloads,1)})

test('reload failure does not lock player editor or undo saved row',async()=>{const calls=[];const h=await load(calls);const p={player,reload:async()=>{throw new Error('reload failed')}};h.render(p).openDrawer();let x=h.render(p);x.change(x.rows[0].key,'https://new');await h.render(p).save();x=h.render(p);assert.equal(x.saving,false);assert.equal(x.rows[0].saved,true);assert.equal(x.rows[0].originalUrl,'https://new')})
